param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,
    [Parameter(Mandatory = $true)]
    [string]$OutputPath,
    [string]$Prefix = 'fa_',
    [switch]$CreateOnly
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Split-SqlStatements([string]$Text) {
    $result = New-Object System.Collections.Generic.List[string]
    $start = 0
    $single = $false
    $double = $false
    for ($i = 0; $i -lt $Text.Length; $i++) {
        $ch = $Text[$i]
        if ($ch -eq "'" -and -not $double) {
            if ($single -and $i + 1 -lt $Text.Length -and $Text[$i + 1] -eq "'") {
                $i++
            } else {
                $single = -not $single
            }
        } elseif ($ch -eq '"' -and -not $single) {
            $double = -not $double
        } elseif ($ch -eq ';' -and -not $single -and -not $double) {
            $result.Add($Text.Substring($start, $i - $start))
            $start = $i + 1
        }
    }
    if ($start -lt $Text.Length) {
        $result.Add($Text.Substring($start))
    }
    return $result
}

function Convert-Type([string]$Line) {
    $line = $Line
    $line = $line -replace '(?i)\b(bigint|int|integer|smallint|tinyint)\(\d+\)', '$1'
    $line = $line -replace '(?i)\bdecimal\(([^)]*)\)', 'numeric($1)'
    $line = $line -replace '(?i)\bdouble\b', 'double precision'
    $line = $line -replace '(?i)\btinyint\b', 'smallint'
    $line = $line -replace '(?i)\bdatetime\b', 'timestamp'
    $line = $line -replace '(?i)\byear\(\d+\)', 'integer'
    $line = $line -replace '(?i)\b(enum|set)\([^)]*\)', 'varchar(255)'
    $line = $line -replace '(?i)\s+UNSIGNED\b', ''
    $line = $line -replace '(?i)\s+CHARACTER\s+SET\s+[A-Za-z0-9_]+', ''
    $line = $line -replace '(?i)\s+COLLATE\s+[A-Za-z0-9_]+', ''
    $line = $line -replace "(?i)\s+COMMENT\s+'([^']|'')*'", ''
    return $line.Trim()
}

function Quote-Columns([string]$Columns) {
    return (($Columns -split ',') | ForEach-Object {
        $item = $_.Trim()
        if ($item -match '^`?([A-Za-z0-9_]+)`?$') { '"' + $Matches[1] + '"' } else { $item -replace '`', '"' }
    }) -join ', '
}

function Convert-CreateTable([string]$Statement) {
    $open = $Statement.IndexOf('(')
    $close = $Statement.LastIndexOf(')')
    if ($open -lt 0 -or $close -le $open) { return $null }
    $head = $Statement.Substring(0, $open)
    if ($head -notmatch '(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?`?([A-Za-z0-9_]+)`?') { return $null }
    $table = $Matches[1]
    $body = $Statement.Substring($open + 1, $close - $open - 1)
    $columns = New-Object System.Collections.Generic.List[string]
    $indexes = New-Object System.Collections.Generic.List[string]
    foreach ($rawLine in ($body -split "`r?`n")) {
        $line = $rawLine.Trim()
        if ($line -eq '') { continue }
        $line = $line.TrimEnd(',').Trim()
        if ($line -match '(?i)^PRIMARY\s+KEY\s*\(([^)]*)\)') {
            $columns.Add(('PRIMARY KEY (' + (Quote-Columns $Matches[1]) + ')'))
            continue
        }
        if ($line -match '(?i)^(?:UNIQUE\s+KEY|UNIQUE\s+INDEX)\s+`?([A-Za-z0-9_]+)`?\s*\(([^)]*)\)') {
            $columns.Add(('CONSTRAINT "' + $table + '_' + $Matches[1] + '" UNIQUE (' + (Quote-Columns $Matches[2]) + ')'))
            continue
        }
        if ($line -match '(?i)^(?:KEY|INDEX)\s+`?([A-Za-z0-9_]+)`?\s*\(([^)]*)\)') {
            $indexes.Add(('CREATE INDEX IF NOT EXISTS "' + $table + '_' + $Matches[1] + '" ON "' + $table + '" (' + (Quote-Columns $Matches[2]) + ');'))
            continue
        }

        $auto = $line -match '(?i)AUTO_INCREMENT'
        $line = Convert-Type $line
        $line = $line -replace '(?i)\blongtext\b|\bmediumtext\b', 'text'
        $line = $line -replace '(?i)\btinyint\b', 'smallint'
        $line = $line -replace '(?i)\s+AUTO_INCREMENT\b', ''
        $line = $line -replace '`', ''
        if ($auto -and $line -match '^([A-Za-z0-9_]+\s+)(.+?)\s+NOT NULL(.*)$') {
            $line = $Matches[1] + $Matches[2] + ' GENERATED BY DEFAULT AS IDENTITY NOT NULL' + $Matches[3]
        }
        if ($line -match '^([A-Za-z0-9_]+)\s+(.+)$') {
            $line = '"' + $Matches[1] + '" ' + $Matches[2]
        }
        $columns.Add($line)
    }
    if ($columns.Count -gt 0) {
        $bodyOut = ($columns | ForEach-Object { '  ' + $_ }) -join ",`n"
    } else {
        $bodyOut = ''
    }
    $tableSql = 'CREATE TABLE IF NOT EXISTS "' + $table + '" (' + "`n" + $bodyOut + "`n);"
    return @($tableSql, ($indexes -join "`n"))
}

function Convert-Statement([string]$Statement) {
    $statement = $Statement.Trim()
    if ($statement -eq '') { return '' }
    if ($statement -match '(?i)^(SET\s|LOCK\s+TABLES|UNLOCK\s+TABLES|START\s+TRANSACTION|BEGIN\s*$|COMMIT\s*$|DELIMITER\s)') { return '' }
    if ($statement -match '(?i)ALTER\s+TABLE.*(?:DISABLE|ENABLE)\s+KEYS') { return '' }
    if ($CreateOnly -and $statement -notmatch '(?i)^CREATE\s+TABLE') { return '' }

    if ($statement -match '(?i)^CREATE\s+TABLE') {
        $converted = Convert-CreateTable $statement
        if ($null -ne $converted) { return ($converted -join "`n") }
    }

    if ($statement -match '(?i)^ALTER\s+TABLE\s+([A-Za-z0-9_]+)\s+ADD\s+INDEX\s+`?([A-Za-z0-9_]+)`?\s*\(([^)]*)\)') {
        return ('CREATE INDEX IF NOT EXISTS "' + $Matches[1] + '_' + $Matches[2] + '" ON "' + $Matches[1] + '" (' + (Quote-Columns $Matches[3]) + ');')
    }
    if ($statement -match '(?i)^ALTER\s+TABLE\s+`?([A-Za-z0-9_]+)`?\s+ADD\s+COLUMN\s+(.+)$') {
        $definition = Convert-Type $Matches[2]
        $definition = $definition -replace '(?i)\s+AFTER\s+["`A-Za-z0-9_]+', ''
        return ('ALTER TABLE "' + $Matches[1] + '" ADD COLUMN IF NOT EXISTS ' + ($definition -replace '`', '"').Trim() + ';')
    }
    if ($statement -match '(?i)^ALTER\s+TABLE\s+`?([A-Za-z0-9_]+)`?\s+ADD\s+INDEX\s+(.+)$') {
        $table = $Matches[1]
        $rest = $Matches[2]
        $parts = [regex]::Matches($rest, '(?i)(?:INDEX|KEY)\s+`?([A-Za-z0-9_]+)`?\s*\(([^)]*)\)')
        $sql = New-Object System.Collections.Generic.List[string]
        foreach ($part in $parts) {
            $sql.Add(('CREATE INDEX IF NOT EXISTS "' + $table + '_' + $part.Groups[1].Value + '" ON "' + $table + '" (' + (Quote-Columns $part.Groups[2].Value) + ');'))
        }
        return ($sql -join "`n")
    }
    if ($statement -match '(?i)^ALTER\s+TABLE\s+.*\b(?:MODIFY|CHANGE|DROP\s+INDEX)\b') { return '' }

    $statement = Convert-Type $statement
    $statement = $statement -replace '(?i)\blongtext\b|\bmediumtext\b', 'text'
    $statement = $statement -replace '(?i)\btinyint\b', 'smallint'
    $statement = $statement -replace '(?i)\s+ENGINE\s*=\s*\w+', ''
    $statement = $statement -replace '(?i)\s+DEFAULT\s+CHARSET\s*=\s*\w+', ''
    $statement = $statement -replace '(?i)\s+COLLATE\s*=\s*\w+', ''
    $statement = $statement -replace '(?i)\s+AUTO_INCREMENT\s*=\s*\d+', ''
    $statement = $statement -replace '`', '"'
    $statement = $statement -replace '(?i)\s+AFTER\s+[A-Za-z0-9_]+', ''
    $statement = $statement -replace '(?i)\bADD\s+COLUMN\s+(?!IF\s+NOT\s+EXISTS)', 'ADD COLUMN IF NOT EXISTS '
    $statement = $statement -replace '(?i)\bINSERT\s+IGNORE\s+INTO\b', 'INSERT INTO'
    $statement = $statement -replace '(?i)\bUNIX_TIMESTAMP\(\)', '(EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint)'

    if ($statement -match '(?i)ON\s+DUPLICATE\s+KEY\s+UPDATE\s+(.+)$') {
        $updates = $Matches[1] -replace '(?i)VALUES\(([^)]+)\)', 'EXCLUDED.$1'
        $statement = $statement -replace '(?is)ON\s+DUPLICATE\s+KEY\s+UPDATE\s+.+$', ('ON CONFLICT DO UPDATE SET ' + $updates)
    } elseif ($statement -match '(?i)^INSERT\s+INTO\b') {
        $statement += ' ON CONFLICT DO NOTHING'
    }
    return ($statement.Trim() + ';')
}

$text = Get-Content -Raw -LiteralPath $InputPath
$text = $text -replace '(?m)^\s*--.*$', ''
$text = $text -replace '(?s)/\*.*?\*/', ''
$text = $text.Replace('__PREFIX__', $Prefix)
$output = New-Object System.Collections.Generic.List[string]
foreach ($statement in (Split-SqlStatements $text)) {
    $converted = Convert-Statement $statement
    if ($converted) { $output.Add($converted) }
}

$parent = Split-Path -Parent $OutputPath
if ($parent -and -not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
Set-Content -LiteralPath $OutputPath -Value (($output -join "`n`n") + "`n") -Encoding UTF8
