CREATE TABLE IF NOT EXISTS "fa_admin" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "username" varchar(20) DEFAULT '',
  "nickname" varchar(50) DEFAULT '',
  "password" varchar(32) DEFAULT '',
  "salt" varchar(30) DEFAULT '',
  "avatar" varchar(255) DEFAULT '',
  "email" varchar(100) DEFAULT '',
  "mobile" varchar(11) DEFAULT '',
  "loginfailure" smallint NOT NULL DEFAULT '0',
  "logintime" bigint DEFAULT NULL,
  "loginip" varchar(50) DEFAULT NULL,
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "token" varchar(59) DEFAULT '',
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_admin_username" UNIQUE ("username")
);


INSERT INTO "fa_admin" VALUES (1, 'admin', 'Admin', '', '', '/assets/img/avatar.png', 'admin@example.com', '', 0, 1491635035, '127.0.0.1',1491635035, 1491635035, '', 'normal') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "fa_admin_log" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "admin_id" int NOT NULL DEFAULT '0',
  "username" varchar(30) DEFAULT '',
  "url" varchar(1500) DEFAULT '',
  "title" varchar(100) DEFAULT '',
  "content" text NOT NULL,
  "ip" varchar(50) DEFAULT '',
  "useragent" varchar(255) DEFAULT '',
  "createtime" bigint DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_admin_log_name" ON "fa_admin_log" ("username");

CREATE TABLE IF NOT EXISTS "fa_area" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pid" int DEFAULT NULL,
  "shortname" varchar(100) DEFAULT NULL,
  "name" varchar(100) DEFAULT NULL,
  "mergename" varchar(255) DEFAULT NULL,
  "level" smallint DEFAULT NULL,
  "pinyin" varchar(100) DEFAULT NULL,
  "code" varchar(100) DEFAULT NULL,
  "zip" varchar(100) DEFAULT NULL,
  "first" varchar(50) DEFAULT NULL,
  "lng" varchar(100) DEFAULT NULL,
  "lat" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_area_pid" ON "fa_area" ("pid");

CREATE TABLE IF NOT EXISTS "fa_attachment" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "category" varchar(50) DEFAULT '',
  "admin_id" int NOT NULL DEFAULT '0',
  "user_id" int NOT NULL DEFAULT '0',
  "url" varchar(255) DEFAULT '',
  "imagewidth" int DEFAULT 0,
  "imageheight" int DEFAULT 0,
  "imagetype" varchar(30) DEFAULT '',
  "imageframes" int NOT NULL DEFAULT '0',
  "filename" varchar(100) DEFAULT '',
  "filesize" int NOT NULL DEFAULT '0',
  "mimetype" varchar(100) DEFAULT '',
  "extparam" varchar(255) DEFAULT '',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "uploadtime" bigint DEFAULT NULL,
  "storage" varchar(100) NOT NULL DEFAULT 'local',
  "sha1" varchar(40) DEFAULT '',
  PRIMARY KEY ("id")
);


INSERT INTO "fa_attachment" VALUES (1, '', 1, 0, '/assets/img/qrcode.png', '150', '150', 'png', 0, 'qrcode.png', 21859, 'image/png', '', 1491635035, 1491635035, 1491635035, 'local', '17163603d0263e4838b9387ff2cd4877e8b018f6') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "fa_auth_group" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pid" int NOT NULL DEFAULT '0',
  "name" varchar(100) DEFAULT '',
  "rules" text NOT NULL,
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "status" varchar(30) DEFAULT '',
  PRIMARY KEY ("id")
);


INSERT INTO "fa_auth_group" VALUES (1, 0, 'Admin group', '*', 1491635035, 1491635035, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_group" VALUES (2, 1, 'Second group', '13,14,16,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,40,41,42,43,44,45,46,47,48,49,50,55,56,57,58,59,60,61,62,63,64,65,1,9,10,11,7,6,8,2,4,5', 1491635035, 1491635035, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_group" VALUES (3, 2, 'Third group', '1,4,9,10,11,13,14,15,16,17,40,41,42,43,44,45,46,47,48,49,50,55,56,57,58,59,60,61,62,63,64,65,5', 1491635035, 1491635035, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_group" VALUES (4, 1, 'Second group 2', '1,4,13,14,15,16,17,55,56,57,58,59,60,61,62,63,64,65', 1491635035, 1491635035, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_group" VALUES (5, 2, 'Third group 2', '1,2,6,7,8,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34', 1491635035, 1491635035, 'normal') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "fa_auth_group_access" (
  "uid" int NOT NULL,
  "group_id" int NOT NULL,
  CONSTRAINT "fa_auth_group_access_uid_group_id" UNIQUE ("uid", "group_id")
);
CREATE INDEX IF NOT EXISTS "fa_auth_group_access_uid" ON "fa_auth_group_access" ("uid");
CREATE INDEX IF NOT EXISTS "fa_auth_group_access_group_id" ON "fa_auth_group_access" ("group_id");

INSERT INTO "fa_auth_group_access" VALUES (1, 1) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "fa_auth_rule" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" varchar(255) NOT NULL DEFAULT 'file',
  "pid" int NOT NULL DEFAULT '0',
  "name" varchar(100) DEFAULT '',
  "title" varchar(50) DEFAULT '',
  "icon" varchar(50) DEFAULT '',
  "url" varchar(255) DEFAULT '',
  "condition" varchar(255) DEFAULT '',
  "remark" varchar(255) DEFAULT '',
  "ismenu" smallint NOT NULL DEFAULT '0',
  "menutype" varchar(255) DEFAULT NULL,
  "extend" varchar(255) DEFAULT '',
  "py" varchar(30) DEFAULT '',
  "pinyin" varchar(100) DEFAULT '',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "weigh" int NOT NULL DEFAULT '0',
  "status" varchar(30) DEFAULT '',
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_auth_rule_name" UNIQUE ("name")
);
CREATE INDEX IF NOT EXISTS "fa_auth_rule_pid" ON "fa_auth_rule" ("pid");
CREATE INDEX IF NOT EXISTS "fa_auth_rule_weigh" ON "fa_auth_rule" ("weigh");

INSERT INTO "fa_auth_rule" VALUES (1, 'file', 0, 'dashboard', 'Dashboard', 'fa fa-dashboard', '', '', 'Dashboard tips', 1, NULL, '', 'kzt', 'kongzhitai', 1491635035, 1491635035, 143, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (2, 'file', 0, 'general', 'General', 'fa fa-cogs', '', '', '', 1, NULL, '', 'cggl', 'changguiguanli', 1491635035, 1491635035, 137, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (3, 'file', 0, 'category', 'Category', 'fa fa-leaf', '', '', 'Category tips', 0, NULL, '', 'flgl', 'fenleiguanli', 1491635035, 1491635035, 119, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (4, 'file', 0, 'addon', 'Addon', 'fa fa-rocket', '', '', 'Addon tips', 1, NULL, '', 'cjgl', 'chajianguanli', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (5, 'file', 0, 'auth', 'Auth', 'fa fa-group', '', '', '', 1, NULL, '', 'qxgl', 'quanxianguanli', 1491635035, 1491635035, 99, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (6, 'file', 2, 'general/config', 'Config', 'fa fa-cog', '', '', 'Config tips', 1, NULL, '', 'xtpz', 'xitongpeizhi', 1491635035, 1491635035, 60, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (7, 'file', 2, 'general/attachment', 'Attachment', 'fa fa-file-image-o', '', '', 'Attachment tips', 1, NULL, '', 'fjgl', 'fujianguanli', 1491635035, 1491635035, 53, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (8, 'file', 2, 'general/profile', 'Profile', 'fa fa-user', '', '', '', 1, NULL, '', 'grzl', 'gerenziliao', 1491635035, 1491635035, 34, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (9, 'file', 5, 'auth/admin', 'Admin', 'fa fa-user', '', '', 'Admin tips', 1, NULL, '', 'glygl', 'guanliyuanguanli', 1491635035, 1491635035, 118, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (10, 'file', 5, 'auth/adminlog', 'Admin log', 'fa fa-list-alt', '', '', 'Admin log tips', 1, NULL, '', 'glyrz', 'guanliyuanrizhi', 1491635035, 1491635035, 113, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (11, 'file', 5, 'auth/group', 'Group', 'fa fa-group', '', '', 'Group tips', 1, NULL, '', 'jsz', 'juesezu', 1491635035, 1491635035, 109, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (12, 'file', 5, 'auth/rule', 'Rule', 'fa fa-bars', '', '', 'Rule tips', 1, NULL, '', 'cdgz', 'caidanguize', 1491635035, 1491635035, 104, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (13, 'file', 1, 'dashboard/index', 'View', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 136, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (14, 'file', 1, 'dashboard/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 135, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (15, 'file', 1, 'dashboard/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 133, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (16, 'file', 1, 'dashboard/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 134, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (17, 'file', 1, 'dashboard/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 132, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (18, 'file', 6, 'general/config/index', 'View', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 52, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (19, 'file', 6, 'general/config/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 51, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (20, 'file', 6, 'general/config/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 50, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (21, 'file', 6, 'general/config/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 49, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (22, 'file', 6, 'general/config/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 48, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (23, 'file', 7, 'general/attachment/index', 'View', 'fa fa-circle-o', '', '', 'Attachment tips', 0, NULL, '', '', '', 1491635035, 1491635035, 59, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (24, 'file', 7, 'general/attachment/select', 'Select attachment', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 58, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (25, 'file', 7, 'general/attachment/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 57, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (26, 'file', 7, 'general/attachment/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 56, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (27, 'file', 7, 'general/attachment/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 55, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (28, 'file', 7, 'general/attachment/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 54, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (29, 'file', 8, 'general/profile/index', 'View', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 33, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (30, 'file', 8, 'general/profile/update', 'Update profile', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 32, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (31, 'file', 8, 'general/profile/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 31, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (32, 'file', 8, 'general/profile/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 30, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (33, 'file', 8, 'general/profile/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 29, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (34, 'file', 8, 'general/profile/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 28, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (35, 'file', 3, 'category/index', 'View', 'fa fa-circle-o', '', '', 'Category tips', 0, NULL, '', '', '', 1491635035, 1491635035, 142, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (36, 'file', 3, 'category/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 141, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (37, 'file', 3, 'category/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 140, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (38, 'file', 3, 'category/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 139, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (39, 'file', 3, 'category/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 138, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (40, 'file', 9, 'auth/admin/index', 'View', 'fa fa-circle-o', '', '', 'Admin tips', 0, NULL, '', '', '', 1491635035, 1491635035, 117, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (41, 'file', 9, 'auth/admin/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 116, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (42, 'file', 9, 'auth/admin/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 115, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (43, 'file', 9, 'auth/admin/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 114, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (44, 'file', 10, 'auth/adminlog/index', 'View', 'fa fa-circle-o', '', '', 'Admin log tips', 0, NULL, '', '', '', 1491635035, 1491635035, 112, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (45, 'file', 10, 'auth/adminlog/detail', 'Detail', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 111, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (46, 'file', 10, 'auth/adminlog/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 110, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (47, 'file', 11, 'auth/group/index', 'View', 'fa fa-circle-o', '', '', 'Group tips', 0, NULL, '', '', '', 1491635035, 1491635035, 108, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (48, 'file', 11, 'auth/group/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 107, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (49, 'file', 11, 'auth/group/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 106, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (50, 'file', 11, 'auth/group/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 105, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (51, 'file', 12, 'auth/rule/index', 'View', 'fa fa-circle-o', '', '', 'Rule tips', 0, NULL, '', '', '', 1491635035, 1491635035, 103, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (52, 'file', 12, 'auth/rule/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 102, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (53, 'file', 12, 'auth/rule/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 101, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (54, 'file', 12, 'auth/rule/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 100, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (55, 'file', 4, 'addon/index', 'View', 'fa fa-circle-o', '', '', 'Addon tips', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (56, 'file', 4, 'addon/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (57, 'file', 4, 'addon/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (58, 'file', 4, 'addon/del', 'Delete', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (59, 'file', 4, 'addon/downloaded', 'Local addon', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (60, 'file', 4, 'addon/state', 'Update state', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (63, 'file', 4, 'addon/config', 'Setting', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (64, 'file', 4, 'addon/refresh', 'Refresh', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (65, 'file', 4, 'addon/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (66, 'file', 0, 'user', 'User', 'fa fa-user-circle', '', '', '', 1, NULL, '', 'hygl', 'huiyuanguanli', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (67, 'file', 66, 'user/user', 'User', 'fa fa-user', '', '', '', 1, NULL, '', 'hygl', 'huiyuanguanli', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (68, 'file', 67, 'user/user/index', 'View', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (69, 'file', 67, 'user/user/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (70, 'file', 67, 'user/user/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (71, 'file', 67, 'user/user/del', 'Del', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (72, 'file', 67, 'user/user/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (73, 'file', 66, 'user/group', 'User group', 'fa fa-users', '', '', '', 1, NULL, '', 'hyfz', 'huiyuanfenzu', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (74, 'file', 73, 'user/group/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (75, 'file', 73, 'user/group/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (76, 'file', 73, 'user/group/index', 'View', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (77, 'file', 73, 'user/group/del', 'Del', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (78, 'file', 73, 'user/group/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (79, 'file', 66, 'user/rule', 'User rule', 'fa fa-circle-o', '', '', '', 1, NULL, '', 'hygz', 'huiyuanguize', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (80, 'file', 79, 'user/rule/index', 'View', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (81, 'file', 79, 'user/rule/del', 'Del', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (82, 'file', 79, 'user/rule/add', 'Add', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (83, 'file', 79, 'user/rule/edit', 'Edit', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_auth_rule" VALUES (84, 'file', 79, 'user/rule/multi', 'Multi', 'fa fa-circle-o', '', '', '', 0, NULL, '', '', '', 1491635035, 1491635035, 0, 'normal') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "fa_category" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pid" int NOT NULL DEFAULT '0',
  "type" varchar(30) DEFAULT '',
  "name" varchar(30) DEFAULT '',
  "nickname" varchar(50) DEFAULT '',
  "flag" varchar(255) DEFAULT '',
  "image" varchar(100) DEFAULT '',
  "keywords" varchar(255) DEFAULT '',
  "description" varchar(255) DEFAULT '',
  "diyname" varchar(30) DEFAULT '',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "weigh" int NOT NULL DEFAULT '0',
  "status" varchar(30) DEFAULT '',
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_category_weigh" ON "fa_category" ("weigh", "id");
CREATE INDEX IF NOT EXISTS "fa_category_pid" ON "fa_category" ("pid");

INSERT INTO "fa_category" VALUES (1, 0, 'page', '官方新闻', 'news', 'recommend', '/assets/img/qrcode.png', '', '', 'news', 1491635035, 1491635035, 1, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (2, 0, 'page', '移动应用', 'mobileapp', 'hot', '/assets/img/qrcode.png', '', '', 'mobileapp', 1491635035, 1491635035, 2, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (3, 2, 'page', '微信公众号', 'wechatpublic', 'index', '/assets/img/qrcode.png', '', '', 'wechatpublic', 1491635035, 1491635035, 3, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (4, 2, 'page', 'Android开发', 'android', 'recommend', '/assets/img/qrcode.png', '', '', 'android', 1491635035, 1491635035, 4, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (5, 0, 'page', '软件产品', 'software', 'recommend', '/assets/img/qrcode.png', '', '', 'software', 1491635035, 1491635035, 5, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (6, 5, 'page', '网站建站', 'website', 'recommend', '/assets/img/qrcode.png', '', '', 'website', 1491635035, 1491635035, 6, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (7, 5, 'page', '企业管理软件', 'company', 'index', '/assets/img/qrcode.png', '', '', 'company', 1491635035, 1491635035, 7, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (8, 6, 'page', 'PC端', 'website-pc', 'recommend', '/assets/img/qrcode.png', '', '', 'website-pc', 1491635035, 1491635035, 8, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (9, 6, 'page', '移动端', 'website-mobile', 'recommend', '/assets/img/qrcode.png', '', '', 'website-mobile', 1491635035, 1491635035, 9, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (10, 7, 'page', 'CRM系统 ', 'company-crm', 'recommend', '/assets/img/qrcode.png', '', '', 'company-crm', 1491635035, 1491635035, 10, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (11, 7, 'page', 'SASS平台软件', 'company-sass', 'recommend', '/assets/img/qrcode.png', '', '', 'company-sass', 1491635035, 1491635035, 11, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (12, 0, 'test', '测试1', 'test1', 'recommend', '/assets/img/qrcode.png', '', '', 'test1', 1491635035, 1491635035, 12, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_category" VALUES (13, 0, 'test', '测试2', 'test2', 'recommend', '/assets/img/qrcode.png', '', '', 'test2', 1491635035, 1491635035, 13, 'normal') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "fa_config" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(30) DEFAULT '',
  "group" varchar(30) DEFAULT '',
  "title" varchar(100) DEFAULT '',
  "tip" varchar(100) DEFAULT '',
  "type" varchar(30) DEFAULT '',
  "visible" varchar(255) DEFAULT '',
  "value" text,
  "content" text,
  "rule" varchar(100) DEFAULT '',
  "extend" varchar(255) DEFAULT '',
  "setting" varchar(255) DEFAULT '',
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_config_name" UNIQUE ("name")
);


INSERT INTO "fa_config" VALUES (1, 'name', 'basic', 'Site name', '请填写站点名称', 'string', '', '我的网站', '', 'required', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (2, 'beian', 'basic', 'Beian', '粤ICP备15000000号-1', 'string', '', '', '', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (3, 'cdnurl', 'basic', 'Cdn url', '如果全站静态资源使用第三方云储存请配置该值', 'string', '', '', '', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (4, 'version', 'basic', 'Version', '如果静态资源有变动请重新配置该值', 'string', '', '1.0.1', '', 'required', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (5, 'timezone', 'basic', 'Timezone', '', 'string', '', 'Asia/Shanghai', '', 'required', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (6, 'forbiddenip', 'basic', 'Forbidden ip', '一行一条记录', 'text', '', '', '', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (7, 'languages', 'basic', 'Languages', '', 'array', '', '{\"backend\":\"zh-cn\",\"frontend\":\"zh-cn\"}', '', 'required', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (8, 'fixedpage', 'basic', 'Fixed page', '请输入左侧菜单栏存在的链接', 'string', '', 'dashboard', '', 'required', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (9, 'categorytype', 'dictionary', 'Category type', '', 'array', '', '{\"default\":\"Default\",\"page\":\"Page\",\"article\":\"Article\",\"test\":\"Test\"}', '', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (10, 'configgroup', 'dictionary', 'Config group', '', 'array', '', '{\"basic\":\"Basic\",\"email\":\"Email\",\"dictionary\":\"Dictionary\",\"user\":\"User\",\"example\":\"Example\"}', '', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (11, 'mail_type', 'email', 'Mail type', '选择邮件发送方式', 'select', '', '1', '[\"请选择\",\"SMTP\"]', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (12, 'mail_smtp_host', 'email', 'Mail smtp host', '错误的配置发送邮件会导致服务器超时', 'string', '', 'smtp.qq.com', '', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (13, 'mail_smtp_port', 'email', 'Mail smtp port', '(不加密默认25,SSL默认465,TLS默认587)', 'string', '', '465', '', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (14, 'mail_smtp_user', 'email', 'Mail smtp user', '（填写完整用户名）', 'string', '', '', '', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (15, 'mail_smtp_pass', 'email', 'Mail smtp password', '（填写您的密码或授权码）', 'password', '', '', '', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (16, 'mail_verify_type', 'email', 'Mail vertify type', '（SMTP验证方式[推荐SSL]）', 'select', '', '2', '[\"无\",\"TLS\",\"SSL\"]', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (17, 'mail_from', 'email', 'Mail from', '', 'string', '', '', '', '', '', '') ON CONFLICT DO NOTHING;

INSERT INTO "fa_config" VALUES (18, 'attachmentcategory', 'dictionary', 'Attachment category', '', 'array', '', '{\"category1\":\"Category1\",\"category2\":\"Category2\",\"custom\":\"Custom\"}', '', '', '', '') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "fa_ems" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "event" varchar(30) DEFAULT '',
  "email" varchar(100) DEFAULT '',
  "code" varchar(10) DEFAULT '',
  "times" int NOT NULL DEFAULT 0,
  "ip" varchar(30) DEFAULT '',
  "createtime" bigint DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_sms" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "event" varchar(30) DEFAULT '',
  "mobile" varchar(20) DEFAULT '',
  "code" varchar(10) DEFAULT '',
  "times" int NOT NULL DEFAULT '0',
  "ip" varchar(30) DEFAULT '',
  "createtime" bigint DEFAULT '0',
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_test" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" int DEFAULT '0',
  "admin_id" int DEFAULT '0',
  "category_id" int DEFAULT '0',
  "category_ids" varchar(100),
  "tags" varchar(255) DEFAULT '',
  "week" varchar(255),
  "flag" varchar(255) DEFAULT '',
  "genderdata" varchar(255) DEFAULT 'male',
  "hobbydata" varchar(255),
  "title" varchar(100) DEFAULT '',
  "content" text,
  "image" varchar(100) DEFAULT '',
  "images" varchar(1500) DEFAULT '',
  "attachfile" varchar(100) DEFAULT '',
  "keywords" varchar(255) DEFAULT '',
  "description" varchar(255) DEFAULT '',
  "city" varchar(100) DEFAULT '',
  "array" varchar(255) DEFAULT '',
  "json" varchar(255) DEFAULT '',
  "multiplejson" varchar(1500) DEFAULT '',
  "price" numeric(10,2) DEFAULT '0.00',
  "views" int DEFAULT '0',
  "workrange" varchar(100) DEFAULT '',
  "startdate" date DEFAULT NULL,
  "activitytime" timestamp DEFAULT NULL,
  "year" integer DEFAULT NULL,
  "times" time DEFAULT NULL,
  "refreshtime" bigint DEFAULT NULL,
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "deletetime" bigint DEFAULT NULL,
  "weigh" int DEFAULT '0',
  "switch" smallint DEFAULT '0',
  "status" varchar(255) DEFAULT 'normal',
  "state" varchar(255) DEFAULT '1',
  PRIMARY KEY ("id")
);


INSERT INTO "fa_test" VALUES (1, 1, 1, 12, '12,13', '互联网,计算机', 'monday', 'hot,index', 'male', 'music,reading', '我是一篇测试文章', '<p>我是测试内容</p>', '/assets/img/avatar.png', '/assets/img/avatar.png,/assets/img/qrcode.png', '/assets/img/avatar.png', '关键字', '我是一篇测试文章描述，内容过多时将自动隐藏', '广西壮族自治区/百色市/平果县', '[\"a\",\"b\"]', '{\"a\":\"1\",\"b\":\"2\"}', '[{\"title\":\"标题一\",\"intro\":\"介绍一\",\"author\":\"小明\",\"age\":\"21\"}]', 0.00, 0, '2020-10-01 00:00:00 - 2021-10-31 23:59:59', '2017-07-10', '2017-07-10 18:24:45', 2017, '18:24:45', 1491635035, 1491635035, 1491635035, NULL, 0, 1, 'normal', '1') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "fa_user" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "group_id" int NOT NULL DEFAULT '0',
  "username" varchar(32) DEFAULT '',
  "nickname" varchar(50) DEFAULT '',
  "password" varchar(32) DEFAULT '',
  "salt" varchar(30) DEFAULT '',
  "email" varchar(100) DEFAULT '',
  "mobile" varchar(11) DEFAULT '',
  "avatar" varchar(255) DEFAULT '',
  "level" smallint NOT NULL DEFAULT '0',
  "gender" smallint NOT NULL DEFAULT '0',
  "birthday" date DEFAULT NULL,
  "bio" varchar(100) DEFAULT '',
  "money" numeric(10,2) NOT NULL DEFAULT '0.00',
  "score" int NOT NULL DEFAULT '0',
  "successions" int NOT NULL DEFAULT '1',
  "maxsuccessions" int NOT NULL DEFAULT '1',
  "prevtime" bigint DEFAULT NULL,
  "logintime" bigint DEFAULT NULL,
  "loginip" varchar(50) DEFAULT '',
  "loginfailure" smallint NOT NULL DEFAULT '0',
  "loginfailuretime" bigint DEFAULT NULL,
  "joinip" varchar(50) DEFAULT '',
  "jointime" bigint DEFAULT NULL,
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "token" varchar(50) DEFAULT '',
  "status" varchar(30) DEFAULT '',
  "verification" varchar(255) DEFAULT '',
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_user_username" ON "fa_user" ("username");
CREATE INDEX IF NOT EXISTS "fa_user_email" ON "fa_user" ("email");
CREATE INDEX IF NOT EXISTS "fa_user_mobile" ON "fa_user" ("mobile");

INSERT INTO "fa_user" VALUES (1, 1, 'admin', 'admin', '', '', 'admin@163.com', '13000000000', '', 0, 0, '2017-04-08', '', 0, 0, 1, 1, 1491635035, 1491635035, '127.0.0.1', 0, 1491635035,'127.0.0.1', 1491635035, 0, 1491635035, '', 'normal','') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "fa_user_group" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(50) DEFAULT '',
  "rules" text,
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);


INSERT INTO "fa_user_group" VALUES (1, '默认组', '1,2,3,4,5,6,7,8,9,10,11,12', 1491635035, 1491635035, 'normal') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "fa_user_money_log" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" int NOT NULL DEFAULT '0',
  "money" numeric(10,2) NOT NULL DEFAULT '0.00',
  "before" numeric(10,2) NOT NULL DEFAULT '0.00',
  "after" numeric(10,2) NOT NULL DEFAULT '0.00',
  "memo" varchar(255) DEFAULT '',
  "createtime" bigint DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_user_rule" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pid" int DEFAULT NULL,
  "name" varchar(50) DEFAULT NULL,
  "title" varchar(50) DEFAULT '',
  "remark" varchar(100) DEFAULT NULL,
  "ismenu" smallint DEFAULT NULL,
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "weigh" int DEFAULT '0',
  "status" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);


INSERT INTO "fa_user_rule" VALUES (1, 0, 'index', 'Frontend', '', 1, 1491635035, 1491635035, 1, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_user_rule" VALUES (2, 0, 'api', 'API Interface', '', 1, 1491635035, 1491635035, 2, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_user_rule" VALUES (3, 1, 'user', 'User Module', '', 1, 1491635035, 1491635035, 12, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_user_rule" VALUES (4, 2, 'user', 'User Module', '', 1, 1491635035, 1491635035, 11, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_user_rule" VALUES (5, 3, 'index/user/login', 'Login', '', 0, 1491635035, 1491635035, 5, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_user_rule" VALUES (6, 3, 'index/user/register', 'Register', '', 0, 1491635035, 1491635035, 7, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_user_rule" VALUES (7, 3, 'index/user/index', 'User Center', '', 0, 1491635035, 1491635035, 9, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_user_rule" VALUES (8, 3, 'index/user/profile', 'Profile', '', 0, 1491635035, 1491635035, 4, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_user_rule" VALUES (9, 4, 'api/user/login', 'Login', '', 0, 1491635035, 1491635035, 6, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_user_rule" VALUES (10, 4, 'api/user/register', 'Register', '', 0, 1491635035, 1491635035, 8, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_user_rule" VALUES (11, 4, 'api/user/index', 'User Center', '', 0, 1491635035, 1491635035, 10, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_user_rule" VALUES (12, 4, 'api/user/profile', 'Profile', '', 0, 1491635035, 1491635035, 3, 'normal') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "fa_user_score_log" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" int NOT NULL DEFAULT '0',
  "score" int NOT NULL DEFAULT '0',
  "before" int NOT NULL DEFAULT '0',
  "after" int NOT NULL DEFAULT '0',
  "memo" varchar(255) DEFAULT '',
  "createtime" bigint DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_user_token" (
  "token" varchar(50) NOT NULL,
  "user_id" int NOT NULL DEFAULT '0',
  "createtime" bigint DEFAULT NULL,
  "expiretime" bigint DEFAULT NULL,
  PRIMARY KEY ("token")
);


CREATE TABLE IF NOT EXISTS "fa_version" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "oldversion" varchar(30) DEFAULT '',
  "newversion" varchar(30) DEFAULT '',
  "packagesize" varchar(30) DEFAULT '',
  "content" varchar(500) DEFAULT '',
  "downloadurl" varchar(255) DEFAULT '',
  "enforce" smallint NOT NULL DEFAULT 0,
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "weigh" int NOT NULL DEFAULT 0,
  "status" varchar(30) DEFAULT '',
  PRIMARY KEY ("id")
);


