CREATE TABLE IF NOT EXISTS "fa_shop_address" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" int NULL DEFAULT NULL,
  "province_id" int NULL DEFAULT NULL,
  "city_id" int NULL DEFAULT NULL,
  "area_id" int NULL DEFAULT NULL,
  "receiver" varchar(255) NULL DEFAULT NULL,
  "mobile" varchar(20) NULL DEFAULT NULL,
  "address" varchar(255) NULL DEFAULT NULL,
  "zipcode" varchar(60) NULL DEFAULT NULL,
  "usednums" int NULL DEFAULT 0,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  "deletetime" bigint NULL DEFAULT NULL,
  "isdefault" smallint NULL DEFAULT 0,
  "status" varchar(30) NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_address_user_id" ON "fa_shop_address" ("user_id");

CREATE TABLE IF NOT EXISTS "fa_shop_area" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pid" int DEFAULT NULL,
  "level" smallint DEFAULT '0',
  "name" varchar(100) DEFAULT '',
  "pinyin" varchar(100) DEFAULT '',
  "py" varchar(50) DEFAULT '',
  "adcode" varchar(50) DEFAULT '',
  "zipcode" varchar(50) DEFAULT '',
  "lng" varchar(30) DEFAULT NULL,
  "lat" varchar(30) DEFAULT NULL,
  "status" varchar(255) DEFAULT 'normal',
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_area_pid" ON "fa_shop_area" ("pid");

CREATE TABLE IF NOT EXISTS "fa_shop_block" (
  "id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" varchar(30) NOT NULL DEFAULT '',
  "name" varchar(50) NOT NULL DEFAULT '',
  "title" varchar(100) NOT NULL DEFAULT '',
  "image" varchar(255) NOT NULL DEFAULT '',
  "url" varchar(255) NOT NULL DEFAULT '',
  "content" text NULL,
  "parsetpl" smallint DEFAULT '0',
  "weigh" int NOT NULL DEFAULT 0,
  "begintime" bigint DEFAULT NULL,
  "endtime" bigint DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_carts" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" int NOT NULL DEFAULT 0,
  "goods_id" int NOT NULL DEFAULT 0,
  "goods_sku_id" int NULL DEFAULT 0,
  "sceneval" smallint NULL DEFAULT 1,
  "nums" smallint NOT NULL DEFAULT 0,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_carts_user_id" ON "fa_shop_carts" ("user_id");

CREATE TABLE IF NOT EXISTS "fa_shop_category" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" smallint DEFAULT NULL,
  "pid" int NOT NULL DEFAULT '0',
  "isnav" smallint DEFAULT '0',
  "name" varchar(30) NOT NULL DEFAULT '',
  "nickname" varchar(50) NOT NULL DEFAULT '',
  "outlink" varchar(255) DEFAULT NULL,
  "flag" varchar(255) NOT NULL DEFAULT '',
  "image" varchar(255) NOT NULL DEFAULT '',
  "keywords" varchar(255) NOT NULL DEFAULT '',
  "description" varchar(255) NOT NULL DEFAULT '',
  "icon" varchar(50) NOT NULL DEFAULT '',
  "diyname" varchar(30) NOT NULL DEFAULT '',
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  "weigh" int NOT NULL DEFAULT '0',
  "status" varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_category_weigh" ON "fa_shop_category" ("weigh", "id");
CREATE INDEX IF NOT EXISTS "fa_shop_category_pid" ON "fa_shop_category" ("pid");

CREATE TABLE IF NOT EXISTS "fa_shop_collect" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" int NULL DEFAULT NULL,
  "goods_id" int NULL DEFAULT NULL,
  "status" smallint NULL DEFAULT 1,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_comment" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pid" int NOT NULL DEFAULT 0,
  "user_id" int NOT NULL DEFAULT 0,
  "order_id" int NULL DEFAULT NULL,
  "goods_id" int NOT NULL DEFAULT 0,
  "star" smallint NOT NULL DEFAULT 0,
  "content" text NULL,
  "comments" int NOT NULL DEFAULT 0,
  "images" varchar(1500) NULL DEFAULT NULL,
  "ip" varchar(50) NOT NULL DEFAULT '',
  "useragent" varchar(255) NOT NULL DEFAULT '',
  "subscribe" smallint NOT NULL DEFAULT 0,
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_comment_post_id" ON "fa_shop_comment" ("goods_id");

CREATE TABLE IF NOT EXISTS "fa_shop_freight" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NULL DEFAULT NULL,
  "type" smallint NULL DEFAULT NULL,
  "weigh" int NOT NULL DEFAULT 0,
  "switch" smallint NOT NULL DEFAULT 0,
  "num" numeric(10, 2) NULL DEFAULT 0,
  "price" numeric(10, 2) NULL DEFAULT 0.00,
  "continue_num" numeric(10, 2) NULL DEFAULT 0,
  "continue_price" numeric(10, 2) NULL DEFAULT 0.00,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_freight_items" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "freight_id" int NULL DEFAULT NULL,
  "first_num" numeric(10, 2) NULL DEFAULT 0,
  "first_price" numeric(10, 2) NULL DEFAULT 0.00,
  "continue_num" numeric(10, 2) NULL DEFAULT 0,
  "continue_price" numeric(10, 2) NULL DEFAULT 0.00,
  "area_ids" text,
  "type" smallint NOT NULL DEFAULT 0,
  "postage_area_ids" text,
  "postage_num" numeric(10, 2) NULL DEFAULT 0,
  "postage_price" numeric(10, 2) NULL DEFAULT 0.00,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_goods" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "category_id" int NOT NULL DEFAULT '0',
  "subtitle" varchar(255) DEFAULT NULL,
  "attribute_ids" varchar(255) DEFAULT NULL,
  "brand_id" int DEFAULT NULL,
  "goods_sn" varchar(100) NOT NULL DEFAULT '',
  "title" varchar(100) NOT NULL DEFAULT '',
  "keywords" varchar(100) DEFAULT '',
  "description" varchar(255) DEFAULT '',
  "marketprice" numeric(10,2) NOT NULL DEFAULT '0.00',
  "price" numeric(10,2) NOT NULL DEFAULT '0.00',
  "stocks" int NOT NULL DEFAULT '0',
  "sales" int NOT NULL DEFAULT '0',
  "guarantee_ids" varchar(50) DEFAULT NULL,
  "star" int DEFAULT '0',
  "views" int NOT NULL DEFAULT '0',
  "comments" int NOT NULL DEFAULT '0',
  "shares" int NOT NULL DEFAULT '0',
  "image" varchar(255) DEFAULT '',
  "images" varchar(1500) DEFAULT '',
  "content" text,
  "corner" varchar(10) DEFAULT NULL,
  "flag" varchar(255) DEFAULT '',
  "spectype" smallint DEFAULT '0',
  "weight" numeric(10,2) DEFAULT '0.00',
  "isvirtual" smallint NOT NULL DEFAULT '0',
  "freight_id" int DEFAULT NULL,
  "weigh" int NOT NULL DEFAULT '1',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "deletetime" bigint DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_goods_category_id" ON "fa_shop_goods" ("category_id");

CREATE TABLE IF NOT EXISTS "fa_shop_goods_sku" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "goods_id" int NOT NULL DEFAULT 0,
  "goods_sn" varchar(100) NOT NULL DEFAULT '',
  "sku_id" varchar(100) NOT NULL DEFAULT '',
  "image" varchar(255) NOT NULL DEFAULT '',
  "price" numeric(10, 2) NOT NULL DEFAULT 0.00,
  "marketprice" numeric(10, 2) NOT NULL DEFAULT 0.00,
  "stocks" int NOT NULL DEFAULT 0,
  "sales" int NOT NULL DEFAULT 0,
  "weigh" int NOT NULL DEFAULT 0,
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_goods_sku_spec" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "goods_id" int NOT NULL DEFAULT 0,
  "spec_id" int NOT NULL DEFAULT 0,
  "spec_value_id" int NOT NULL DEFAULT 0,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_menu" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pid" int NOT NULL DEFAULT 0,
  "name" varchar(50)  NULL DEFAULT '',
  "url" varchar(255)  NULL DEFAULT '',
  "weigh" int NOT NULL DEFAULT 0,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  "status" varchar(30)  NULL DEFAULT '',
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_navigation" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(50)  NULL DEFAULT NULL,
  "size" int NULL DEFAULT 60,
  "image" varchar(255)  NULL DEFAULT NULL,
  "path" varchar(255)  NULL DEFAULT NULL,
  "switch" smallint NOT NULL DEFAULT 0,
  "weigh" int NOT NULL DEFAULT 0,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_order" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_sn" varchar(50) NOT NULL DEFAULT '',
  "user_id" int NOT NULL DEFAULT '0',
  "address_id" int DEFAULT NULL,
  "province_id" int NULL DEFAULT NULL,
  "city_id" int NULL DEFAULT NULL,
  "area_id" int NULL DEFAULT NULL,
  "user_coupon_id" int DEFAULT NULL,
  "openid" varchar(100) DEFAULT NULL,
  "receiver" varchar(60) NOT NULL DEFAULT '',
  "address" varchar(255) NOT NULL DEFAULT '',
  "zipcode" varchar(60) DEFAULT '',
  "mobile" varchar(60) DEFAULT '',
  "amount" numeric(10,2) NOT NULL DEFAULT '0.00',
  "discount" numeric(10,2) NOT NULL DEFAULT '0.00',
  "shippingfee" numeric(10,2) NOT NULL DEFAULT '0.00',
  "goodsprice" numeric(10,2) NOT NULL DEFAULT '0.00',
  "saleamount" numeric(10,2) NOT NULL DEFAULT '0.00',
  "payamount" numeric(10,2) NOT NULL DEFAULT '0.00',
  "paytype" varchar(100) NOT NULL DEFAULT '',
  "method" varchar(50) DEFAULT NULL,
  "transactionid" varchar(100) DEFAULT NULL,
  "expressname" varchar(50) DEFAULT '',
  "expressno" varchar(50) DEFAULT '',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "expiretime" bigint DEFAULT NULL,
  "paytime" bigint DEFAULT NULL,
  "refundtime" bigint DEFAULT NULL,
  "shippingtime" bigint DEFAULT NULL,
  "receivetime" bigint DEFAULT NULL,
  "canceltime" bigint DEFAULT NULL,
  "deletetime" bigint DEFAULT NULL,
  "orderstate" smallint NOT NULL DEFAULT '0',
  "shippingstate" smallint NOT NULL DEFAULT '0',
  "paystate" smallint NOT NULL DEFAULT '0',
  "memo" varchar(255) DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_order_order_sn" UNIQUE ("order_sn")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_user_id" ON "fa_shop_order" ("user_id");
CREATE INDEX IF NOT EXISTS "fa_shop_order_orderstate" ON "fa_shop_order" ("orderstate");
CREATE INDEX IF NOT EXISTS "fa_shop_order_paytime" ON "fa_shop_order" ("paytime");
CREATE INDEX IF NOT EXISTS "fa_shop_order_createtime" ON "fa_shop_order" ("createtime");
CREATE INDEX IF NOT EXISTS "fa_shop_order_province_city_area" ON "fa_shop_order" ("province_id", "city_id", "area_id");

CREATE TABLE IF NOT EXISTS "fa_shop_order_aftersales" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" int DEFAULT NULL,
  "order_goods_id" int DEFAULT NULL,
  "user_id" int DEFAULT NULL,
  "type" smallint NOT NULL DEFAULT '1',
  "nums" int NULL DEFAULT 0,
  "realprice" numeric(10,2) NULL DEFAULT '0.00',
  "shippingfee" smallint NULL DEFAULT 0,
  "refund" numeric(10,2) NOT NULL DEFAULT '0.00',
  "reason" varchar(255) NOT NULL,
  "images" varchar(2500) DEFAULT NULL,
  "mark" varchar(255) DEFAULT NULL,
  "status" smallint DEFAULT '1',
  "expressname" varchar(50) DEFAULT '',
  "expressno" varchar(50) DEFAULT '',
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_order_action" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_sn" varchar(50) NOT NULL DEFAULT '0',
  "operator" varchar(30) NOT NULL DEFAULT '',
  "memo" varchar(255) NOT NULL DEFAULT '',
  "createtime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_action_order_id" ON "fa_shop_order_action" ("order_sn");

CREATE TABLE IF NOT EXISTS "fa_shop_order_goods" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_sn" varchar(50) NOT NULL DEFAULT '0',
  "goods_sn" varchar(100) NOT NULL DEFAULT '',
  "goods_id" int NOT NULL DEFAULT 0,
  "goods_sku_id" int NULL DEFAULT NULL,
  "title" varchar(255) NULL DEFAULT NULL,
  "nums" smallint NOT NULL DEFAULT 1,
  "marketprice" numeric(10, 2) NOT NULL DEFAULT 0.00,
  "price" numeric(10, 2) NOT NULL DEFAULT 0.00,
  "realprice" numeric(10,2) DEFAULT 0.00,
  "salestate" smallint DEFAULT '0',
  "commentstate" smallint DEFAULT '0',
  "attrdata" varchar(1500) NULL DEFAULT NULL,
  "image" varchar(255) NULL DEFAULT NULL,
  "weight" numeric(10,2) DEFAULT '0.00',
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_goods_order_id" ON "fa_shop_order_goods" ("order_sn");
CREATE INDEX IF NOT EXISTS "fa_shop_order_goods_goods_id" ON "fa_shop_order_goods" ("goods_id");

CREATE TABLE IF NOT EXISTS "fa_shop_spec" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(100) NOT NULL DEFAULT '',
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_spec_value" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "spec_id" int NOT NULL,
  "value" varchar(255) NOT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_electronics_order" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "shipper_id" int NULL DEFAULT NULL,
  "paytype" smallint NULL DEFAULT 1,
  "customer_name" varchar(100) NULL DEFAULT NULL,
  "customer_pwd" varchar(100) NULL DEFAULT NULL,
  "send_site" varchar(100) NULL DEFAULT NULL,
  "send_staff" varchar(100) NULL DEFAULT NULL,
  "month_code" varchar(100) NULL DEFAULT NULL,
  "is_notice" smallint NULL DEFAULT 0,
  "is_return_temp" smallint NULL DEFAULT NULL,
  "is_send_message" smallint NULL DEFAULT NULL,
  "template_size" varchar(10) NULL DEFAULT NULL,
  "operate_require" varchar(255) NULL DEFAULT NULL,
  "logistic_code" varchar(255) NULL DEFAULT NULL,
  "start_date" int NULL DEFAULT NULL,
  "end_date" int NULL DEFAULT NULL,
  "remark" varchar(255) NULL DEFAULT NULL,
  "exp_type" smallint NULL DEFAULT NULL,
  "is_return_sign_bill" smallint NULL DEFAULT NULL,
  "company" varchar(255) NULL DEFAULT NULL,
  "province_name" varchar(50) NULL DEFAULT NULL,
  "city_name" varchar(50) NULL DEFAULT NULL,
  "exp_area_name" varchar(50) NULL DEFAULT NULL,
  "address" varchar(255) NULL DEFAULT NULL,
  "name" varchar(50) NULL DEFAULT NULL,
  "tel" varchar(20) NULL DEFAULT NULL,
  "mobile" varchar(15) NULL DEFAULT NULL,
  "post_code" varchar(15) NULL DEFAULT NULL,
  "title" varchar(255) NULL DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_shipper" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(120) NULL DEFAULT NULL,
  "shipper_code" varchar(100) NULL DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_order_electronics" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_sn" varchar(50)  NULL DEFAULT NULL,
  "print_template" text  NULL,
  "kdn_order_code" varchar(100)  NULL DEFAULT NULL,
  "logistic_code" varchar(50)  NULL DEFAULT NULL,
  "shipper_code" varchar(30)  NULL DEFAULT NULL,
  "order" varchar(255) NULL DEFAULT NULL,
  "customer_name" varchar(100) NULL DEFAULT NULL,
  "customer_pwd" varchar(100) NULL DEFAULT NULL,
  "status" smallint NULL DEFAULT 0,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_sku_template" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(50) NULL DEFAULT NULL,
  "spec_names" varchar(150) NULL DEFAULT NULL,
  "spec_values" varchar(250) NULL DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_guarantee" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(50) NULL DEFAULT NULL,
  "image" varchar(255) NOT NULL DEFAULT '',
  "intro" varchar(255) NULL DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_page" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "category_id" int NOT NULL DEFAULT '0',
  "admin_id" int DEFAULT '0',
  "type" varchar(50) DEFAULT '',
  "title" varchar(50) DEFAULT '',
  "seotitle" varchar(255) DEFAULT '',
  "keywords" varchar(255) DEFAULT '',
  "description" varchar(255) DEFAULT '',
  "flag" varchar(100) DEFAULT '',
  "image" varchar(255) DEFAULT '',
  "content" text,
  "icon" varchar(50) DEFAULT '',
  "views" int NOT NULL DEFAULT '0',
  "likes" int NOT NULL DEFAULT '0',
  "dislikes" int NOT NULL DEFAULT '0',
  "diyname" varchar(100) DEFAULT '',
  "showtpl" varchar(50) DEFAULT '',
  "parsetpl" smallint DEFAULT '0',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "deletetime" bigint DEFAULT NULL,
  "weigh" int NOT NULL DEFAULT '0',
  "status" varchar(30) DEFAULT '',
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_page_diyname" ON "fa_shop_page" ("diyname");
CREATE INDEX IF NOT EXISTS "fa_shop_page_type" ON "fa_shop_page" ("type");

CREATE TABLE IF NOT EXISTS "fa_shop_brand" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(100) NULL DEFAULT NULL,
  "image" varchar(255) NULL DEFAULT '',
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  "weigh" int NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_search_log" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nums" int DEFAULT NULL,
  "keywords" varchar(100) DEFAULT NULL,
  "createtime" bigint DEFAULT NULL,
  "status" varchar(50) DEFAULT NULL,
  PRIMARY KEY ("id")
);


INSERT INTO "fa_shop_block" VALUES (1, '焦点图', 'indexfocus', '首页焦点图1', 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80', '/', '<h2 class=\"animated bounceInDown\">\r\n	畅享你的水果下午茶\r\n</h2>\r\n<p class=\"animated slideInRight\">\r\n	无限量应季水果供应<br />\r\n精选水果菠萝橙子牛油果猕猴桃\r\n</p>', 0, 2, NULL, NULL, 1624603959, 1625108648, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_block" VALUES (2, '焦点图', 'indexfocus', '首页焦点图2', 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2100&q=80', '/', '<h2 class=\"animated bounceInDown\">\r\n	美味点心大集合\r\n</h2>\r\n<p class=\"animated slideInRight\">\r\n	家庭自制美味小点心<br />\r\n在家也能吃到蓝莓咖啡蓝莓鸡蛋\r\n</p>', 0, 1, NULL, NULL, 1624603959, 1625108843, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_block" VALUES (3, 'uniapp焦点图', 'uniappfocus', 'uniapp焦点图1', '/assets/addons/shop/img/swiper1.jpg', '/pages/category/index', '', 0, 4, NULL, NULL, 1625556492, 1625556891, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_block" VALUES (4, 'uniapp焦点图', 'uniappfocus', 'uniapp焦点图2', '/assets/addons/shop/img/swiper2.jpg', '/pages/goods/goods', '', 0, 5, NULL, NULL, 1625556518, 1625556882, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_electronics_order" VALUES (1, 2, 1, '', '', '', '', '', 0, 1, 0, '130', '签名', '', 0, 0, '', 1, 0, '公司名称', '广东省', '深圳市', '罗湖区', '建设路', '阿良', '18333333333', '18333333333', '518000', '百世快递电子面单', 1623392763, 1625560310) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_freight" VALUES (1, '按件', 1, 1, 1, 1.00, 12.00, 1.00, 5.00, 1623309170, 1625558947) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_freight" VALUES (2, '按重量', 2, 2, 1, 1.00, 12.00, 1.00, 5.00, 1623309192, 1625558936) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_guarantee" VALUES (1, '放心购', '','7天无理由退货', 1624071780, 1624071780, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_guarantee" VALUES (2, '在线客服','','7*24小时在线客服', 1624071795, 1624071795, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_menu" VALUES (1, 0, '首页', '/shop', 5, 1625024797, 1625024797, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_menu" VALUES (2, 0, '会员中心', '/index/user', 4, 1625024797, 1625045590, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_menu" VALUES (3, 0, '外部链接', 'javascript:', 3, 1625024797, 1625120775, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_menu" VALUES (4, 3, '京东商城', 'https://www.jd.com', 2, 1625024797, 1625024845, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_menu" VALUES (5, 3, '淘宝', 'https://www.taobao.com', 1, 1625024797, 1625024774, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_menu" VALUES (6, 0, '关于我们', '/shop/p/aboutus', 1, 1625024797, 1625024774, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_menu" VALUES (7, 0, '优惠券', '/shop/coupon', 1, 1625024797, 1625024774, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_menu" VALUES (8, 0, '积分兑换', '/shop/exchange', 1, 1625024797, 1625024774, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_navigation" VALUES (1, '我的评论', 60, '/assets/addons/shop/navigation/comment.svg', '/pages/remark/comment', 1, 13, 1609402165, 1625555529) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_navigation" VALUES (2, '商品列表', 60, '/assets/addons/shop/navigation/commodity.svg', '/pages/goods/goods', 1, 2, 1609402235, 1625555571) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_navigation" VALUES (3, '优惠券', 60, '/assets/addons/shop/navigation/coupon.svg', '/pages/coupon/coupon', 1, 2, 1609402235, 1625555584) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_navigation" VALUES (4, '单页文章', 60, '/assets/addons/shop/navigation/page-template.svg', '/pages/page/page?id=2', 1, 2, 1609402235, 1625555594) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_navigation" VALUES (5, '积分兑换', 60, '/assets/addons/shop/navigation/exchange.svg', '/pages/score/exchange', 1, 2, 1609402235, 1625555608) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_navigation" VALUES (6, '订单列表', 60, '/assets/addons/shop/navigation/order.svg', '/pages/order/list', 1, 2, 1609402235, 1625555614) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_navigation" VALUES (7, '外部链接', 60, '/assets/addons/shop/navigation/copy-link.svg', 'https://www.baidu.com', 1, 2, 1609402235, 1625555630) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_navigation" VALUES (8, '签到排行', 60, '/assets/addons/shop/navigation/local.svg', '/pages/signin/ranking', 1, 2, 1609402235, 1625555641) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_navigation" VALUES (9, '测试导航', 60, '/assets/addons/shop/navigation/application-one.svg', '/pages/signin/signin', 1, 1, 1623308082, 1625555654) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_page" VALUES (1, 0, 0, 'page', '关于我们', '', '', '', '', '', '<p>\r\n	关于我们的内容\r\n</p>', '', 1, 225, 0, 'aboutus', 'page', 0, 1508933935, 1625557767, NULL, 1, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_page" VALUES (2, 0, 0, 'page', '用户注册协议', '', '', '', '', '', '<p>\r\n	用户注册协议\r\n</p>', '', 1, 225, 0, 'agreement', 'page', 0, 1508933935, 1625557772, NULL, 1, 'normal') ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (1, '顺丰速运', 'SF', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (2, '百世快递', 'HTKY', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (3, '中通快递', 'ZTO', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (4, '申通快递', 'STO', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (5, '圆通速递', 'YTO', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (6, '韵达速递', 'YD', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (7, '邮政快递包裹', 'YZPY', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (8, 'EMS', 'EMS', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (9, '天天快递', 'HHTT', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (10, '京东快递', 'JD', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (11, '优速快递', 'UC', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (12, '德邦快递', 'DBL', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (36, '百世快运', 'BTWL', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

INSERT INTO "fa_shop_shipper" VALUES (135, '极兔速递', 'JTSD', 1623320171, 1623320171) ON CONFLICT DO NOTHING;

ALTER TABLE "fa_shop_guarantee" ADD COLUMN IF NOT EXISTS "image" VARCHAR(255) NULL;

ALTER TABLE "fa_shop_address" ADD COLUMN IF NOT EXISTS "deletetime" bigint NULL;

ALTER TABLE "fa_shop_order" ADD COLUMN IF NOT EXISTS "goodsprice" numeric(10, 2) NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS "fa_shop_order_paytime" ON "fa_shop_order" ("paytime");
CREATE INDEX IF NOT EXISTS "fa_shop_order_createtime" ON "fa_shop_order" ("createtime");
CREATE INDEX IF NOT EXISTS "fa_shop_order_province_city_area" ON "fa_shop_order" ("province_id", "city_id", "area_id");

ALTER TABLE "fa_shop_order_aftersales" ADD COLUMN IF NOT EXISTS "nums" int NULL DEFAULT 0;
ALTER TABLE "fa_shop_order_aftersales" ADD COLUMN IF NOT EXISTS "realprice" numeric(10, 2) NULL DEFAULT 0;
ALTER TABLE "fa_shop_order_aftersales" ADD COLUMN IF NOT EXISTS "shippingfee" numeric(10,2) NULL DEFAULT '0.00';

CREATE TABLE IF NOT EXISTS "fa_shop_attribute" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "category_id" int NULL DEFAULT NULL,
  "is_search" smallint NULL DEFAULT 0,
  "is_must" smallint NULL DEFAULT 0,
  "type" varchar(255) NULL DEFAULT 'radio',
  "name" varchar(100) NULL DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_attribute_value" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "attribute_id" int NULL DEFAULT NULL,
  "name" varchar(100) NULL DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_coupon" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(100) NULL DEFAULT NULL,
  "condition_ids" varchar(50) NULL DEFAULT NULL,
  "result" smallint NULL DEFAULT NULL,
  "result_data" varchar(255) NULL DEFAULT NULL,
  "mode" varchar(255) NULL DEFAULT 'dates',
  "is_private" varchar(255) NULL DEFAULT 'no',
  "is_open" smallint NULL DEFAULT 1,
  "allow_num" int NULL DEFAULT 1,
  "give_num" int NULL DEFAULT 1,
  "received_num" int NULL DEFAULT 0,
  "receive_times" varchar(100) NULL DEFAULT NULL,
  "begintime" bigint NULL DEFAULT NULL,
  "endtime" bigint NULL DEFAULT NULL,
  "use_times" varchar(100) NULL DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_coupon_condition" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(100) NULL DEFAULT NULL,
  "type" smallint NULL DEFAULT NULL,
  "content" varchar(100) NULL DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_exchange" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" varchar(255) NULL DEFAULT NULL,
  "title" varchar(255) NULL DEFAULT NULL,
  "description" varchar(255) NULL DEFAULT NULL,
  "content" text,
  "image" varchar(225) NULL DEFAULT NULL,
  "score" int NULL DEFAULT 0,
  "stocks" int NULL DEFAULT 0,
  "sales" int NULL DEFAULT 0,
  "weigh" int NOT NULL DEFAULT 0,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  "status" varchar(255) NULL DEFAULT 'normal',
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_exchange_order" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" int NULL DEFAULT 0,
  "exchange_id" int NULL DEFAULT 0,
  "type" varchar(50) NULL DEFAULT NULL,
  "orderid" varchar(50) NULL DEFAULT NULL,
  "nums" int NULL DEFAULT 0,
  "score" int NULL DEFAULT 0,
  "receiver" varchar(30) NULL DEFAULT NULL,
  "mobile" varchar(30) NULL DEFAULT NULL,
  "address" varchar(100) NULL DEFAULT NULL,
  "memo" varchar(255) NULL DEFAULT NULL,
  "reason" varchar(100) NULL DEFAULT NULL,
  "expressname" varchar(50) NULL DEFAULT NULL,
  "expressno" varchar(50) NULL DEFAULT NULL,
  "ip" varchar(50) NULL DEFAULT NULL,
  "useragent" varchar(255) NULL DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  "status" varchar(255) NULL DEFAULT 'created',
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_goods_attr" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "attribute_id" int NULL DEFAULT NULL,
  "value_id" int NULL DEFAULT NULL,
  "goods_id" int NULL DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_goods_attr_attribute" ON "fa_shop_goods_attr" ("attribute_id", "value_id", "goods_id");

CREATE TABLE IF NOT EXISTS "fa_shop_subscribe_log" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" int NULL DEFAULT NULL,
  "order_sn" varchar(50) NULL DEFAULT NULL,
  "tpl_id" varchar(100) NULL DEFAULT NULL,
  "status" smallint NULL DEFAULT 0,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_template_msg" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" smallint NULL DEFAULT 1,
  "event" smallint NOT NULL DEFAULT 0,
  "title" varchar(150) NULL DEFAULT NULL,
  "tpl_id" varchar(50) NULL DEFAULT NULL,
  "content" varchar(500) NULL DEFAULT NULL,
  "extend" text NOT NULL,
  "page" varchar(100) NULL DEFAULT NULL,
  "switch" smallint NOT NULL DEFAULT 0,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_user_coupon" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "coupon_id" int NULL DEFAULT NULL,
  "user_id" int NULL DEFAULT NULL,
  "is_used" smallint NULL DEFAULT 1,
  "begin_time" bigint NULL DEFAULT NULL,
  "expire_time" bigint NULL DEFAULT NULL,
  "createtime" bigint NULL DEFAULT NULL,
  "updatetime" bigint NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_card" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" smallint DEFAULT '0',
  "title" varchar(100) DEFAULT NULL,
  "content" text,
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  PRIMARY KEY ("id")
);


ALTER TABLE "fa_shop_order_goods" ADD COLUMN IF NOT EXISTS "realprice" numeric(10, 2) NULL DEFAULT 0.00;

ALTER TABLE "fa_shop_order" ADD COLUMN IF NOT EXISTS "openid" varchar(100) NULL DEFAULT '';

