CREATE TABLE IF NOT EXISTS "fa_shop_schema_migration" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "version" varchar(40) NOT NULL,
  "description" varchar(255) NOT NULL DEFAULT '',
  "checksum" char(64) NOT NULL DEFAULT '',
  "executed_at" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_schema_migration_uk_schema_version" UNIQUE ("version")
);


CREATE TABLE IF NOT EXISTS "fa_shop_master_data_import" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "batch_sn" varchar(64) NOT NULL,
  "original_name" varchar(255) NOT NULL DEFAULT '',
  "file_hash" char(64) NOT NULL,
  "status" varchar(30) NOT NULL DEFAULT 'previewing',
  "total_rows" int NOT NULL DEFAULT 0,
  "valid_rows" int NOT NULL DEFAULT 0,
  "invalid_rows" int NOT NULL DEFAULT 0,
  "inserted_count" int NOT NULL DEFAULT 0,
  "updated_count" int NOT NULL DEFAULT 0,
  "error_count" int NOT NULL DEFAULT 0,
  "summary_json" text,
  "created_by" bigint NOT NULL DEFAULT 0,
  "confirmed_by" bigint NOT NULL DEFAULT 0,
  "imported_at" bigint NOT NULL DEFAULT 0,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_master_data_import_uk_master_import_batch" UNIQUE ("batch_sn"),
  CONSTRAINT "fa_shop_master_data_import_uk_master_import_hash" UNIQUE ("file_hash")
);
CREATE INDEX IF NOT EXISTS "fa_shop_master_data_import_idx_master_import_status" ON "fa_shop_master_data_import" ("status", "createtime");

CREATE TABLE IF NOT EXISTS "fa_shop_master_data_import_row" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "batch_id" bigint NOT NULL,
  "sheet_name" varchar(50) NOT NULL,
  "row_no" int NOT NULL,
  "business_key" varchar(255) NOT NULL DEFAULT '',
  "action" varchar(20) NOT NULL DEFAULT 'pending',
  "status" varchar(20) NOT NULL DEFAULT 'valid',
  "error_message" varchar(2000) NOT NULL DEFAULT '',
  "data_json" text,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_master_data_import_row_uk_master_import_row" UNIQUE ("batch_id", "sheet_name", "row_no")
);
CREATE INDEX IF NOT EXISTS "fa_shop_master_data_import_row_idx_master_import_row_status" ON "fa_shop_master_data_import_row" ("batch_id", "status", "sheet_name");

CREATE TABLE IF NOT EXISTS "fa_shop_ingredient" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ingredient_code" varchar(50) NOT NULL,
  "name" varchar(100) NOT NULL,
  "category_code" varchar(50) NOT NULL DEFAULT '',
  "default_unit" varchar(20) NOT NULL DEFAULT '',
  "description" varchar(500) NOT NULL DEFAULT '',
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  "deletetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_ingredient_uk_ingredient_code" UNIQUE ("ingredient_code")
);
CREATE INDEX IF NOT EXISTS "fa_shop_ingredient_idx_ingredient_name" ON "fa_shop_ingredient" ("name");
CREATE INDEX IF NOT EXISTS "fa_shop_ingredient_idx_ingredient_category" ON "fa_shop_ingredient" ("category_code", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_ingredient_alias" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ingredient_id" bigint NOT NULL,
  "alias" varchar(100) NOT NULL,
  "source" varchar(30) NOT NULL DEFAULT 'manual',
  "language" varchar(10) NOT NULL DEFAULT 'zh-CN',
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_ingredient_alias_uk_ingredient_alias" UNIQUE ("ingredient_id", "alias", "language")
);
CREATE INDEX IF NOT EXISTS "fa_shop_ingredient_alias_idx_alias" ON "fa_shop_ingredient_alias" ("alias", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_ingredient_sku_map" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ingredient_id" bigint NOT NULL,
  "goods_id" bigint NOT NULL DEFAULT 0,
  "sku_id" bigint NOT NULL,
  "role" varchar(20) NOT NULL DEFAULT 'primary',
  "net_value" numeric(14,3) NOT NULL DEFAULT 0,
  "net_unit" varchar(20) NOT NULL DEFAULT '',
  "convert_ratio" numeric(14,6) NOT NULL DEFAULT 1,
  "loss_rate" numeric(8,6) NOT NULL DEFAULT 0,
  "priority" int NOT NULL DEFAULT 0,
  "valid_from" bigint NOT NULL DEFAULT 0,
  "valid_to" bigint NOT NULL DEFAULT 0,
  "review_status" varchar(20) NOT NULL DEFAULT 'pending',
  "reviewer_id" bigint NOT NULL DEFAULT 0,
  "reviewed_at" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_ingredient_sku_map_uk_ingredient_sku" UNIQUE ("ingredient_id", "sku_id", "role")
);
CREATE INDEX IF NOT EXISTS "fa_shop_ingredient_sku_map_idx_map_sku" ON "fa_shop_ingredient_sku_map" ("sku_id", "status");
CREATE INDEX IF NOT EXISTS "fa_shop_ingredient_sku_map_idx_map_candidate" ON "fa_shop_ingredient_sku_map" ("ingredient_id", "status", "priority");

CREATE TABLE IF NOT EXISTS "fa_shop_sku_ingredient_component" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sku_id" bigint NOT NULL,
  "ingredient_id" bigint NOT NULL,
  "component_value" numeric(14,3) NOT NULL DEFAULT 0,
  "component_unit" varchar(20) NOT NULL DEFAULT '',
  "percentage" numeric(8,4) DEFAULT NULL,
  "is_main" smallint NOT NULL DEFAULT 0,
  "allergen_flag" smallint NOT NULL DEFAULT 0,
  "data_source" varchar(50) NOT NULL DEFAULT '',
  "data_version" varchar(50) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_sku_ingredient_component_uk_sku_component" UNIQUE ("sku_id", "ingredient_id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_sku_nutrition_fact" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sku_id" bigint NOT NULL,
  "basis_type" varchar(20) NOT NULL DEFAULT 'per_100g',
  "basis_value" numeric(14,3) NOT NULL DEFAULT 100,
  "basis_unit" varchar(20) NOT NULL DEFAULT 'g',
  "energy_kcal" numeric(14,3) DEFAULT NULL,
  "protein_g" numeric(14,3) DEFAULT NULL,
  "fat_g" numeric(14,3) DEFAULT NULL,
  "carbohydrate_g" numeric(14,3) DEFAULT NULL,
  "fiber_g" numeric(14,3) DEFAULT NULL,
  "sodium_mg" numeric(14,3) DEFAULT NULL,
  "extra_json" text,
  "source_name" varchar(100) NOT NULL DEFAULT '',
  "source_version" varchar(50) NOT NULL DEFAULT '',
  "review_status" varchar(20) NOT NULL DEFAULT 'pending',
  "reviewed_at" bigint NOT NULL DEFAULT 0,
  "valid_from" bigint NOT NULL DEFAULT 0,
  "valid_to" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_sku_nutrition_fact_idx_nutrition_sku" ON "fa_shop_sku_nutrition_fact" ("sku_id", "status", "valid_from");

CREATE TABLE IF NOT EXISTS "fa_shop_bundle_item" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "bundle_goods_id" bigint NOT NULL,
  "bundle_sku_id" bigint NOT NULL,
  "item_goods_id" bigint NOT NULL,
  "item_sku_id" bigint NOT NULL,
  "quantity" int NOT NULL DEFAULT 1,
  "sort" int NOT NULL DEFAULT 0,
  "item_snapshot_json" text,
  "version_no" int NOT NULL DEFAULT 1,
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_bundle_item_uk_bundle_item" UNIQUE ("bundle_sku_id", "version_no", "item_sku_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_bundle_item_idx_bundle_version" ON "fa_shop_bundle_item" ("bundle_goods_id", "version_no", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_recipe_bundle_map" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "recipe_ref" varchar(100) NOT NULL,
  "recipe_version_ref" varchar(100) NOT NULL DEFAULT '',
  "bundle_sku_id" bigint NOT NULL,
  "people_count" int NOT NULL DEFAULT 1,
  "meal_type" varchar(20) NOT NULL DEFAULT '',
  "priority" int NOT NULL DEFAULT 0,
  "valid_from" bigint NOT NULL DEFAULT 0,
  "valid_to" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_recipe_bundle_map_uk_recipe_bundle" UNIQUE ("recipe_ref", "recipe_version_ref", "bundle_sku_id", "people_count")
);


CREATE TABLE IF NOT EXISTS "fa_shop_catalog_version" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "catalog_version" varchar(64) NOT NULL,
  "change_type" varchar(30) NOT NULL DEFAULT 'product',
  "resource_ref" varchar(100) NOT NULL DEFAULT '',
  "summary" varchar(500) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_catalog_version_uk_catalog_version" UNIQUE ("catalog_version")
);
CREATE INDEX IF NOT EXISTS "fa_shop_catalog_version_idx_catalog_created" ON "fa_shop_catalog_version" ("createtime");

CREATE TABLE IF NOT EXISTS "fa_shop_external_identity" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "client_id" varchar(64) NOT NULL,
  "external_user_ref" varchar(100) NOT NULL,
  "user_id" bigint NOT NULL,
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_external_identity_uk_external_identity" UNIQUE ("client_id", "external_user_ref")
);
CREATE INDEX IF NOT EXISTS "fa_shop_external_identity_idx_external_identity_user" ON "fa_shop_external_identity" ("user_id", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_recommendation_package" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "package_sn" varchar(64) NOT NULL,
  "agent_client_id" varchar(64) NOT NULL,
  "agent_task_id" varchar(100) NOT NULL,
  "request_digest" char(64) NOT NULL DEFAULT '',
  "user_id" bigint NOT NULL DEFAULT 0,
  "user_ref" varchar(100) NOT NULL DEFAULT '',
  "family_ref" varchar(100) NOT NULL DEFAULT '',
  "current_version" int NOT NULL DEFAULT 1,
  "menu_version_ref" varchar(100) NOT NULL DEFAULT '',
  "catalog_version" varchar(64) NOT NULL DEFAULT '',
  "meal_date" date DEFAULT NULL,
  "nutrition_status" varchar(30) NOT NULL DEFAULT 'pending',
  "trade_status" varchar(30) NOT NULL DEFAULT 'pending',
  "confirm_status" varchar(30) NOT NULL DEFAULT 'unconfirmed',
  "confirmed_at" bigint NOT NULL DEFAULT 0,
  "expires_at" bigint NOT NULL DEFAULT 0,
  "total_amount_cent" bigint NOT NULL DEFAULT 0,
  "currency" char(3) NOT NULL DEFAULT 'CNY',
  "last_issue_code" varchar(50) NOT NULL DEFAULT '',
  "status" varchar(30) NOT NULL DEFAULT 'draft',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_recommendation_package_uk_package_sn" UNIQUE ("package_sn"),
  CONSTRAINT "fa_shop_recommendation_package_uk_agent_package_task" UNIQUE ("agent_client_id", "agent_task_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_recommendation_package_idx_package_user" ON "fa_shop_recommendation_package" ("user_id", "status", "createtime");
CREATE INDEX IF NOT EXISTS "fa_shop_recommendation_package_idx_package_expire" ON "fa_shop_recommendation_package" ("status", "expires_at");

CREATE TABLE IF NOT EXISTS "fa_shop_recommendation_package_version" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "package_id" bigint NOT NULL,
  "version_no" int NOT NULL,
  "base_version_no" int NOT NULL DEFAULT 0,
  "menu_version_ref" varchar(100) NOT NULL DEFAULT '',
  "catalog_version" varchar(64) NOT NULL DEFAULT '',
  "change_type" varchar(30) NOT NULL DEFAULT 'create',
  "nutrition_validation_id" varchar(100) NOT NULL DEFAULT '',
  "nutrition_rules_version" varchar(100) NOT NULL DEFAULT '',
  "nutrition_status" varchar(30) NOT NULL DEFAULT 'pending',
  "nutrition_summary" varchar(500) NOT NULL DEFAULT '',
  "validated_at" bigint NOT NULL DEFAULT 0,
  "trade_status" varchar(30) NOT NULL DEFAULT 'pending',
  "trade_checked_at" bigint NOT NULL DEFAULT 0,
  "recipes_snapshot_json" text,
  "requirements_snapshot_json" text,
  "issues_json" text,
  "total_amount_cent" bigint NOT NULL DEFAULT 0,
  "created_by_type" varchar(30) NOT NULL DEFAULT 'agent',
  "created_by_ref" varchar(100) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_recommendation_package_version_uk_package_version" UNIQUE ("package_id", "version_no")
);


CREATE TABLE IF NOT EXISTS "fa_shop_recommendation_package_item" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "package_version_id" bigint NOT NULL,
  "goods_id" bigint NOT NULL,
  "sku_id" bigint NOT NULL,
  "ingredient_id" bigint NOT NULL DEFAULT 0,
  "quantity" int NOT NULL DEFAULT 1,
  "planned_value" numeric(14,3) NOT NULL DEFAULT 0,
  "planned_unit" varchar(20) NOT NULL DEFAULT '',
  "unit_price_cent" bigint NOT NULL DEFAULT 0,
  "line_amount_cent" bigint NOT NULL DEFAULT 0,
  "product_snapshot_json" text,
  "sort" int NOT NULL DEFAULT 0,
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_recommendation_package_item_idx_package_item_version" ON "fa_shop_recommendation_package_item" ("package_version_id", "sort");
CREATE INDEX IF NOT EXISTS "fa_shop_recommendation_package_item_idx_package_item_sku" ON "fa_shop_recommendation_package_item" ("sku_id");

CREATE TABLE IF NOT EXISTS "fa_shop_recommendation_swap" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "swap_request_id" varchar(100) NOT NULL,
  "agent_task_id" varchar(100) NOT NULL,
  "package_id" bigint NOT NULL,
  "base_version_no" int NOT NULL,
  "result_version_no" int NOT NULL DEFAULT 0,
  "base_menu_version_ref" varchar(100) NOT NULL DEFAULT '',
  "result_menu_version_ref" varchar(100) NOT NULL DEFAULT '',
  "swap_type" varchar(30) NOT NULL DEFAULT 'recipe',
  "change_reason" varchar(500) NOT NULL DEFAULT '',
  "old_recipe_ref" varchar(100) NOT NULL DEFAULT '',
  "new_recipe_ref" varchar(100) NOT NULL DEFAULT '',
  "ingredient_changes_json" text,
  "nutrition_validation_id" varchar(100) NOT NULL DEFAULT '',
  "nutrition_status" varchar(30) NOT NULL DEFAULT 'pending',
  "trade_status" varchar(30) NOT NULL DEFAULT 'pending',
  "user_id" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'pending',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_recommendation_swap_uk_swap_request" UNIQUE ("swap_request_id"),
  CONSTRAINT "fa_shop_recommendation_swap_uk_swap_agent_task" UNIQUE ("agent_task_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_recommendation_swap_idx_swap_package" ON "fa_shop_recommendation_swap" ("package_id", "createtime");

CREATE TABLE IF NOT EXISTS "fa_shop_purchase_list" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "purchase_list_sn" varchar(64) NOT NULL,
  "user_id" bigint NOT NULL,
  "source_type" varchar(30) NOT NULL,
  "source_ref" varchar(64) NOT NULL,
  "source_version" int NOT NULL DEFAULT 1,
  "current_version" int NOT NULL DEFAULT 1,
  "address_id" bigint NOT NULL DEFAULT 0,
  "match_status" varchar(30) NOT NULL DEFAULT 'pending',
  "confirm_status" varchar(30) NOT NULL DEFAULT 'unconfirmed',
  "estimated_total_cent" bigint NOT NULL DEFAULT 0,
  "currency" char(3) NOT NULL DEFAULT 'CNY',
  "expires_at" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'draft',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_purchase_list_uk_purchase_list_sn" UNIQUE ("purchase_list_sn"),
  CONSTRAINT "fa_shop_purchase_list_uk_purchase_source" UNIQUE ("user_id", "source_type", "source_ref", "source_version")
);
CREATE INDEX IF NOT EXISTS "fa_shop_purchase_list_idx_purchase_user" ON "fa_shop_purchase_list" ("user_id", "status", "createtime");

CREATE TABLE IF NOT EXISTS "fa_shop_purchase_item" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "purchase_list_id" bigint NOT NULL,
  "list_version_no" int NOT NULL DEFAULT 1,
  "recipe_ref" varchar(100) NOT NULL DEFAULT '',
  "ingredient_id" bigint NOT NULL,
  "required_value" numeric(14,3) NOT NULL DEFAULT 0,
  "required_unit" varchar(20) NOT NULL DEFAULT '',
  "pantry_value" numeric(14,3) NOT NULL DEFAULT 0,
  "pantry_unit" varchar(20) NOT NULL DEFAULT '',
  "net_required_value" numeric(14,3) NOT NULL DEFAULT 0,
  "net_required_unit" varchar(20) NOT NULL DEFAULT '',
  "is_optional" smallint NOT NULL DEFAULT 0,
  "match_status" varchar(30) NOT NULL DEFAULT 'pending',
  "selected_match_id" bigint NOT NULL DEFAULT 0,
  "sort" int NOT NULL DEFAULT 0,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_purchase_item_idx_purchase_item_list" ON "fa_shop_purchase_item" ("purchase_list_id", "list_version_no", "sort");
CREATE INDEX IF NOT EXISTS "fa_shop_purchase_item_idx_purchase_item_ingredient" ON "fa_shop_purchase_item" ("ingredient_id", "match_status");

CREATE TABLE IF NOT EXISTS "fa_shop_purchase_match" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "purchase_item_id" bigint NOT NULL,
  "list_version_no" int NOT NULL DEFAULT 1,
  "sku_id" bigint NOT NULL,
  "rank_no" int NOT NULL DEFAULT 1,
  "required_pack_count" int NOT NULL DEFAULT 1,
  "covered_value" numeric(14,3) NOT NULL DEFAULT 0,
  "covered_unit" varchar(20) NOT NULL DEFAULT '',
  "surplus_value" numeric(14,3) NOT NULL DEFAULT 0,
  "surplus_unit" varchar(20) NOT NULL DEFAULT '',
  "unit_price_cent" bigint NOT NULL DEFAULT 0,
  "total_price_cent" bigint NOT NULL DEFAULT 0,
  "match_score" numeric(8,4) NOT NULL DEFAULT 0,
  "match_reason_json" text,
  "trade_status" varchar(30) NOT NULL DEFAULT 'pending',
  "requires_agent_revalidation" smallint NOT NULL DEFAULT 0,
  "is_selected" smallint NOT NULL DEFAULT 0,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_purchase_match_uk_purchase_match" UNIQUE ("purchase_item_id", "list_version_no", "sku_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_purchase_match_idx_match_selected" ON "fa_shop_purchase_match" ("purchase_item_id", "list_version_no", "is_selected");

CREATE TABLE IF NOT EXISTS "fa_shop_inventory_reservation" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reservation_sn" varchar(64) NOT NULL,
  "sku_id" bigint NOT NULL,
  "source_type" varchar(30) NOT NULL,
  "source_ref" varchar(64) NOT NULL,
  "source_item_ref" varchar(64) NOT NULL DEFAULT '',
  "quantity" int NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "expires_at" bigint NOT NULL DEFAULT 0,
  "confirmed_at" bigint NOT NULL DEFAULT 0,
  "released_at" bigint NOT NULL DEFAULT 0,
  "release_reason" varchar(255) NOT NULL DEFAULT '',
  "request_id" varchar(64) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_inventory_reservation_uk_reservation_sn" UNIQUE ("reservation_sn"),
  CONSTRAINT "fa_shop_inventory_reservation_uk_reservation_source" UNIQUE ("source_type", "source_ref", "source_item_ref", "sku_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_inventory_reservation_idx_reservation_expire" ON "fa_shop_inventory_reservation" ("status", "expires_at");
CREATE INDEX IF NOT EXISTS "fa_shop_inventory_reservation_idx_reservation_sku" ON "fa_shop_inventory_reservation" ("sku_id", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_inventory_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sku_id" bigint NOT NULL,
  "change_type" varchar(30) NOT NULL,
  "quantity_delta" int NOT NULL DEFAULT 0,
  "stock_before" int NOT NULL DEFAULT 0,
  "stock_after" int NOT NULL DEFAULT 0,
  "reserved_before" int NOT NULL DEFAULT 0,
  "reserved_after" int NOT NULL DEFAULT 0,
  "source_type" varchar(30) NOT NULL DEFAULT '',
  "source_ref" varchar(64) NOT NULL DEFAULT '',
  "operator_type" varchar(30) NOT NULL DEFAULT 'system',
  "operator_id" bigint NOT NULL DEFAULT 0,
  "reason" varchar(500) NOT NULL DEFAULT '',
  "request_id" varchar(64) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_inventory_log_idx_inventory_log_sku" ON "fa_shop_inventory_log" ("sku_id", "createtime");
CREATE INDEX IF NOT EXISTS "fa_shop_inventory_log_idx_inventory_log_source" ON "fa_shop_inventory_log" ("source_type", "source_ref");
CREATE INDEX IF NOT EXISTS "fa_shop_inventory_log_idx_inventory_log_request" ON "fa_shop_inventory_log" ("request_id");

CREATE TABLE IF NOT EXISTS "fa_shop_checkout_session" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkout_token_hash" char(64) NOT NULL,
  "user_id" bigint NOT NULL,
  "source_type" varchar(30) NOT NULL,
  "source_ref" varchar(64) NOT NULL,
  "source_version" int NOT NULL DEFAULT 1,
  "address_id" bigint NOT NULL DEFAULT 0,
  "pricing_snapshot_json" text,
  "trade_issues_json" text,
  "total_amount_cent" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'active',
  "expires_at" bigint NOT NULL DEFAULT 0,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_checkout_session_uk_checkout_token" UNIQUE ("checkout_token_hash")
);
CREATE INDEX IF NOT EXISTS "fa_shop_checkout_session_idx_checkout_user" ON "fa_shop_checkout_session" ("user_id", "status", "expires_at");

CREATE TABLE IF NOT EXISTS "fa_shop_order_ext" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" bigint NOT NULL,
  "order_sn" varchar(64) NOT NULL,
  "source_type" varchar(30) NOT NULL DEFAULT 'legacy',
  "source_ref" varchar(64) NOT NULL DEFAULT '',
  "source_version" int NOT NULL DEFAULT 1,
  "checkout_token_hash" char(64) DEFAULT NULL,
  "business_status" varchar(30) NOT NULL DEFAULT 'created',
  "payment_status" varchar(30) NOT NULL DEFAULT 'created',
  "fulfillment_status" varchar(30) NOT NULL DEFAULT 'pending',
  "exception_status" varchar(30) NOT NULL DEFAULT 'normal',
  "address_snapshot_json" text,
  "pricing_snapshot_json" text,
  "request_id" varchar(64) NOT NULL DEFAULT '',
  "row_version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_order_ext_uk_order_ext_order" UNIQUE ("order_id"),
  CONSTRAINT "fa_shop_order_ext_uk_order_ext_sn" UNIQUE ("order_sn"),
  CONSTRAINT "fa_shop_order_ext_uk_order_ext_checkout" UNIQUE ("checkout_token_hash")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_ext_idx_order_ext_source" ON "fa_shop_order_ext" ("source_type", "source_ref");

CREATE TABLE IF NOT EXISTS "fa_shop_order_goods_ext" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_goods_id" bigint NOT NULL,
  "order_id" bigint NOT NULL,
  "order_sn" varchar(64) NOT NULL,
  "package_version_id" bigint NOT NULL DEFAULT 0,
  "purchase_item_id" bigint NOT NULL DEFAULT 0,
  "plan_batch_id" bigint NOT NULL DEFAULT 0,
  "sku_snapshot_json" text,
  "ingredient_snapshot_json" text,
  "unit_price_cent" bigint NOT NULL DEFAULT 0,
  "line_amount_cent" bigint NOT NULL DEFAULT 0,
  "discount_allocated_cent" bigint NOT NULL DEFAULT 0,
  "refunded_quantity" int NOT NULL DEFAULT 0,
  "refunded_amount_cent" bigint NOT NULL DEFAULT 0,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_order_goods_ext_uk_order_goods_ext" UNIQUE ("order_goods_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_goods_ext_idx_order_goods_ext_order" ON "fa_shop_order_goods_ext" ("order_id");
CREATE INDEX IF NOT EXISTS "fa_shop_order_goods_ext_idx_order_goods_ext_batch" ON "fa_shop_order_goods_ext" ("plan_batch_id");

CREATE TABLE IF NOT EXISTS "fa_shop_payment_record" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "payment_sn" varchar(64) NOT NULL,
  "order_sn" varchar(64) NOT NULL,
  "channel" varchar(30) NOT NULL DEFAULT 'wechat',
  "channel_transaction_id" varchar(100) DEFAULT NULL,
  "appid" varchar(64) NOT NULL DEFAULT '',
  "mchid" varchar(64) NOT NULL DEFAULT '',
  "amount_cent" bigint NOT NULL,
  "currency" char(3) NOT NULL DEFAULT 'CNY',
  "status" varchar(30) NOT NULL DEFAULT 'created',
  "prepay_id" varchar(255) NOT NULL DEFAULT '',
  "paid_at" bigint NOT NULL DEFAULT 0,
  "closed_at" bigint NOT NULL DEFAULT 0,
  "notify_id" varchar(100) NOT NULL DEFAULT '',
  "notify_received_at" bigint NOT NULL DEFAULT 0,
  "last_query_at" bigint NOT NULL DEFAULT 0,
  "request_id" varchar(64) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_payment_record_uk_payment_sn" UNIQUE ("payment_sn"),
  CONSTRAINT "fa_shop_payment_record_uk_payment_channel_tx" UNIQUE ("channel", "channel_transaction_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_payment_record_idx_payment_order_status" ON "fa_shop_payment_record" ("order_sn", "status");
CREATE INDEX IF NOT EXISTS "fa_shop_payment_record_idx_payment_status" ON "fa_shop_payment_record" ("status", "updatetime");

CREATE TABLE IF NOT EXISTS "fa_shop_refund_record" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "refund_sn" varchar(64) NOT NULL,
  "order_sn" varchar(64) NOT NULL,
  "payment_id" bigint NOT NULL DEFAULT 0,
  "aftersale_id" bigint NOT NULL DEFAULT 0,
  "plan_change_request_id" bigint NOT NULL DEFAULT 0,
  "channel_refund_id" varchar(100) DEFAULT NULL,
  "refund_amount_cent" bigint NOT NULL,
  "currency" char(3) NOT NULL DEFAULT 'CNY',
  "reason" varchar(500) NOT NULL DEFAULT '',
  "status" varchar(30) NOT NULL DEFAULT 'created',
  "requested_at" bigint NOT NULL DEFAULT 0,
  "success_at" bigint NOT NULL DEFAULT 0,
  "notify_id" varchar(100) NOT NULL DEFAULT '',
  "last_query_at" bigint NOT NULL DEFAULT 0,
  "failure_code" varchar(50) NOT NULL DEFAULT '',
  "failure_message" varchar(500) NOT NULL DEFAULT '',
  "request_id" varchar(64) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_refund_record_uk_refund_sn" UNIQUE ("refund_sn"),
  CONSTRAINT "fa_shop_refund_record_uk_channel_refund" UNIQUE ("channel_refund_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_refund_record_idx_refund_order" ON "fa_shop_refund_record" ("order_sn", "status");
CREATE INDEX IF NOT EXISTS "fa_shop_refund_record_idx_refund_pending" ON "fa_shop_refund_record" ("status", "updatetime");

CREATE TABLE IF NOT EXISTS "fa_shop_refund_allocation" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "refund_id" bigint NOT NULL,
  "allocation_type" varchar(30) NOT NULL,
  "batch_id" bigint NOT NULL DEFAULT 0,
  "order_goods_id" bigint NOT NULL DEFAULT 0,
  "original_amount_cent" bigint NOT NULL DEFAULT 0,
  "fulfilled_amount_cent" bigint NOT NULL DEFAULT 0,
  "refundable_amount_cent" bigint NOT NULL DEFAULT 0,
  "refund_amount_cent" bigint NOT NULL DEFAULT 0,
  "formula_version" varchar(50) NOT NULL DEFAULT '',
  "calculation_json" text,
  "exception_reason_code" varchar(50) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_refund_allocation_uk_refund_allocation" UNIQUE ("refund_id", "allocation_type", "batch_id", "order_goods_id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_policy_version" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "policy_type" varchar(30) NOT NULL,
  "policy_version" varchar(50) NOT NULL,
  "title" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "content_hash" char(64) NOT NULL,
  "effective_at" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'draft',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_policy_version_uk_policy_version" UNIQUE ("policy_type", "policy_version")
);
CREATE INDEX IF NOT EXISTS "fa_shop_policy_version_idx_policy_effective" ON "fa_shop_policy_version" ("policy_type", "status", "effective_at");

CREATE TABLE IF NOT EXISTS "fa_shop_order_consent" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "consent_sn" varchar(64) NOT NULL,
  "user_id" bigint NOT NULL,
  "order_id" bigint NOT NULL DEFAULT 0,
  "checkout_token_hash" char(64) NOT NULL,
  "consent_type" varchar(30) NOT NULL DEFAULT 'plan_non_refund',
  "policy_version" varchar(50) NOT NULL,
  "policy_title" varchar(255) NOT NULL,
  "policy_content_hash" char(64) NOT NULL,
  "displayed_at" bigint NOT NULL,
  "confirmed_at" bigint NOT NULL,
  "confirm_action" varchar(30) NOT NULL DEFAULT 'explicit_click',
  "ip_hash" char(64) NOT NULL DEFAULT '',
  "device_hash" char(64) NOT NULL DEFAULT '',
  "request_id" varchar(64) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_order_consent_uk_consent_sn" UNIQUE ("consent_sn"),
  CONSTRAINT "fa_shop_order_consent_uk_consent_checkout" UNIQUE ("checkout_token_hash", "consent_type", "policy_version")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_consent_idx_consent_order" ON "fa_shop_order_consent" ("order_id", "consent_type");

CREATE TABLE IF NOT EXISTS "fa_shop_service_plan" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "plan_sn" varchar(64) NOT NULL,
  "agent_client_id" varchar(64) NOT NULL,
  "agent_task_id" varchar(100) NOT NULL,
  "request_digest" char(64) NOT NULL DEFAULT '',
  "user_id" bigint NOT NULL DEFAULT 0,
  "user_ref" varchar(100) NOT NULL DEFAULT '',
  "family_ref" varchar(100) NOT NULL DEFAULT '',
  "plan_name" varchar(255) NOT NULL DEFAULT '',
  "plan_days" int NOT NULL DEFAULT 21,
  "delivery_frequency" varchar(20) NOT NULL DEFAULT 'daily',
  "delivery_lead_days" int NOT NULL DEFAULT 1,
  "current_version" int NOT NULL DEFAULT 1,
  "requires_professional_review" smallint NOT NULL DEFAULT 0,
  "review_gate_status" varchar(30) NOT NULL DEFAULT 'not_required',
  "nutrition_status" varchar(30) NOT NULL DEFAULT 'pending',
  "trade_status" varchar(30) NOT NULL DEFAULT 'pending',
  "estimated_amount_cent" bigint NOT NULL DEFAULT 0,
  "currency" char(3) NOT NULL DEFAULT 'CNY',
  "status" varchar(30) NOT NULL DEFAULT 'draft',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_service_plan_uk_plan_sn" UNIQUE ("plan_sn"),
  CONSTRAINT "fa_shop_service_plan_uk_plan_agent_task" UNIQUE ("agent_client_id", "agent_task_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_service_plan_idx_plan_user" ON "fa_shop_service_plan" ("user_id", "status", "createtime");

CREATE TABLE IF NOT EXISTS "fa_shop_service_plan_version" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "plan_id" bigint NOT NULL,
  "version_no" int NOT NULL,
  "base_version_no" int NOT NULL DEFAULT 0,
  "profile_version_refs_json" text,
  "catalog_version" varchar(64) NOT NULL DEFAULT '',
  "change_reason" varchar(500) NOT NULL DEFAULT '',
  "nutrition_validation_id" varchar(100) NOT NULL DEFAULT '',
  "nutrition_rules_version" varchar(100) NOT NULL DEFAULT '',
  "nutrition_status" varchar(30) NOT NULL DEFAULT 'pending',
  "nutrition_summary" varchar(500) NOT NULL DEFAULT '',
  "review_ref" varchar(100) NOT NULL DEFAULT '',
  "review_gate_status" varchar(30) NOT NULL DEFAULT 'not_required',
  "trade_status" varchar(30) NOT NULL DEFAULT 'pending',
  "pricing_draft_json" text,
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_service_plan_version_uk_plan_version" UNIQUE ("plan_id", "version_no")
);


CREATE TABLE IF NOT EXISTS "fa_shop_service_plan_day" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "plan_version_id" bigint NOT NULL,
  "day_no" int NOT NULL,
  "relative_date_offset" int NOT NULL DEFAULT 0,
  "display_title" varchar(255) NOT NULL DEFAULT '',
  "daily_summary" varchar(500) NOT NULL DEFAULT '',
  "ingredient_requirements_json" text,
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_service_plan_day_uk_plan_day" UNIQUE ("plan_version_id", "day_no")
);


CREATE TABLE IF NOT EXISTS "fa_shop_service_plan_meal" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "plan_day_id" bigint NOT NULL,
  "meal_type" varchar(20) NOT NULL,
  "sort" int NOT NULL DEFAULT 0,
  "recipe_ref" varchar(100) NOT NULL,
  "recipe_version_ref" varchar(100) NOT NULL DEFAULT '',
  "recipe_name" varchar(255) NOT NULL DEFAULT '',
  "recipe_summary" varchar(500) NOT NULL DEFAULT '',
  "recipe_snapshot_json" text,
  "ingredient_requirements_json" text,
  "mapped_bundle_sku_id" bigint NOT NULL DEFAULT 0,
  "mapping_status" varchar(30) NOT NULL DEFAULT 'pending',
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_service_plan_meal_idx_plan_meal_day" ON "fa_shop_service_plan_meal" ("plan_day_id", "meal_type", "sort");

CREATE TABLE IF NOT EXISTS "fa_shop_service_plan_member" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "plan_id" bigint NOT NULL,
  "member_ref" varchar(100) NOT NULL,
  "profile_version_ref" varchar(100) NOT NULL DEFAULT '',
  "role" varchar(30) NOT NULL DEFAULT 'member',
  "display_alias" varchar(100) NOT NULL DEFAULT '',
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_service_plan_member_uk_plan_member" UNIQUE ("plan_id", "member_ref")
);


CREATE TABLE IF NOT EXISTS "fa_shop_professional_review_ref" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "review_ref" varchar(100) NOT NULL,
  "resource_type" varchar(30) NOT NULL,
  "resource_ref" varchar(100) NOT NULL,
  "resource_version" int NOT NULL,
  "member_refs_json" text,
  "review_system" varchar(50) NOT NULL DEFAULT '',
  "review_status" varchar(30) NOT NULL DEFAULT 'pending',
  "purchase_gate" varchar(30) NOT NULL DEFAULT 'blocked',
  "summary" varchar(500) NOT NULL DEFAULT '',
  "result_signature" varchar(255) NOT NULL DEFAULT '',
  "reviewed_at" bigint NOT NULL DEFAULT 0,
  "expired_at" bigint NOT NULL DEFAULT 0,
  "last_event_id" varchar(100) NOT NULL DEFAULT '',
  "payload_digest" char(64) NOT NULL DEFAULT '',
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_professional_review_ref_uk_review_ref" UNIQUE ("review_ref"),
  CONSTRAINT "fa_shop_professional_review_ref_uk_review_resource" UNIQUE ("resource_type", "resource_ref", "resource_version")
);
CREATE INDEX IF NOT EXISTS "fa_shop_professional_review_ref_idx_review_gate" ON "fa_shop_professional_review_ref" ("review_status", "purchase_gate", "updatetime");

CREATE TABLE IF NOT EXISTS "fa_shop_service_plan_order" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "plan_order_sn" varchar(64) NOT NULL,
  "order_id" bigint NOT NULL DEFAULT 0,
  "order_sn" varchar(64) NOT NULL DEFAULT '',
  "plan_id" bigint NOT NULL,
  "plan_version_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "schedule_version" int NOT NULL DEFAULT 1,
  "first_delivery_date" date NOT NULL,
  "delivery_frequency" varchar(20) NOT NULL DEFAULT 'daily',
  "total_batches" int NOT NULL DEFAULT 21,
  "completed_batches" int NOT NULL DEFAULT 0,
  "total_amount_cent" bigint NOT NULL,
  "goods_amount_cent" bigint NOT NULL DEFAULT 0,
  "shipping_fee_cent" bigint NOT NULL DEFAULT 0,
  "service_fee_cent" bigint NOT NULL DEFAULT 0,
  "discount_amount_cent" bigint NOT NULL DEFAULT 0,
  "fulfilled_amount_cent" bigint NOT NULL DEFAULT 0,
  "exception_refunded_amount_cent" bigint NOT NULL DEFAULT 0,
  "user_cancellable" smallint NOT NULL DEFAULT 0,
  "non_refund_consent_id" bigint NOT NULL,
  "status" varchar(30) NOT NULL DEFAULT 'pending_payment',
  "pause_started_at" bigint NOT NULL DEFAULT 0,
  "resume_agent_validation_ref" varchar(100) NOT NULL DEFAULT '',
  "row_version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_service_plan_order_uk_plan_order_sn" UNIQUE ("plan_order_sn"),
  CONSTRAINT "fa_shop_service_plan_order_uk_plan_order_order" UNIQUE ("order_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_service_plan_order_idx_plan_order_user" ON "fa_shop_service_plan_order" ("user_id", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_plan_delivery_batch" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "batch_sn" varchar(64) NOT NULL,
  "plan_order_id" bigint NOT NULL,
  "batch_no" int NOT NULL,
  "schedule_version" int NOT NULL DEFAULT 1,
  "meal_date" date NOT NULL,
  "delivery_date" date NOT NULL,
  "inventory_lock_at" bigint NOT NULL,
  "delivery_slot_id" bigint NOT NULL DEFAULT 0,
  "cutoff_at" bigint NOT NULL DEFAULT 0,
  "address_snapshot_json" text,
  "goods_amount_cent" bigint NOT NULL DEFAULT 0,
  "shipping_fee_cent" bigint NOT NULL DEFAULT 0,
  "service_fee_cent" bigint NOT NULL DEFAULT 0,
  "discount_amount_cent" bigint NOT NULL DEFAULT 0,
  "allocated_pay_amount_cent" bigint NOT NULL DEFAULT 0,
  "exception_refunded_amount_cent" bigint NOT NULL DEFAULT 0,
  "inventory_status" varchar(30) NOT NULL DEFAULT 'pending',
  "supplier_status" varchar(30) NOT NULL DEFAULT 'pending',
  "fulfillment_status" varchar(30) NOT NULL DEFAULT 'pending',
  "aftersale_status" varchar(30) NOT NULL DEFAULT 'none',
  "status" varchar(30) NOT NULL DEFAULT 'scheduled',
  "row_version" int NOT NULL DEFAULT 1,
  "prepared_at" bigint NOT NULL DEFAULT 0,
  "shipped_at" bigint NOT NULL DEFAULT 0,
  "delivered_at" bigint NOT NULL DEFAULT 0,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_plan_delivery_batch_uk_plan_batch" UNIQUE ("plan_order_id", "batch_no"),
  CONSTRAINT "fa_shop_plan_delivery_batch_uk_batch_sn" UNIQUE ("batch_sn")
);
CREATE INDEX IF NOT EXISTS "fa_shop_plan_delivery_batch_idx_batch_prepare" ON "fa_shop_plan_delivery_batch" ("status", "inventory_lock_at");
CREATE INDEX IF NOT EXISTS "fa_shop_plan_delivery_batch_idx_batch_delivery" ON "fa_shop_plan_delivery_batch" ("delivery_date", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_plan_delivery_batch_item" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "batch_id" bigint NOT NULL,
  "goods_id" bigint NOT NULL,
  "sku_id" bigint NOT NULL,
  "quantity" int NOT NULL,
  "unit_price_cent" bigint NOT NULL DEFAULT 0,
  "line_amount_cent" bigint NOT NULL DEFAULT 0,
  "discount_allocated_cent" bigint NOT NULL DEFAULT 0,
  "ingredient_codes_json" text,
  "sku_snapshot_json" text,
  "inventory_reservation_id" bigint NOT NULL DEFAULT 0,
  "supplier_order_item_id" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'scheduled',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_plan_delivery_batch_item_idx_batch_item" ON "fa_shop_plan_delivery_batch_item" ("batch_id", "status");
CREATE INDEX IF NOT EXISTS "fa_shop_plan_delivery_batch_item_idx_batch_item_sku" ON "fa_shop_plan_delivery_batch_item" ("sku_id", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_plan_change_request" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "change_request_sn" varchar(64) NOT NULL,
  "plan_order_id" bigint NOT NULL,
  "request_type" varchar(30) NOT NULL,
  "target_batch_ids_json" text,
  "base_version" int NOT NULL,
  "request_payload_json" text,
  "agent_revalidation_ref" varchar(100) NOT NULL DEFAULT '',
  "request_user_id" bigint NOT NULL,
  "status" varchar(30) NOT NULL DEFAULT 'pending',
  "approved_admin_id" bigint NOT NULL DEFAULT 0,
  "processed_at" bigint NOT NULL DEFAULT 0,
  "failure_code" varchar(50) NOT NULL DEFAULT '',
  "failure_message" varchar(500) NOT NULL DEFAULT '',
  "request_id" varchar(64) NOT NULL,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_plan_change_request_uk_plan_change_sn" UNIQUE ("change_request_sn"),
  CONSTRAINT "fa_shop_plan_change_request_uk_plan_change_request_id" UNIQUE ("request_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_plan_change_request_idx_plan_change_order" ON "fa_shop_plan_change_request" ("plan_order_id", "status", "createtime");

CREATE TABLE IF NOT EXISTS "fa_shop_supplier" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_code" varchar(64) NOT NULL,
  "name" varchar(100) NOT NULL,
  "company_name" varchar(255) NOT NULL DEFAULT '',
  "credit_code" varchar(64) DEFAULT NULL,
  "contact_name" varchar(100) NOT NULL DEFAULT '',
  "contact_mobile_encrypted" varchar(255) NOT NULL DEFAULT '',
  "interface_type" varchar(30) NOT NULL DEFAULT 'manual',
  "endpoint_url" varchar(500) NOT NULL DEFAULT '',
  "secret_ciphertext" varchar(500) NOT NULL DEFAULT '',
  "credential_ref" varchar(255) NOT NULL DEFAULT '',
  "service_area_json" text,
  "settlement_ref" varchar(100) NOT NULL DEFAULT '',
  "priority" int NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  "deletetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_supplier_uk_supplier_code" UNIQUE ("supplier_code"),
  CONSTRAINT "fa_shop_supplier_uk_supplier_credit_code" UNIQUE ("credit_code")
);


CREATE TABLE IF NOT EXISTS "fa_shop_supplier_sku" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_id" bigint NOT NULL,
  "sku_id" bigint NOT NULL,
  "supplier_sku_code" varchar(100) NOT NULL,
  "supplier_sku_name" varchar(255) NOT NULL DEFAULT '',
  "purchase_price_cent" bigint NOT NULL DEFAULT 0,
  "minimum_order_quantity" int NOT NULL DEFAULT 1,
  "stock_status" varchar(30) NOT NULL DEFAULT 'unknown',
  "stock_quantity" int NOT NULL DEFAULT 0,
  "stock_updated_at" bigint NOT NULL DEFAULT 0,
  "service_area_json" text,
  "priority" int NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_supplier_sku_uk_supplier_sku" UNIQUE ("supplier_id", "supplier_sku_code"),
  CONSTRAINT "fa_shop_supplier_sku_uk_supplier_platform_sku" UNIQUE ("supplier_id", "sku_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_sku_idx_supplier_sku_candidate" ON "fa_shop_supplier_sku" ("sku_id", "status", "priority");

CREATE TABLE IF NOT EXISTS "fa_shop_supplier_order" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_order_sn" varchar(64) NOT NULL,
  "supplier_id" bigint NOT NULL,
  "platform_order_sn" varchar(64) NOT NULL DEFAULT '',
  "plan_batch_id" bigint NOT NULL DEFAULT 0,
  "external_order_no" varchar(100) DEFAULT NULL,
  "status" varchar(30) NOT NULL DEFAULT 'created',
  "push_status" varchar(30) NOT NULL DEFAULT 'pending',
  "push_attempts" int NOT NULL DEFAULT 0,
  "next_retry_at" bigint NOT NULL DEFAULT 0,
  "accepted_at" bigint NOT NULL DEFAULT 0,
  "shipped_at" bigint NOT NULL DEFAULT 0,
  "completed_at" bigint NOT NULL DEFAULT 0,
  "reject_code" varchar(50) NOT NULL DEFAULT '',
  "address_snapshot_json" text,
  "request_snapshot_json" text,
  "response_snapshot_json" text,
  "row_version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_supplier_order_uk_supplier_order_sn" UNIQUE ("supplier_order_sn"),
  CONSTRAINT "fa_shop_supplier_order_uk_supplier_external_order" UNIQUE ("supplier_id", "external_order_no")
);
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_order_idx_supplier_push" ON "fa_shop_supplier_order" ("push_status", "next_retry_at");
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_order_idx_supplier_platform_order" ON "fa_shop_supplier_order" ("platform_order_sn");
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_order_idx_supplier_batch" ON "fa_shop_supplier_order" ("plan_batch_id");

CREATE TABLE IF NOT EXISTS "fa_shop_supplier_order_item" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_order_id" bigint NOT NULL,
  "order_goods_id" bigint NOT NULL DEFAULT 0,
  "plan_batch_item_id" bigint NOT NULL DEFAULT 0,
  "supplier_sku_id" bigint NOT NULL,
  "quantity" int NOT NULL,
  "purchase_price_cent" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'created',
  "unavailable_quantity" int NOT NULL DEFAULT 0,
  "reason_code" varchar(50) NOT NULL DEFAULT '',
  "item_snapshot_json" text,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_order_item_idx_supplier_order_item" ON "fa_shop_supplier_order_item" ("supplier_order_id", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_fulfillment_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "event_id" varchar(100) NOT NULL,
  "source_type" varchar(30) NOT NULL,
  "source_ref" varchar(100) NOT NULL DEFAULT '',
  "platform_order_sn" varchar(64) NOT NULL DEFAULT '',
  "plan_batch_id" bigint NOT NULL DEFAULT 0,
  "supplier_order_id" bigint NOT NULL DEFAULT 0,
  "carrier_code" varchar(50) NOT NULL DEFAULT '',
  "tracking_no" varchar(100) NOT NULL DEFAULT '',
  "source_status" varchar(50) NOT NULL DEFAULT '',
  "normalized_status" varchar(30) NOT NULL,
  "occurred_at" bigint NOT NULL,
  "location" varchar(255) NOT NULL DEFAULT '',
  "description" varchar(500) NOT NULL DEFAULT '',
  "payload_json" text,
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_fulfillment_event_uk_fulfillment_event" UNIQUE ("source_type", "event_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_fulfillment_event_idx_fulfillment_order" ON "fa_shop_fulfillment_event" ("platform_order_sn", "occurred_at");
CREATE INDEX IF NOT EXISTS "fa_shop_fulfillment_event_idx_fulfillment_batch" ON "fa_shop_fulfillment_event" ("plan_batch_id", "occurred_at");
CREATE INDEX IF NOT EXISTS "fa_shop_fulfillment_event_idx_tracking" ON "fa_shop_fulfillment_event" ("carrier_code", "tracking_no");

CREATE TABLE IF NOT EXISTS "fa_shop_delivery_area" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "area_code" varchar(64) NOT NULL,
  "name" varchar(100) NOT NULL,
  "province_code" varchar(30) NOT NULL DEFAULT '',
  "city_code" varchar(30) NOT NULL DEFAULT '',
  "district_code" varchar(30) NOT NULL DEFAULT '',
  "polygon_json" text,
  "postal_codes_json" text,
  "supplier_id" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_delivery_area_uk_delivery_area" UNIQUE ("area_code", "supplier_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_delivery_area_idx_delivery_admin" ON "fa_shop_delivery_area" ("province_code", "city_code", "district_code", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_delivery_slot" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "area_id" bigint NOT NULL,
  "slot_code" varchar(64) NOT NULL,
  "name" varchar(100) NOT NULL,
  "start_time" char(5) NOT NULL,
  "end_time" char(5) NOT NULL,
  "cutoff_minutes" int NOT NULL DEFAULT 0,
  "capacity" int NOT NULL DEFAULT 0,
  "used_capacity" int NOT NULL DEFAULT 0,
  "weekday_mask" varchar(20) NOT NULL DEFAULT '1,2,3,4,5,6,7',
  "blackout_dates_json" text,
  "extra_fee_cent" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_delivery_slot_uk_delivery_slot" UNIQUE ("area_id", "slot_code")
);


CREATE TABLE IF NOT EXISTS "fa_shop_supplier_application" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "application_sn" varchar(64) NOT NULL,
  "user_id" bigint NOT NULL DEFAULT 0,
  "company_name" varchar(255) NOT NULL,
  "credit_code" varchar(64) NOT NULL DEFAULT '',
  "contact_name" varchar(100) NOT NULL,
  "contact_mobile_encrypted" varchar(255) NOT NULL,
  "business_categories_json" text,
  "service_areas_json" text,
  "capacity_summary" varchar(1000) NOT NULL DEFAULT '',
  "qualification_files_json" text,
  "privacy_consent_version" varchar(50) NOT NULL,
  "review_status" varchar(30) NOT NULL DEFAULT 'pending',
  "review_admin_id" bigint NOT NULL DEFAULT 0,
  "review_comment" varchar(1000) NOT NULL DEFAULT '',
  "supplier_id" bigint NOT NULL DEFAULT 0,
  "submitted_at" bigint NOT NULL DEFAULT 0,
  "reviewed_at" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_supplier_application_uk_supplier_application_sn" UNIQUE ("application_sn")
);
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_application_idx_supplier_application_user" ON "fa_shop_supplier_application" ("user_id", "createtime");
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_application_idx_supplier_application_review" ON "fa_shop_supplier_application" ("review_status", "submitted_at");

CREATE TABLE IF NOT EXISTS "fa_shop_exception_order" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "exception_sn" varchar(64) NOT NULL,
  "dedupe_key" varchar(128) NOT NULL,
  "severity" varchar(20) NOT NULL DEFAULT 'medium',
  "module" varchar(30) NOT NULL,
  "exception_type" varchar(50) NOT NULL,
  "resource_type" varchar(30) NOT NULL DEFAULT '',
  "resource_ref" varchar(100) NOT NULL DEFAULT '',
  "order_sn" varchar(64) NOT NULL DEFAULT '',
  "batch_id" bigint NOT NULL DEFAULT 0,
  "supplier_order_id" bigint NOT NULL DEFAULT 0,
  "summary" varchar(500) NOT NULL,
  "detail_json" text,
  "assignee_admin_id" bigint NOT NULL DEFAULT 0,
  "status" varchar(30) NOT NULL DEFAULT 'open',
  "retry_count" int NOT NULL DEFAULT 0,
  "next_retry_at" bigint NOT NULL DEFAULT 0,
  "resolved_at" bigint NOT NULL DEFAULT 0,
  "resolution" varchar(1000) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_exception_order_uk_exception_sn" UNIQUE ("exception_sn"),
  CONSTRAINT "fa_shop_exception_order_uk_exception_dedupe" UNIQUE ("dedupe_key")
);
CREATE INDEX IF NOT EXISTS "fa_shop_exception_order_idx_exception_todo" ON "fa_shop_exception_order" ("status", "severity", "createtime");

CREATE TABLE IF NOT EXISTS "fa_shop_integration_client" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "client_id" varchar(64) NOT NULL,
  "client_type" varchar(30) NOT NULL,
  "name" varchar(100) NOT NULL,
  "secret_ciphertext" varchar(500) NOT NULL,
  "allowed_ip_json" text,
  "callback_whitelist_json" text,
  "clock_skew_seconds" int NOT NULL DEFAULT 300,
  "status" varchar(30) NOT NULL DEFAULT 'normal',
  "version" int NOT NULL DEFAULT 1,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_integration_client_uk_integration_client" UNIQUE ("client_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_integration_client_idx_integration_client_type" ON "fa_shop_integration_client" ("client_type", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_integration_nonce" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "client_id" varchar(64) NOT NULL,
  "nonce_hash" char(64) NOT NULL,
  "expires_at" bigint NOT NULL,
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_integration_nonce_uk_client_nonce" UNIQUE ("client_id", "nonce_hash")
);
CREATE INDEX IF NOT EXISTS "fa_shop_integration_nonce_idx_nonce_expire" ON "fa_shop_integration_nonce" ("expires_at");

CREATE TABLE IF NOT EXISTS "fa_shop_integration_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "request_id" varchar(64) NOT NULL,
  "partner_type" varchar(30) NOT NULL,
  "partner_code" varchar(64) NOT NULL DEFAULT '',
  "direction" varchar(20) NOT NULL,
  "interface_name" varchar(100) NOT NULL,
  "method" varchar(10) NOT NULL DEFAULT '',
  "url_path" varchar(255) NOT NULL DEFAULT '',
  "business_type" varchar(30) NOT NULL DEFAULT '',
  "business_ref" varchar(100) NOT NULL DEFAULT '',
  "request_headers_masked" text,
  "request_body_masked" text,
  "response_code" varchar(50) NOT NULL DEFAULT '',
  "response_body_masked" text,
  "http_status" int NOT NULL DEFAULT 0,
  "duration_ms" int NOT NULL DEFAULT 0,
  "success" smallint NOT NULL DEFAULT 0,
  "retry_count" int NOT NULL DEFAULT 0,
  "error_code" varchar(50) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_integration_log_idx_integration_request" ON "fa_shop_integration_log" ("request_id");
CREATE INDEX IF NOT EXISTS "fa_shop_integration_log_idx_integration_business" ON "fa_shop_integration_log" ("business_type", "business_ref");
CREATE INDEX IF NOT EXISTS "fa_shop_integration_log_idx_integration_partner" ON "fa_shop_integration_log" ("partner_code", "createtime");
CREATE INDEX IF NOT EXISTS "fa_shop_integration_log_idx_integration_failure" ON "fa_shop_integration_log" ("success", "createtime");

CREATE TABLE IF NOT EXISTS "fa_shop_idempotency_record" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "scope" varchar(100) NOT NULL,
  "client_id" varchar(64) NOT NULL,
  "idempotency_key" varchar(64) NOT NULL,
  "request_hash" char(64) NOT NULL,
  "resource_type" varchar(30) NOT NULL DEFAULT '',
  "resource_ref" varchar(100) NOT NULL DEFAULT '',
  "response_code" int NOT NULL DEFAULT 0,
  "response_body" text,
  "status" varchar(20) NOT NULL DEFAULT 'processing',
  "locked_until" bigint NOT NULL DEFAULT 0,
  "expires_at" bigint NOT NULL DEFAULT 0,
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_idempotency_record_uk_idempotency" UNIQUE ("scope", "client_id", "idempotency_key")
);
CREATE INDEX IF NOT EXISTS "fa_shop_idempotency_record_idx_idempotency_expire" ON "fa_shop_idempotency_record" ("expires_at");

CREATE TABLE IF NOT EXISTS "fa_shop_outbox_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "event_id" varchar(100) NOT NULL,
  "event_type" varchar(100) NOT NULL,
  "aggregate_type" varchar(30) NOT NULL,
  "aggregate_ref" varchar(100) NOT NULL,
  "aggregate_version" int NOT NULL,
  "destination" varchar(100) NOT NULL,
  "payload_json" text,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "attempts" int NOT NULL DEFAULT 0,
  "next_retry_at" bigint NOT NULL DEFAULT 0,
  "locked_by" varchar(100) NOT NULL DEFAULT '',
  "locked_until" bigint NOT NULL DEFAULT 0,
  "sent_at" bigint NOT NULL DEFAULT 0,
  "last_error" varchar(1000) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_outbox_event_uk_outbox_event_id" UNIQUE ("event_id"),
  CONSTRAINT "fa_shop_outbox_event_uk_outbox_aggregate_event" UNIQUE ("aggregate_type", "aggregate_ref", "aggregate_version", "event_type", "destination")
);
CREATE INDEX IF NOT EXISTS "fa_shop_outbox_event_idx_outbox_dispatch" ON "fa_shop_outbox_event" ("status", "next_retry_at");

CREATE TABLE IF NOT EXISTS "fa_shop_job_lock" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "job_name" varchar(100) NOT NULL,
  "owner" varchar(100) NOT NULL DEFAULT '',
  "locked_until" bigint NOT NULL DEFAULT 0,
  "cursor_value" varchar(255) NOT NULL DEFAULT '',
  "version" int NOT NULL DEFAULT 1,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_job_lock_uk_job_name" UNIQUE ("job_name")
);


CREATE TABLE IF NOT EXISTS "fa_shop_job_run" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "run_id" varchar(64) NOT NULL,
  "job_name" varchar(100) NOT NULL,
  "owner" varchar(100) NOT NULL DEFAULT '',
  "status" varchar(20) NOT NULL DEFAULT 'running',
  "processed_count" int NOT NULL DEFAULT 0,
  "success_count" int NOT NULL DEFAULT 0,
  "failure_count" int NOT NULL DEFAULT 0,
  "cursor_before" varchar(255) NOT NULL DEFAULT '',
  "cursor_after" varchar(255) NOT NULL DEFAULT '',
  "last_error" varchar(1000) NOT NULL DEFAULT '',
  "started_at" bigint NOT NULL DEFAULT 0,
  "finished_at" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_job_run_uk_job_run" UNIQUE ("run_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_job_run_idx_job_run_name" ON "fa_shop_job_run" ("job_name", "started_at");

CREATE TABLE IF NOT EXISTS "fa_shop_metric_daily" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "metric_date" date NOT NULL,
  "metric_group" varchar(50) NOT NULL,
  "metric_key" varchar(100) NOT NULL,
  "dimension_key" varchar(100) NOT NULL DEFAULT '',
  "metric_value" numeric(20,4) NOT NULL DEFAULT 0,
  "metric_json" text,
  "calculated_at" bigint NOT NULL DEFAULT 0,
  "updatetime" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_metric_daily_uk_metric_daily" UNIQUE ("metric_date", "metric_group", "metric_key", "dimension_key")
);
CREATE INDEX IF NOT EXISTS "fa_shop_metric_daily_idx_metric_group" ON "fa_shop_metric_daily" ("metric_group", "metric_date");

