<script setup>
import AppNavBar from '../../components/AppNavBar.vue'
import { ref } from 'vue'
import { backHome,getProfile,saveProfile } from '../../utils/profile.js'
import { onShow } from '@dcloudio/uni-app'
import { forget,editMemory } from '../../utils/memory.js'
const profile=ref(getProfile())
onShow(()=>profile.value=getProfile())
function remove(item){uni.showModal({title:'删除这条记忆？',content:'以后生成的建议不再引用它；旧对话与已支付订单不会被改写。',success:({confirm})=>{if(confirm){forget(item.id);profile.value=getProfile()}}})}
function edit(item){uni.showModal({title:'修改长期记忆',editable:true,content:item.text,success:r=>{if(!r.confirm)return;const result=editMemory(item.id,r.content||'');if(result.question)uni.showToast({title:result.question,icon:'none'});profile.value=getProfile()}})}
</script>
<template><view class="screen"><AppNavBar><view class="nav-row"><button class="icon-button" @click="backHome">‹</button><text class="nav-title">AI 记住的事</text><text></text></view></AppNavBar><view class="hero"><text class="eyebrow">LONG-TERM MEMORY</text><text class="display-title">长期记住，<br/>也随时可以改。</text><text>只收录明确且值得长期保留的家庭信息。“今天有点咸”只关联当餐反馈，不会自动变成长期忌口。</text></view><view v-if="profile.memories.length" class="memory-list"><view v-for="item in profile.memories" :key="item.id" class="memory-card card"><view class="memory-mark">忆</view><view><text>{{item.member}} · {{item.text}}</text><text>{{item.source}}</text><view><button @click="edit(item)">修改</button><button @click="remove(item)">删除</button></view></view></view></view><view v-else class="empty card"><text>还没有长期记忆</text><text>AI 发现值得长期保留的信息时，会在当天对话的“本次处理结果”中明确告知。</text></view><view class="notice"><text>资料变化后</text><text>过去生成的个体化建议需要重新复核；删除记忆不会改写已支付的计划、菜谱或配送快照。</text></view></view></template>
<style scoped>.hero{display:flex;flex-direction:column;gap:13rpx;margin:44rpx 0 28rpx}.hero .display-title{font-size:49rpx}.hero>text:last-child{color:#687a72;font-size:21rpx;line-height:1.65}.memory-list{display:flex;flex-direction:column;gap:14rpx}.memory-card{display:flex;gap:17rpx;padding:23rpx}.memory-mark{width:58rpx;height:58rpx;display:flex;align-items:center;justify-content:center;flex:0 0 auto;border-radius:18rpx 18rpx 7rpx;background:#e9ecea;color:#1d1d1f;font-weight:900}.memory-card>view:last-child{flex:1;display:flex;flex-direction:column;gap:8rpx}.memory-card>view:last-child>text:first-child{font-size:23rpx;font-weight:900}.memory-card>view:last-child>text:nth-child(2){color:#788780;font-size:18rpx}.memory-card>view:last-child>view{display:flex;gap:18rpx}.memory-card button{color:#246b50;font-size:19rpx;font-weight:800}.memory-card button:last-child{color:#a4513e}.empty{display:flex;flex-direction:column;gap:10rpx;padding:30rpx;text-align:center}.empty text:first-child{font-size:25rpx;font-weight:900}.empty text:last-child{color:#76867f;font-size:20rpx;line-height:1.6}.notice{display:flex;flex-direction:column;gap:8rpx;margin-top:22rpx;padding:22rpx;border-radius:21rpx;background:#e8eddc;color:#526a60}.notice text:first-child{font-size:21rpx;font-weight:900}.notice text:last-child{font-size:18rpx;line-height:1.6}</style>
