CREATE TABLE IF NOT EXISTS "fa_shop_admin_supplier_scope" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "admin_id" int NOT NULL,
  "supplier_id" int NOT NULL,
  "createtime" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_admin_supplier_scope_uk_admin_supplier" UNIQUE ("admin_id", "supplier_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_admin_supplier_scope_idx_supplier" ON "fa_shop_admin_supplier_scope" ("supplier_id");

