CREATE TABLE IF NOT EXISTS "fa_shop_supplier_product_pool" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_id" int NOT NULL,
  "supplier_goods_code" varchar(100) NOT NULL DEFAULT '',
  "supplier_sku_code" varchar(100) NOT NULL,
  "title" varchar(255) NOT NULL DEFAULT '',
  "spec_text" varchar(500) NOT NULL DEFAULT '',
  "barcode" varchar(100) NOT NULL DEFAULT '',
  "image" varchar(255) NOT NULL DEFAULT '',
  "supply_price" numeric(12,2) NOT NULL DEFAULT '0.00',
  "min_order_qty" int NOT NULL DEFAULT '1',
  "delivery_days" int NOT NULL DEFAULT '0',
  "fulfillment_mode" varchar(255) NOT NULL DEFAULT 'SUPPLIER_DIRECT',
  "source_payload_json" json DEFAULT NULL,
  "goods_id" int NOT NULL DEFAULT '0',
  "goods_sku_id" int NOT NULL DEFAULT '0',
  "match_status" varchar(255) NOT NULL DEFAULT 'PENDING',
  "match_method" varchar(30) NOT NULL DEFAULT 'NONE',
  "match_note" varchar(500) NOT NULL DEFAULT '',
  "sync_status" varchar(255) NOT NULL DEFAULT 'SUCCESS',
  "last_sync_time" bigint DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_supplier_product_pool_uk_supplier_sku" UNIQUE ("supplier_id", "supplier_sku_code")
);
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_product_pool_idx_match_status" ON "fa_shop_supplier_product_pool" ("match_status", "supplier_id");
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_product_pool_idx_goods_sku" ON "fa_shop_supplier_product_pool" ("goods_id", "goods_sku_id");
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_product_pool_idx_barcode" ON "fa_shop_supplier_product_pool" ("barcode");

