CREATE TABLE IF NOT EXISTS "fa_shop_cart_ext" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cart_id" int NOT NULL,
  "user_id" int NOT NULL,
  "shopping_list_id" bigint NOT NULL,
  "shopping_list_item_id" bigint NOT NULL,
  "ingredient_id" int NOT NULL,
  "preferred_supplier_id" int NOT NULL DEFAULT '0',
  "selected_supplier_id" int NOT NULL DEFAULT '0',
  "shopping_list_version" int NOT NULL,
  "source_hash" char(64) NOT NULL,
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_cart_ext_uk_cart_id" UNIQUE ("cart_id"),
  CONSTRAINT "fa_shop_cart_ext_uk_user_list_item" UNIQUE ("user_id", "shopping_list_item_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_cart_ext_idx_shopping_list" ON "fa_shop_cart_ext" ("shopping_list_id");
CREATE INDEX IF NOT EXISTS "fa_shop_cart_ext_idx_ingredient" ON "fa_shop_cart_ext" ("ingredient_id");
CREATE INDEX IF NOT EXISTS "fa_shop_cart_ext_idx_selected_supplier" ON "fa_shop_cart_ext" ("selected_supplier_id");

