CREATE TABLE IF NOT EXISTS "fa_shop_stock_reservation_adjustment" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "adjustment_sn" varchar(64) NOT NULL,
  "reservation_id" bigint NOT NULL,
  "order_goods_id" int NOT NULL DEFAULT '0',
  "aftersales_id" int NOT NULL DEFAULT '0',
  "adjustment_type" varchar(255) NOT NULL,
  "quantity" int NOT NULL,
  "biz_no" varchar(100) NOT NULL,
  "remark" varchar(500) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_stock_reservation_adjustment_uk_adjustment_sn" UNIQUE ("adjustment_sn")
);
CREATE INDEX IF NOT EXISTS "fa_shop_stock_reservation_adjustment_idx_reservation_type" ON "fa_shop_stock_reservation_adjustment" ("reservation_id", "adjustment_type");
CREATE INDEX IF NOT EXISTS "fa_shop_stock_reservation_adjustment_idx_order_goods" ON "fa_shop_stock_reservation_adjustment" ("order_goods_id");
CREATE INDEX IF NOT EXISTS "fa_shop_stock_reservation_adjustment_idx_aftersales" ON "fa_shop_stock_reservation_adjustment" ("aftersales_id");
CREATE INDEX IF NOT EXISTS "fa_shop_stock_reservation_adjustment_idx_biz_no" ON "fa_shop_stock_reservation_adjustment" ("biz_no");

CREATE TABLE IF NOT EXISTS "fa_shop_aftersales_inspection" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inspection_sn" varchar(64) NOT NULL,
  "aftersales_id" int NOT NULL,
  "supplier_order_id" bigint NOT NULL,
  "warehouse_sku_id" bigint NOT NULL,
  "accepted_quantity" int NOT NULL DEFAULT '0',
  "rejected_quantity" int NOT NULL DEFAULT '0',
  "status" varchar(255) NOT NULL,
  "biz_no" varchar(100) NOT NULL,
  "operator_type" varchar(30) NOT NULL DEFAULT 'ADMIN',
  "operator_id" int NOT NULL DEFAULT '0',
  "remark" varchar(500) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_aftersales_inspection_uk_inspection_sn" UNIQUE ("inspection_sn"),
  CONSTRAINT "fa_shop_aftersales_inspection_uk_aftersales" UNIQUE ("aftersales_id"),
  CONSTRAINT "fa_shop_aftersales_inspection_uk_biz_no" UNIQUE ("biz_no")
);
CREATE INDEX IF NOT EXISTS "fa_shop_aftersales_inspection_idx_supplier_order" ON "fa_shop_aftersales_inspection" ("supplier_order_id");
CREATE INDEX IF NOT EXISTS "fa_shop_aftersales_inspection_idx_warehouse_sku" ON "fa_shop_aftersales_inspection" ("warehouse_sku_id");

