CREATE TABLE IF NOT EXISTS "fa_shop_refund_transaction" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "refund_sn" varchar(64) NOT NULL,
  "aftersales_id" int NOT NULL,
  "order_id" int NOT NULL,
  "order_sn" varchar(50) NOT NULL,
  "channel" varchar(30) NOT NULL DEFAULT 'manual',
  "amount" numeric(12,2) NOT NULL,
  "local_action" varchar(255) NOT NULL,
  "local_payload_json" json DEFAULT NULL,
  "external_required" smallint NOT NULL DEFAULT '0',
  "status" varchar(255) NOT NULL DEFAULT 'CREATED',
  "gateway_refund_id" varchar(100) NOT NULL DEFAULT '',
  "request_json" json DEFAULT NULL,
  "response_json" json DEFAULT NULL,
  "attempt_count" int NOT NULL DEFAULT '0',
  "error_message" varchar(1000) NOT NULL DEFAULT '',
  "next_retry_at" bigint DEFAULT NULL,
  "external_succeeded_at" bigint DEFAULT NULL,
  "completed_at" bigint DEFAULT NULL,
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_refund_transaction_uk_refund_sn" UNIQUE ("refund_sn"),
  CONSTRAINT "fa_shop_refund_transaction_uk_aftersales" UNIQUE ("aftersales_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_refund_transaction_idx_status_retry" ON "fa_shop_refund_transaction" ("status", "next_retry_at");
CREATE INDEX IF NOT EXISTS "fa_shop_refund_transaction_idx_order" ON "fa_shop_refund_transaction" ("order_id");

