CREATE TABLE IF NOT EXISTS "fa_shop_schema_migration" (
  "version" varchar(64) NOT NULL,
  "description" varchar(255) NOT NULL DEFAULT '',
  "applied_at" bigint NOT NULL,
  PRIMARY KEY ("version")
);


CREATE TABLE IF NOT EXISTS "fa_shop_goods_ext" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "goods_id" int NOT NULL,
  "product_type" varchar(255) NOT NULL DEFAULT 'NORMAL',
  "composition_json" json DEFAULT NULL,
  "allergen_tags_json" json DEFAULT NULL,
  "applicable_tags_json" json DEFAULT NULL,
  "origin" varchar(255) NOT NULL DEFAULT '',
  "storage_condition" varchar(255) NOT NULL DEFAULT '',
  "shelf_life_days" int NOT NULL DEFAULT '0',
  "delivery_scope_type" varchar(255) NOT NULL DEFAULT 'SUPPLIER',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_goods_ext_uk_goods_id" UNIQUE ("goods_id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_sku_ext" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "goods_id" int NOT NULL,
  "goods_sku_id" int NOT NULL DEFAULT '0',
  "barcode" varchar(100) NOT NULL DEFAULT '',
  "unit" varchar(30) NOT NULL DEFAULT '份',
  "net_quantity" numeric(14,3) NOT NULL DEFAULT '0.000',
  "net_unit" varchar(20) NOT NULL DEFAULT 'g',
  "reference_cost_price" numeric(12,2) NOT NULL DEFAULT '0.00',
  "safety_stock" int NOT NULL DEFAULT '0',
  "batch_enabled" smallint NOT NULL DEFAULT '0',
  "expiry_enabled" smallint NOT NULL DEFAULT '0',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_sku_ext_uk_goods_sku" UNIQUE ("goods_id", "goods_sku_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_sku_ext_idx_barcode" ON "fa_shop_sku_ext" ("barcode");

CREATE TABLE IF NOT EXISTS "fa_shop_ingredient" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" varchar(64) NOT NULL,
  "name" varchar(100) NOT NULL,
  "category" varchar(100) NOT NULL DEFAULT '',
  "default_unit" varchar(20) NOT NULL DEFAULT 'g',
  "aliases_json" json DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_ingredient_uk_code" UNIQUE ("code")
);
CREATE INDEX IF NOT EXISTS "fa_shop_ingredient_idx_name" ON "fa_shop_ingredient" ("name");

CREATE TABLE IF NOT EXISTS "fa_shop_ingredient_product_map" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ingredient_id" int NOT NULL,
  "goods_id" int NOT NULL,
  "goods_sku_id" int NOT NULL DEFAULT '0',
  "content_quantity" numeric(14,3) NOT NULL DEFAULT '0.000',
  "content_unit" varchar(20) NOT NULL DEFAULT 'g',
  "conversion_rate" numeric(18,6) NOT NULL DEFAULT '1.000000',
  "priority" int NOT NULL DEFAULT '0',
  "is_substitute" smallint NOT NULL DEFAULT '0',
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_ingredient_product_map_uk_ingredient_goods_sku" UNIQUE ("ingredient_id", "goods_id", "goods_sku_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_ingredient_product_map_idx_goods_sku" ON "fa_shop_ingredient_product_map" ("goods_id", "goods_sku_id");

CREATE TABLE IF NOT EXISTS "fa_shop_goods_substitute" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "goods_id" int NOT NULL,
  "goods_sku_id" int NOT NULL DEFAULT '0',
  "substitute_goods_id" int NOT NULL,
  "substitute_goods_sku_id" int NOT NULL DEFAULT '0',
  "priority" int NOT NULL DEFAULT '0',
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_goods_substitute_uk_goods_substitute" UNIQUE ("goods_id", "goods_sku_id", "substitute_goods_id", "substitute_goods_sku_id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_supplier" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" varchar(64) NOT NULL,
  "name" varchar(150) NOT NULL,
  "company_name" varchar(200) NOT NULL DEFAULT '',
  "contact_name" varchar(60) NOT NULL DEFAULT '',
  "contact_mobile" varchar(30) NOT NULL DEFAULT '',
  "fulfillment_mode" varchar(255) NOT NULL DEFAULT 'SUPPLIER_DIRECT',
  "settlement_mode" varchar(50) NOT NULL DEFAULT '',
  "api_type" varchar(255) NOT NULL DEFAULT 'MANUAL',
  "api_config_encrypted" text,
  "priority" int NOT NULL DEFAULT '0',
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_supplier_uk_code" UNIQUE ("code")
);
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_idx_status_priority" ON "fa_shop_supplier" ("status", "priority");

CREATE TABLE IF NOT EXISTS "fa_shop_supplier_sku" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_id" int NOT NULL,
  "goods_id" int NOT NULL,
  "goods_sku_id" int NOT NULL DEFAULT '0',
  "supplier_goods_code" varchar(100) NOT NULL DEFAULT '',
  "supplier_sku_code" varchar(100) NOT NULL DEFAULT '',
  "supply_price" numeric(12,2) NOT NULL DEFAULT '0.00',
  "min_order_qty" int NOT NULL DEFAULT '1',
  "delivery_days" int NOT NULL DEFAULT '0',
  "fulfillment_mode" varchar(255) NOT NULL DEFAULT 'SUPPLIER_DIRECT',
  "priority" int NOT NULL DEFAULT '0',
  "last_sync_time" bigint DEFAULT NULL,
  "sync_status" varchar(255) NOT NULL DEFAULT 'PENDING',
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_supplier_sku_uk_supplier_goods_sku" UNIQUE ("supplier_id", "goods_id", "goods_sku_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_sku_idx_goods_sku_status" ON "fa_shop_supplier_sku" ("goods_id", "goods_sku_id", "status");
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_sku_idx_supplier_code" ON "fa_shop_supplier_sku" ("supplier_id", "supplier_sku_code");

CREATE TABLE IF NOT EXISTS "fa_shop_supplier_delivery_region" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_id" int NOT NULL,
  "province_id" int NOT NULL DEFAULT '0',
  "city_id" int NOT NULL DEFAULT '0',
  "area_id" int NOT NULL DEFAULT '0',
  "shipping_fee" numeric(12,2) NOT NULL DEFAULT '0.00',
  "free_shipping_amount" numeric(12,2) NOT NULL DEFAULT '0.00',
  "delivery_days" int NOT NULL DEFAULT '0',
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_supplier_delivery_region_uk_supplier_region" UNIQUE ("supplier_id", "province_id", "city_id", "area_id")
);


CREATE TABLE IF NOT EXISTS "fa_shop_supplier_sync_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_id" int NOT NULL,
  "sync_type" varchar(255) NOT NULL,
  "biz_key" varchar(150) NOT NULL DEFAULT '',
  "request_id" varchar(100) NOT NULL DEFAULT '',
  "request_json" json DEFAULT NULL,
  "response_json" json DEFAULT NULL,
  "status" varchar(255) NOT NULL,
  "error_message" varchar(1000) NOT NULL DEFAULT '',
  "retry_count" int NOT NULL DEFAULT '0',
  "createtime" bigint NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_sync_log_idx_supplier_type_time" ON "fa_shop_supplier_sync_log" ("supplier_id", "sync_type", "createtime");
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_sync_log_idx_status_time" ON "fa_shop_supplier_sync_log" ("status", "createtime");

CREATE TABLE IF NOT EXISTS "fa_shop_warehouse" (
  "id" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" varchar(64) NOT NULL,
  "name" varchar(120) NOT NULL,
  "owner_type" varchar(255) NOT NULL DEFAULT 'PLATFORM',
  "owner_id" int NOT NULL DEFAULT '0',
  "warehouse_type" varchar(255) NOT NULL DEFAULT 'PHYSICAL',
  "province_id" int NOT NULL DEFAULT '0',
  "city_id" int NOT NULL DEFAULT '0',
  "area_id" int NOT NULL DEFAULT '0',
  "address" varchar(255) NOT NULL DEFAULT '',
  "contact_name" varchar(60) NOT NULL DEFAULT '',
  "contact_mobile" varchar(30) NOT NULL DEFAULT '',
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_warehouse_uk_code" UNIQUE ("code")
);
CREATE INDEX IF NOT EXISTS "fa_shop_warehouse_idx_owner" ON "fa_shop_warehouse" ("owner_type", "owner_id");

CREATE TABLE IF NOT EXISTS "fa_shop_warehouse_sku" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "warehouse_id" int NOT NULL,
  "supplier_id" int NOT NULL DEFAULT '0',
  "supplier_sku_id" int NOT NULL DEFAULT '0',
  "goods_id" int NOT NULL,
  "goods_sku_id" int NOT NULL DEFAULT '0',
  "on_hand_qty" int NOT NULL DEFAULT '0',
  "locked_qty" int NOT NULL DEFAULT '0',
  "unavailable_qty" int NOT NULL DEFAULT '0',
  "in_transit_qty" int NOT NULL DEFAULT '0',
  "version" int NOT NULL DEFAULT '0',
  "last_sync_time" bigint DEFAULT NULL,
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_warehouse_sku_uk_warehouse_goods_sku" UNIQUE ("warehouse_id", "goods_id", "goods_sku_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_warehouse_sku_idx_supplier_sku" ON "fa_shop_warehouse_sku" ("supplier_id", "supplier_sku_id");
CREATE INDEX IF NOT EXISTS "fa_shop_warehouse_sku_idx_goods_sku" ON "fa_shop_warehouse_sku" ("goods_id", "goods_sku_id");

CREATE TABLE IF NOT EXISTS "fa_shop_stock_batch" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "warehouse_sku_id" bigint NOT NULL,
  "batch_no" varchar(100) NOT NULL,
  "production_date" date DEFAULT NULL,
  "expiry_date" date DEFAULT NULL,
  "cost_price" numeric(12,2) NOT NULL DEFAULT '0.00',
  "on_hand_qty" int NOT NULL DEFAULT '0',
  "locked_qty" int NOT NULL DEFAULT '0',
  "unavailable_qty" int NOT NULL DEFAULT '0',
  "status" varchar(255) NOT NULL DEFAULT 'normal',
  "createtime" bigint DEFAULT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_stock_batch_uk_warehouse_sku_batch" UNIQUE ("warehouse_sku_id", "batch_no")
);
CREATE INDEX IF NOT EXISTS "fa_shop_stock_batch_idx_expiry" ON "fa_shop_stock_batch" ("expiry_date", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_stock_reservation" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reservation_sn" varchar(64) NOT NULL,
  "biz_key" varchar(100) NOT NULL,
  "order_sn" varchar(50) NOT NULL DEFAULT '',
  "supplier_order_sn" varchar(64) NOT NULL DEFAULT '',
  "warehouse_sku_id" bigint NOT NULL,
  "goods_id" int NOT NULL,
  "goods_sku_id" int NOT NULL DEFAULT '0',
  "quantity" int NOT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'LOCKED',
  "expiretime" bigint DEFAULT NULL,
  "released_at" bigint DEFAULT NULL,
  "deducted_at" bigint DEFAULT NULL,
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_stock_reservation_uk_reservation_sn" UNIQUE ("reservation_sn"),
  CONSTRAINT "fa_shop_stock_reservation_uk_biz_warehouse_sku" UNIQUE ("biz_key", "warehouse_sku_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_stock_reservation_idx_order_status" ON "fa_shop_stock_reservation" ("order_sn", "status");
CREATE INDEX IF NOT EXISTS "fa_shop_stock_reservation_idx_expire_status" ON "fa_shop_stock_reservation" ("expiretime", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_stock_flow" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "flow_sn" varchar(64) NOT NULL,
  "warehouse_sku_id" bigint NOT NULL,
  "supplier_id" int NOT NULL DEFAULT '0',
  "warehouse_id" int NOT NULL,
  "goods_id" int NOT NULL,
  "goods_sku_id" int NOT NULL DEFAULT '0',
  "biz_type" varchar(40) NOT NULL,
  "biz_no" varchar(100) NOT NULL DEFAULT '',
  "change_on_hand" int NOT NULL DEFAULT '0',
  "change_locked" int NOT NULL DEFAULT '0',
  "before_on_hand" int NOT NULL,
  "after_on_hand" int NOT NULL,
  "before_locked" int NOT NULL,
  "after_locked" int NOT NULL,
  "operator_type" varchar(30) NOT NULL DEFAULT 'SYSTEM',
  "operator_id" int NOT NULL DEFAULT '0',
  "remark" varchar(500) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_stock_flow_uk_flow_sn" UNIQUE ("flow_sn")
);
CREATE INDEX IF NOT EXISTS "fa_shop_stock_flow_idx_warehouse_sku_time" ON "fa_shop_stock_flow" ("warehouse_sku_id", "createtime");
CREATE INDEX IF NOT EXISTS "fa_shop_stock_flow_idx_biz" ON "fa_shop_stock_flow" ("biz_type", "biz_no");

CREATE TABLE IF NOT EXISTS "fa_shop_shopping_list" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "list_sn" varchar(64) NOT NULL,
  "user_id" int NOT NULL,
  "menu_version_id" varchar(100) NOT NULL,
  "list_version" int NOT NULL DEFAULT '1',
  "source_hash" char(64) NOT NULL DEFAULT '',
  "status" varchar(255) NOT NULL DEFAULT 'DRAFT',
  "confirmed_at" bigint DEFAULT NULL,
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_shopping_list_uk_list_sn" UNIQUE ("list_sn"),
  CONSTRAINT "fa_shop_shopping_list_uk_user_menu_version" UNIQUE ("user_id", "menu_version_id", "list_version")
);
CREATE INDEX IF NOT EXISTS "fa_shop_shopping_list_idx_user_status" ON "fa_shop_shopping_list" ("user_id", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_shopping_list_item" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "shopping_list_id" bigint NOT NULL,
  "ingredient_id" int NOT NULL,
  "required_quantity" numeric(14,3) NOT NULL,
  "home_quantity" numeric(14,3) NOT NULL DEFAULT '0.000',
  "net_quantity" numeric(14,3) NOT NULL,
  "unit" varchar(20) NOT NULL,
  "source_refs_json" json DEFAULT NULL,
  "constraint_result_json" json DEFAULT NULL,
  "selected_goods_id" int NOT NULL DEFAULT '0',
  "selected_goods_sku_id" int NOT NULL DEFAULT '0',
  "selected_supplier_id" int NOT NULL DEFAULT '0',
  "purchase_quantity" int NOT NULL DEFAULT '0',
  "covered_quantity" numeric(14,3) NOT NULL DEFAULT '0.000',
  "shortage_quantity" numeric(14,3) NOT NULL DEFAULT '0.000',
  "excess_quantity" numeric(14,3) NOT NULL DEFAULT '0.000',
  "purchase_mode" varchar(255) NOT NULL DEFAULT 'PLATFORM',
  "substitution_confirmed" smallint NOT NULL DEFAULT '0',
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_shopping_list_item_idx_list" ON "fa_shop_shopping_list_item" ("shopping_list_id");
CREATE INDEX IF NOT EXISTS "fa_shop_shopping_list_item_idx_ingredient" ON "fa_shop_shopping_list_item" ("ingredient_id");

CREATE TABLE IF NOT EXISTS "fa_shop_order_ext" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" int NOT NULL,
  "order_sn" varchar(50) NOT NULL,
  "user_id" int NOT NULL,
  "idempotency_key" varchar(100) NOT NULL,
  "shopping_list_id" bigint NOT NULL DEFAULT '0',
  "shopping_list_version" int NOT NULL DEFAULT '0',
  "biz_status" varchar(40) NOT NULL DEFAULT 'PENDING_PAYMENT',
  "fulfillment_status" varchar(40) NOT NULL DEFAULT 'PENDING',
  "refund_status" varchar(40) NOT NULL DEFAULT 'NONE',
  "trace_id" varchar(64) NOT NULL DEFAULT '',
  "version" int NOT NULL DEFAULT '0',
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_order_ext_uk_order_id" UNIQUE ("order_id"),
  CONSTRAINT "fa_shop_order_ext_uk_order_sn" UNIQUE ("order_sn"),
  CONSTRAINT "fa_shop_order_ext_uk_user_idempotency" UNIQUE ("user_id", "idempotency_key")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_ext_idx_user_status" ON "fa_shop_order_ext" ("user_id", "biz_status");

CREATE TABLE IF NOT EXISTS "fa_shop_order_supplier" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_order_sn" varchar(64) NOT NULL,
  "order_id" int NOT NULL,
  "order_sn" varchar(50) NOT NULL,
  "supplier_id" int NOT NULL,
  "warehouse_id" int NOT NULL,
  "fulfillment_mode" varchar(255) NOT NULL,
  "goods_amount" numeric(12,2) NOT NULL DEFAULT '0.00',
  "shipping_fee" numeric(12,2) NOT NULL DEFAULT '0.00',
  "supply_amount" numeric(12,2) NOT NULL DEFAULT '0.00',
  "status" varchar(40) NOT NULL DEFAULT 'PENDING_ASSIGN',
  "accepted_at" bigint DEFAULT NULL,
  "preparing_at" bigint DEFAULT NULL,
  "shipping_at" bigint DEFAULT NULL,
  "completed_at" bigint DEFAULT NULL,
  "cancelled_at" bigint DEFAULT NULL,
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_order_supplier_uk_supplier_order_sn" UNIQUE ("supplier_order_sn"),
  CONSTRAINT "fa_shop_order_supplier_uk_order_supplier_warehouse" UNIQUE ("order_id", "supplier_id", "warehouse_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_supplier_idx_supplier_status" ON "fa_shop_order_supplier" ("supplier_id", "status");
CREATE INDEX IF NOT EXISTS "fa_shop_order_supplier_idx_order_sn" ON "fa_shop_order_supplier" ("order_sn");

CREATE TABLE IF NOT EXISTS "fa_shop_order_goods_ext" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_goods_id" int NOT NULL,
  "supplier_order_id" bigint NOT NULL,
  "supplier_id" int NOT NULL,
  "supplier_sku_id" int NOT NULL,
  "warehouse_id" int NOT NULL,
  "shopping_list_item_id" bigint NOT NULL DEFAULT '0',
  "ingredient_id" int NOT NULL DEFAULT '0',
  "supply_price" numeric(12,2) NOT NULL DEFAULT '0.00',
  "goods_snapshot_json" json NOT NULL,
  "delivery_snapshot_json" json DEFAULT NULL,
  "shipped_quantity" int NOT NULL DEFAULT '0',
  "refunded_quantity" int NOT NULL DEFAULT '0',
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_order_goods_ext_uk_order_goods" UNIQUE ("order_goods_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_goods_ext_idx_supplier_order" ON "fa_shop_order_goods_ext" ("supplier_order_id");
CREATE INDEX IF NOT EXISTS "fa_shop_order_goods_ext_idx_supplier" ON "fa_shop_order_goods_ext" ("supplier_id");

CREATE TABLE IF NOT EXISTS "fa_shop_order_snapshot" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" int NOT NULL,
  "order_sn" varchar(50) NOT NULL,
  "snapshot_type" varchar(255) NOT NULL,
  "snapshot_json" json NOT NULL,
  "createtime" bigint NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_snapshot_idx_order_type" ON "fa_shop_order_snapshot" ("order_id", "snapshot_type");
CREATE INDEX IF NOT EXISTS "fa_shop_order_snapshot_idx_order_sn" ON "fa_shop_order_snapshot" ("order_sn");

CREATE TABLE IF NOT EXISTS "fa_shop_order_status_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" int NOT NULL,
  "order_sn" varchar(50) NOT NULL,
  "supplier_order_id" bigint NOT NULL DEFAULT '0',
  "status_type" varchar(255) NOT NULL,
  "from_status" varchar(40) NOT NULL DEFAULT '',
  "to_status" varchar(40) NOT NULL,
  "biz_no" varchar(100) NOT NULL DEFAULT '',
  "operator_type" varchar(30) NOT NULL DEFAULT 'SYSTEM',
  "operator_id" int NOT NULL DEFAULT '0',
  "remark" varchar(500) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_status_log_idx_order_time" ON "fa_shop_order_status_log" ("order_id", "createtime");
CREATE INDEX IF NOT EXISTS "fa_shop_order_status_log_idx_supplier_order" ON "fa_shop_order_status_log" ("supplier_order_id");

CREATE TABLE IF NOT EXISTS "fa_shop_order_shipment" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "shipment_sn" varchar(64) NOT NULL,
  "supplier_order_id" bigint NOT NULL,
  "order_id" int NOT NULL,
  "order_sn" varchar(50) NOT NULL,
  "shipper_code" varchar(50) NOT NULL DEFAULT '',
  "shipper_name" varchar(100) NOT NULL DEFAULT '',
  "logistic_code" varchar(100) NOT NULL DEFAULT '',
  "status" varchar(255) NOT NULL DEFAULT 'PENDING',
  "shipping_at" bigint DEFAULT NULL,
  "received_at" bigint DEFAULT NULL,
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_order_shipment_uk_shipment_sn" UNIQUE ("shipment_sn")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_shipment_idx_supplier_order" ON "fa_shop_order_shipment" ("supplier_order_id");
CREATE INDEX IF NOT EXISTS "fa_shop_order_shipment_idx_logistic_code" ON "fa_shop_order_shipment" ("logistic_code");

CREATE TABLE IF NOT EXISTS "fa_shop_order_shipment_item" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "shipment_id" bigint NOT NULL,
  "order_goods_id" int NOT NULL,
  "quantity" int NOT NULL,
  "createtime" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_order_shipment_item_uk_shipment_goods" UNIQUE ("shipment_id", "order_goods_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_shipment_item_idx_order_goods" ON "fa_shop_order_shipment_item" ("order_goods_id");

CREATE TABLE IF NOT EXISTS "fa_shop_payment_transaction" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "payment_sn" varchar(64) NOT NULL,
  "order_id" int NOT NULL,
  "order_sn" varchar(50) NOT NULL,
  "channel" varchar(30) NOT NULL,
  "channel_transaction_id" varchar(100) NOT NULL DEFAULT '',
  "amount" numeric(12,2) NOT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'CREATED',
  "request_json" json DEFAULT NULL,
  "callback_json" json DEFAULT NULL,
  "paid_at" bigint DEFAULT NULL,
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_payment_transaction_uk_payment_sn" UNIQUE ("payment_sn"),
  CONSTRAINT "fa_shop_payment_transaction_uk_channel_transaction" UNIQUE ("channel", "channel_transaction_id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_payment_transaction_idx_order_status" ON "fa_shop_payment_transaction" ("order_id", "status");

CREATE TABLE IF NOT EXISTS "fa_shop_aftersales_ext" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "aftersales_id" int NOT NULL,
  "supplier_order_id" bigint NOT NULL,
  "supplier_id" int NOT NULL,
  "warehouse_id" int NOT NULL,
  "return_status" varchar(255) NOT NULL DEFAULT 'NONE',
  "restock_quantity" int NOT NULL DEFAULT '0',
  "idempotency_key" varchar(100) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_aftersales_ext_uk_aftersales" UNIQUE ("aftersales_id"),
  CONSTRAINT "fa_shop_aftersales_ext_uk_supplier_idempotency" UNIQUE ("supplier_id", "idempotency_key")
);


CREATE TABLE IF NOT EXISTS "fa_shop_order_substitution" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" int NOT NULL,
  "order_goods_id" int NOT NULL,
  "from_supplier_id" int NOT NULL,
  "from_goods_id" int NOT NULL,
  "from_goods_sku_id" int NOT NULL DEFAULT '0',
  "to_supplier_id" int NOT NULL DEFAULT '0',
  "to_goods_id" int NOT NULL,
  "to_goods_sku_id" int NOT NULL DEFAULT '0',
  "constraint_result_json" json DEFAULT NULL,
  "price_difference" numeric(12,2) NOT NULL DEFAULT '0.00',
  "status" varchar(255) NOT NULL DEFAULT 'PENDING_CONFIRM',
  "confirmed_at" bigint DEFAULT NULL,
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "fa_shop_order_substitution_idx_order_status" ON "fa_shop_order_substitution" ("order_id", "status");
CREATE INDEX IF NOT EXISTS "fa_shop_order_substitution_idx_order_goods" ON "fa_shop_order_substitution" ("order_goods_id");

