CREATE TABLE IF NOT EXISTS "fa_shop_supplier_sync_job" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "job_sn" varchar(64) NOT NULL,
  "supplier_id" int NOT NULL,
  "sync_type" varchar(255) NOT NULL,
  "direction" varchar(255) NOT NULL DEFAULT 'INBOUND',
  "biz_key" varchar(150) NOT NULL,
  "payload_json" json NOT NULL,
  "response_json" json DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'PENDING',
  "attempts" int NOT NULL DEFAULT '0',
  "max_attempts" int NOT NULL DEFAULT '5',
  "next_retry_at" bigint DEFAULT NULL,
  "last_error" varchar(1000) NOT NULL DEFAULT '',
  "completed_at" bigint DEFAULT NULL,
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_supplier_sync_job_uk_job_sn" UNIQUE ("job_sn"),
  CONSTRAINT "fa_shop_supplier_sync_job_uk_supplier_type_biz" UNIQUE ("supplier_id", "sync_type", "biz_key")
);
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_sync_job_idx_status_retry" ON "fa_shop_supplier_sync_job" ("status", "next_retry_at");
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_sync_job_idx_supplier_time" ON "fa_shop_supplier_sync_job" ("supplier_id", "createtime");

