CREATE TABLE IF NOT EXISTS "fa_shop_supplier_reconciliation" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reconciliation_sn" varchar(64) NOT NULL,
  "supplier_id" int NOT NULL,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  "order_count" int NOT NULL DEFAULT '0',
  "goods_amount" numeric(14,2) NOT NULL DEFAULT '0.00',
  "supply_amount" numeric(14,2) NOT NULL DEFAULT '0.00',
  "refund_amount" numeric(14,2) NOT NULL DEFAULT '0.00',
  "payable_amount" numeric(14,2) NOT NULL DEFAULT '0.00',
  "status" varchar(255) NOT NULL DEFAULT 'DRAFT',
  "confirmed_at" bigint DEFAULT NULL,
  "paid_at" bigint DEFAULT NULL,
  "admin_id" int NOT NULL DEFAULT '0',
  "remark" varchar(500) NOT NULL DEFAULT '',
  "createtime" bigint NOT NULL,
  "updatetime" bigint DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fa_shop_supplier_reconciliation_uk_reconciliation_sn" UNIQUE ("reconciliation_sn"),
  CONSTRAINT "fa_shop_supplier_reconciliation_uk_supplier_period" UNIQUE ("supplier_id", "period_start", "period_end")
);
CREATE INDEX IF NOT EXISTS "fa_shop_supplier_reconciliation_idx_status_period" ON "fa_shop_supplier_reconciliation" ("status", "period_end");

