<script setup>
import AppNavBar from '../../components/AppNavBar.vue'
import { ref,computed } from 'vue'
import { onLoad,onShow,onShareAppMessage } from '@dcloudio/uni-app'
import MemberFields from '../../components/MemberFields.vue'
import { backHome,getProfile,getRecords,saveProfile } from '../../utils/profile.js'
import { dataWarnings,restrictionSummary,memberNotes,diseaseSummary } from '../../utils/health.js'
import { createInvite,shareInvite } from '../../utils/invitations.js'
import { localDate } from '../../utils/meal-state.js'
import { confirmedFor,recordsOn } from '../../utils/feedback.js'
const profile=ref(getProfile()),id=ref(''),editing=ref(false),draft=ref(null),records=ref([])
const member=computed(()=>profile.value.members.find(m=>String(m.id)===id.value)||profile.value.members[0])
const canInvite=computed(()=>!member.value.claimedBy && (!profile.value.viewerAccount||profile.value.viewerAccount==='creator'))
const canEdit=computed(()=>member.value.claimedBy?member.value.claimedBy===(profile.value.viewerAccount||'creator'):(!profile.value.viewerAccount||profile.value.viewerAccount==='creator'))
const todayRecords=computed(()=>recordsOn(confirmedFor(records.value,member.value.id),localDate()))
onLoad(o=>{id.value=o.id||'';if(o.edit==='1')edit()})
onShow(()=>{profile.value=getProfile();records.value=getRecords();if(draft.value){const fresh=profile.value.members.find(m=>m.id===draft.value.id);if(fresh){draft.value.reports=fresh.reports;draft.value.reportStatus=fresh.reportStatus}}})
onShareAppMessage(()=>canInvite.value?shareInvite(createInvite(member.value.id)):{title:'家庭营养师',path:'/pages/index/index'})
function edit(){if(!canEdit.value)return;draft.value=JSON.parse(JSON.stringify(member.value));editing.value=true}
function commit(){if(!canEdit.value)return;if(!draft.value.name.trim())return uni.showToast({title:'请填写姓名／称呼',icon:'none'});if(draft.value.healthStatus==='set'&&(!draft.value.conditions.length||draft.value.conditions.includes('其他')&&!draft.value.otherCondition.trim()))return uni.showToast({title:'请补充具体基础病',icon:'none'});const index=profile.value.members.findIndex(m=>m.id===member.value.id);profile.value.members[index]=draft.value;saveProfile(profile.value);editing.value=false}
function save(){const warnings=dataWarnings(draft.value);if(!warnings.length)return commit();uni.showModal({title:'请复核档案信息',content:warnings.join('；')+'。此提示不是诊断，不解除饮食安全限制。',cancelText:'返回修改',confirmText:'继续保存',success:r=>{if(r.confirm)commit()}})}
function share(){if(!canInvite.value)return;const token=createInvite(member.value.id);uni.navigateTo({url:'/pages/invite/index?token='+token})}
function menu(){uni.showActionSheet({itemList:canInvite.value?['转发成员邀请卡片（模拟）']:['该档案已认领，无法重复邀请'],success:()=>{if(canInvite.value)share()}})}
</script>
<template><view class="screen member-detail"><AppNavBar><view class="nav-row"><button class="icon-button" @click="editing?editing=false:backHome()">‹</button><text class="nav-title">{{member.name}}的健康档案</text><button class="edit" :disabled="!canEdit" @click="editing?save():edit()">{{!canEdit?'只读':editing?'保存':'编辑'}}</button><button class="icon-button" aria-label="成员分享菜单" @click="menu">···</button></view></AppNavBar><view class="identity card"><view class="avatar" :style="{background:member.color}">{{member.name.slice(0,1)}}</view><view><text>{{member.name}}</text><text>{{member.birthDate?member.age+' 岁':'年龄未填写'}} · {{member.gender}} · {{member.relation}}</text></view></view><template v-if="editing"><MemberFields :member="draft"/><button class="primary-button" @click="save">保存档案</button><button class="secondary-button" @click="editing=false">取消修改</button></template><template v-else><button v-if="canInvite" class="secondary-button" @click="share">邀请本人加入</button><view class="main-card card"><text class="section-title">基础资料</text><text class="subheading">成员信息</text><text>身高 {{member.height||'未填写'}} cm · 体重 {{member.weight||'未填写'}} kg</text><text>出生日期 {{member.birthDate||'未填写'}} · 关系 {{member.relation}}</text><text class="subheading">偏好与目标</text><text>饮食目标：{{member.goals.join('、')||'未填写'}}</text><text>口味：{{member.tastePreferences.join('、')||'未填写'}}</text><text>菜系：{{member.cuisines.join('、')||'未填写'}}</text><text class="subheading">饮食限制、医生要求与报告</text><MemberFields :member="member" :read-only="!canEdit" :sections="['restrictions','reports']" @saved="saveProfile(profile)"/></view><view class="main-card card"><text class="section-title">基础病情况</text><text>{{member.healthStatus==='set'?member.conditions.map(c=>c==='其他'?member.otherCondition||'其他':c).join(' · '):member.healthStatus==='none'?'没有已知基础病':'暂不填写'}}</text><text v-if="member.healthStatus==='set'" class="self-reported">用户自述</text><text>{{diseaseSummary(member)}}</text></view><view class="main-card card"><text class="section-title">每日饮食</text><text class="helper">今日实际保存的饮食记录，不是计划菜单。</text><view v-for="r in todayRecords" :key="r.id" class="record"><text>{{r.meal}} · {{r.displayTime||r.time||''}}</text><text>{{r.dishes?.join('、')||r.recognizedDishes?.join('、')||r.description||'已保存饮食记录'}}</text></view><text v-if="!todayRecords.length">今天尚未保存饮食记录，不代表没有用餐。</text></view></template></view></template>
<style scoped>.member-detail{padding-bottom:50rpx}.edit{color:#246b50;font-size:23rpx;font-weight:800}.identity{display:flex;align-items:center;gap:20rpx;padding:28rpx;margin:32rpx 0}.avatar{width:92rpx;height:92rpx;display:flex;align-items:center;justify-content:center;border-radius:28rpx;font-size:34rpx;font-weight:800}.identity>view:last-child{display:flex;flex-direction:column;gap:12rpx}.identity>view:last-child>text:first-child{font-size:32rpx;font-weight:800}.identity>view:last-child>text:last-child{font-size:22rpx;color:#6d7b70}.main-card{padding:28rpx;margin:22rpx 0;display:flex;flex-direction:column;gap:16rpx;font-size:23rpx;line-height:1.7}.subheading{margin-top:12rpx;color:#246b50;font-size:23rpx;font-weight:800}.self-reported{align-self:flex-start;padding:4rpx 14rpx;border-radius:12rpx;background:#edf1e6;font-size:20rpx}.helper{color:#7b857a}.record{display:flex;flex-direction:column;border-top:1rpx solid #e0e5db;padding-top:16rpx}.secondary-button{margin-top:14rpx}</style>
