<script setup>
import AppNavBar from '../../components/AppNavBar.vue'
import { ref } from 'vue'
import { backHome } from '../../utils/profile.js'
const form=ref({type:'供应商',company:'',category:'',name:'',phone:'',region:'',note:''})
function submit(){if(!form.value.company||(form.value.type==='供应商'&&!form.value.category)||!form.value.name||!/^1\d{10}$/.test(form.value.phone)||!form.value.region)return uni.showToast({title:'请完整填写必填项和手机号',icon:'none'});uni.showModal({title:'测试提交未发送',content:'当前离线原型没有后台接收回执，因此不显示“已收到”的虚假成功状态。表单内容已保留，可在接入服务后重试。',showCancel:false})}
</script>
<template><view class="screen"><AppNavBar><view class="nav-row"><button class="icon-button" @click="backHome">‹</button><text class="nav-title">合作商合作</text><text class="pill">申请</text></view></AppNavBar><view class="hero"><text class="eyebrow">PARTNER WITH US</text><text class="display-title">让好食材，<br/>更靠近家庭餐桌。</text></view><view v-if="form.type==='供应商'" class="requirements card"><text class="section-title">合作要求</text><view v-for="(item,i) in ['食材来源真实，品质和新鲜度可核验','提供必要资质与溯源资料','按约定保障储运、供货稳定与售后配合']" :key="item"><text>{{i+1}}</text><text>{{item}}</text></view><text class="review-note">具体准入标准由供应链负责人审核。</text></view><view class="form card"><text class="section-title">留下合作信息</text><text class="label">合作方类型 *</text><view class="partner-types"><button v-for="type in ['供应商','渠道商','经销商']" :key="type" :class="{active:form.type===type}" @click="form.type=type">{{type}}</button></view><text class="label">公司名称 *</text><input v-model="form.company" class="field-input" placeholder="请填写公司全称"/><template v-if="form.type==='供应商'"><text class="label">供应食材类别 *</text><input v-model="form.category" class="field-input" placeholder="例如：时令蔬菜、净菜"/></template><text class="label">联系人姓名 *</text><input v-model="form.name" class="field-input"/><text class="label">联系电话 *</text><input v-model="form.phone" type="number" class="field-input" placeholder="11位手机号"/><text class="label">{{form.type==='供应商'?'供货地区':'合作地区'}} *</text><input v-model="form.region" class="field-input" placeholder="省／市／区"/><text v-if="form.type!=='供应商'" class="safe-note">渠道商／经销商的专属业务字段待团队确定，首期仅收集基本合作信息。</text><text class="label">补充说明</text><textarea v-model="form.note" class="text-area" placeholder="可选：供货能力、资质或合作期待"/><button class="primary-button" @click="submit">提交申请</button><text class="safe-note">合作申请与消费者订单、家庭健康数据完全独立。</text></view></view></template>
<style scoped>
.partner-types{display:flex;gap:12rpx;margin:16rpx 0}.partner-types button{padding:16rpx;background:#eef2e7;border-radius:18rpx;font-size:23rpx}.partner-types .active{background:#246b50;color:white}.hero{margin:45rpx 0 28rpx}.hero .display-title{display:block;margin-top:10rpx;font-size:49rpx}.requirements,.form{padding:27rpx}.requirements>view{display:grid;grid-template-columns:44rpx 1fr;gap:12rpx;align-items:start;margin-top:18rpx}.requirements>view>text:first-child{width:40rpx;height:40rpx;display:flex;align-items:center;justify-content:center;border-radius:14rpx;background:#246b50;color:#fff;font-size:18rpx;font-weight:900}.requirements>view>text:last-child{font-size:20rpx;line-height:1.55}.review-note{display:block;margin-top:20rpx;padding:15rpx;border-radius:15rpx;background:#edf2e5;color:#51695f;font-size:18rpx}.form{margin-top:20rpx}.form .section-title{display:block;margin-bottom:20rpx}.form .label{display:block;margin-top:13rpx}.field-input{margin-top:8rpx}.text-area{width:100%;height:130rpx;margin-top:8rpx;padding:17rpx;border:1rpx solid #dce2d8;border-radius:16rpx;background:#ffffff;font-size:21rpx}.form .primary-button{margin-top:22rpx}.safe-note{display:block;margin-top:15rpx;text-align:center}</style>
