<script setup>
import { ref } from 'vue'
import { diseaseOptions, diseaseSummary, preferenceGroups, restrictionFields, restrictionSummary } from '../utils/health.js'
import { getProfile,saveProfile } from '../utils/profile.js'
const emit=defineEmits(['saved'])
const props=defineProps({member:Object,readOnly:{type:Boolean,default:false},sections:{type:Array,default:()=>['basic','disease','preferences','restrictions','reports']}})
const editor=ref(''),draft=ref(null),custom=ref({})
const states=[{v:'unknown',t:'暂不填写'},{v:'none',t:'确认没有'},{v:'set',t:'有／选择内容'}]
function toggle(list,value){const i=list.indexOf(value);i<0?list.push(value):list.splice(i,1)}
function add(field){const value=custom.value[field]?.trim();if(!value)return;if(!props.member[field].includes(value))props.member[field].push(value);custom.value[field]=''}
function open(type){if(type==='report'){if(!props.readOnly){const p=getProfile();const member=p.members.find(m=>m.id===props.member.id);if(member)Object.assign(member,props.member);else p.members.push({...props.member});saveProfile(p)}uni.navigateTo({url:'/pages/reports/index?member='+props.member.id});return}if(props.readOnly)return uni.showToast({title:'此档案由本人维护',icon:'none'});editor.value=type;draft.value=JSON.parse(JSON.stringify(props.member))}
function save(){const cfg=restrictionFields[editor.value];if(cfg&&draft.value[cfg.status]==='set'&&!draft.value[cfg.field].length)return uni.showToast({title:'请选择或补充具体内容',icon:'none'});Object.assign(props.member,draft.value);editor.value='';emit('saved')}
function addRestriction(){const cfg=restrictionFields[editor.value],value=custom.value.restriction?.trim();if(value&&!draft.value[cfg.field].includes(value))draft.value[cfg.field].push(value);custom.value.restriction=''}
function report(source){draft.value.reportStatus='review';draft.value.reports=[{id:Date.now(),name:source+' · 演示报告',status:'待核对'}]}
</script>
<template>
  <view v-if="sections.includes('basic')" class="field-card card"><text class="section-title">成员信息</text><text class="label">姓名／称呼</text><input v-model="member.name" class="field-input"/><view class="two-col"><view><text class="label">性别</text><picker :range="['女','男','未填写']" @change="member.gender=['女','男','未填写'][$event.detail.value]"><view class="field-input picker">{{member.gender}}</view></picker></view><view><text class="label">与我的关系</text><input v-model="member.relation" class="field-input"/></view></view><text class="label">出生日期</text><picker mode="date" :value="member.birthDate" @change="member.birthDate=$event.detail.value;member.age=new Date().getFullYear()-Number(member.birthDate.slice(0,4))"><view class="field-input picker">{{member.birthDate||'选择出生日期'}}</view></picker><view class="two-col"><view><text class="label">身高 cm（可后补）</text><input v-model="member.height" class="field-input" type="digit"/></view><view><text class="label">体重 kg（可后补）</text><input v-model="member.weight" class="field-input" type="digit"/></view></view><text class="helper">使用默认头像；离线原型不上传真实身份资料。</text></view>
  <view v-if="sections.includes('disease')" class="field-card card"><text class="section-title">基础病情况</text><text class="label">是否有已知基础病？</text><view class="chips"><button v-for="s in [{v:'unknown',t:'暂不填写'},{v:'none',t:'没有已知基础病'},{v:'set',t:'有基础病'}]" :key="s.v" :class="{active:member.healthStatus===s.v}" @click="member.healthStatus=s.v;member.health=s.v==='none'?'一般成人':s.v==='unknown'?'未填写':'用户自述'">{{s.t}}</button></view><view v-if="member.healthStatus==='set'" class="chips"><button v-for="c in diseaseOptions" :key="c" :class="{active:member.conditions.includes(c)}" @click="toggle(member.conditions,c)">{{c}}</button></view><input v-if="member.healthStatus==='set'&&member.conditions.includes('其他')" v-model="member.otherCondition" class="field-input" placeholder="请手动填写具体基础病"/><text class="helper">基础病信息：用户自述，不是平台确诊。</text><view class="management"><text class="label">系统饮食管理摘要 · 只读演示</text><text>{{diseaseSummary(member)}}</text></view></view>
  <template v-if="sections.includes('preferences')"><view v-for="(group,key) in preferenceGroups" :key="key" class="field-card card"><text class="section-title">{{group.title}}</text><view class="chips"><button v-for="item in group.items" :key="item" :class="{active:member[key].includes(item)}" @click="toggle(member[key],item)">{{item}}</button></view><view class="custom-row"><input v-model="custom[key]" class="field-input" :placeholder="'补充'+group.title"/><button @click="add(key)">添加</button></view></view><text class="helper">饮食目标不代表基础病诊断，例如“控糖”不等于糖尿病。</text></template>
  <view v-if="sections.includes('restrictions')" class="field-card card"><button v-for="(cfg,type) in restrictionFields" :key="type" class="field-row" @click="open(type)"><view><text>{{cfg.title}}</text><text>{{restrictionSummary(member,type)}}</text></view><text>›</text></button><button class="field-row" @click="open('doctor')"><view><text>医生饮食要求</text><text>{{member.doctorStatus==='none'?'没有饮食要求':member.doctorStatus==='set'?member.clinicianGuidance||'请补充':'未填写'}}</text></view><text>›</text></button></view>
  <view v-if="sections.includes('reports')" class="field-card card"><button class="field-row" @click="open('report')"><view><text>体检报告</text><text>{{member.reportStatus==='review'?'待核对':member.reportStatus==='done'?'已核对':'尚未上传'}}</text></view><text>›</text></button><text class="helper">报告关联 {{member.name}}，识别结果需要核对后保存。</text></view>
  <view v-if="editor" class="sheet-mask" @click.self="editor=''"><view class="sheet member-sheet"><view class="sheet-head"><view><text class="eyebrow">{{member.name}}</text><text class="section-title">{{restrictionFields[editor]?.title || (editor==='doctor'?'医生饮食要求':'体检报告')}}</text></view><button @click="editor=''">×</button></view><template v-if="restrictionFields[editor]"><view class="chips"><button v-for="s in states" :key="s.v" :class="{active:draft[restrictionFields[editor].status]===s.v}" @click="draft[restrictionFields[editor].status]=s.v">{{s.t}}</button></view><template v-if="draft[restrictionFields[editor].status]==='set'"><view class="chips"><button v-for="item in restrictionFields[editor].items.filter(i=>i!=='自定义')" :key="item" :class="{active:draft[restrictionFields[editor].field].includes(item)}" @click="toggle(draft[restrictionFields[editor].field],item)">{{item}}</button></view><view class="chips"><text v-for="v in draft[restrictionFields[editor].field]" :key="v">{{v}}</text></view><view class="custom-row"><input v-model="custom.restriction" class="field-input" placeholder="其他具体食物／成分"/><button @click="addRestriction">添加</button></view></template></template><template v-else-if="editor==='doctor'"><view class="chips"><button v-for="s in states" :key="s.v" :class="{active:draft.doctorStatus===s.v}" @click="draft.doctorStatus=s.v">{{s.t}}</button></view><textarea v-if="draft.doctorStatus==='set'" v-model="draft.clinicianGuidance" class="text-area" placeholder="填写医生交代的饮食要求"/></template><template v-else><text class="helper">离线原型仅演示上传和核对，不读取真实报告。</text><view class="chips"><button v-for="source in ['拍照上传','微信聊天文件','设备文件']" :key="source" @click="report(source)">{{source}}</button></view><view v-for="r in draft.reports||[]" :key="r.id"><text>{{r.name}} · {{draft.reportStatus==='done'?'已核对':'待核对'}}</text></view><button v-if="draft.reportStatus==='review'" class="secondary-button" @click="draft.reportStatus='done'">核对并确认示例报告</button></template><view class="two-col actions"><button class="secondary-button" @click="editor=''">取消</button><button class="primary-button" @click="save">保存</button></view></view></view>
</template>
<style scoped>.field-card{padding:24rpx;margin-bottom:18rpx}.chips{display:flex;flex-wrap:wrap;gap:10rpx;margin:18rpx 0}.chips button{padding:12rpx 18rpx;background:#eff1e7;border-radius:16rpx;color:#597063;font-size:21rpx}.chips button.active{background:#eaf2ed;color:#246b50;font-weight:800}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:14rpx}.custom-row{display:grid;grid-template-columns:1fr 90rpx;gap:12rpx;align-items:center}.custom-row button{color:#246b50;font-size:23rpx}.helper{display:block;color:#6b7a72;font-size:20rpx;line-height:1.65;margin:16rpx 0}.management{background:#f0f3f1;border-radius:20rpx;padding:18rpx;font-size:22rpx;line-height:1.7}.field-row{width:100%;padding:18rpx 0;display:flex;justify-content:space-between;align-items:center;text-align:left;border-bottom:1rpx solid #e0e5dc}.field-row>view{display:flex;flex-direction:column;gap:8rpx}.field-row>view>text:first-child{font-size:25rpx;font-weight:800}.field-row>view>text:last-child{font-size:20rpx;color:#6b7a72}.field-row>text{font-size:30rpx}.member-sheet{max-height:70vh;overflow:auto}.sheet-head{display:flex;justify-content:space-between;align-items:center}.sheet-head>view{display:flex;flex-direction:column;gap:8rpx}.sheet-head>button{font-size:40rpx}.text-area{width:100%;height:160rpx;padding:20rpx;background:#eef2e8;border-radius:20rpx;font-size:23rpx}.actions{margin-top:24rpx}.picker{display:flex;align-items:center}</style>
