-- Family Nutrition Commerce V5 schema.
-- This file is executed by addons\shop\library\v5\Migrator after replacing __PREFIX__.
-- Existing shop tables are extended idempotently in Migrator.php.

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_schema_migration` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `version` varchar(40) NOT NULL,
  `description` varchar(255) NOT NULL DEFAULT '',
  `checksum` char(64) NOT NULL DEFAULT '',
  `executed_at` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_schema_version` (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商城数据库迁移记录';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_ingredient` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ingredient_code` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `category_code` varchar(50) NOT NULL DEFAULT '',
  `default_unit` varchar(20) NOT NULL DEFAULT '',
  `description` varchar(500) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  `deletetime` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ingredient_code` (`ingredient_code`),
  KEY `idx_ingredient_name` (`name`),
  KEY `idx_ingredient_category` (`category_code`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='标准食材';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_ingredient_alias` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ingredient_id` bigint unsigned NOT NULL,
  `alias` varchar(100) NOT NULL,
  `source` varchar(30) NOT NULL DEFAULT 'manual',
  `language` varchar(10) NOT NULL DEFAULT 'zh-CN',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ingredient_alias` (`ingredient_id`,`alias`,`language`),
  KEY `idx_alias` (`alias`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='食材别名';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_ingredient_sku_map` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ingredient_id` bigint unsigned NOT NULL,
  `goods_id` bigint unsigned NOT NULL DEFAULT 0,
  `sku_id` bigint unsigned NOT NULL,
  `role` varchar(20) NOT NULL DEFAULT 'primary',
  `net_value` decimal(14,3) NOT NULL DEFAULT 0,
  `net_unit` varchar(20) NOT NULL DEFAULT '',
  `convert_ratio` decimal(14,6) NOT NULL DEFAULT 1,
  `loss_rate` decimal(8,6) NOT NULL DEFAULT 0,
  `priority` int NOT NULL DEFAULT 0,
  `valid_from` bigint unsigned NOT NULL DEFAULT 0,
  `valid_to` bigint unsigned NOT NULL DEFAULT 0,
  `review_status` varchar(20) NOT NULL DEFAULT 'pending',
  `reviewer_id` bigint unsigned NOT NULL DEFAULT 0,
  `reviewed_at` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ingredient_sku` (`ingredient_id`,`sku_id`,`role`),
  KEY `idx_map_sku` (`sku_id`,`status`),
  KEY `idx_map_candidate` (`ingredient_id`,`status`,`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='食材SKU映射';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_sku_ingredient_component` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sku_id` bigint unsigned NOT NULL,
  `ingredient_id` bigint unsigned NOT NULL,
  `component_value` decimal(14,3) NOT NULL DEFAULT 0,
  `component_unit` varchar(20) NOT NULL DEFAULT '',
  `percentage` decimal(8,4) DEFAULT NULL,
  `is_main` tinyint unsigned NOT NULL DEFAULT 0,
  `allergen_flag` tinyint unsigned NOT NULL DEFAULT 0,
  `data_source` varchar(50) NOT NULL DEFAULT '',
  `data_version` varchar(50) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_component` (`sku_id`,`ingredient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SKU食材组成';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_sku_nutrition_fact` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sku_id` bigint unsigned NOT NULL,
  `basis_type` varchar(20) NOT NULL DEFAULT 'per_100g',
  `basis_value` decimal(14,3) NOT NULL DEFAULT 100,
  `basis_unit` varchar(20) NOT NULL DEFAULT 'g',
  `energy_kcal` decimal(14,3) DEFAULT NULL,
  `protein_g` decimal(14,3) DEFAULT NULL,
  `fat_g` decimal(14,3) DEFAULT NULL,
  `carbohydrate_g` decimal(14,3) DEFAULT NULL,
  `fiber_g` decimal(14,3) DEFAULT NULL,
  `sodium_mg` decimal(14,3) DEFAULT NULL,
  `extra_json` longtext,
  `source_name` varchar(100) NOT NULL DEFAULT '',
  `source_version` varchar(50) NOT NULL DEFAULT '',
  `review_status` varchar(20) NOT NULL DEFAULT 'pending',
  `reviewed_at` bigint unsigned NOT NULL DEFAULT 0,
  `valid_from` bigint unsigned NOT NULL DEFAULT 0,
  `valid_to` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_nutrition_sku` (`sku_id`,`status`,`valid_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SKU营养资料';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_bundle_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bundle_goods_id` bigint unsigned NOT NULL,
  `bundle_sku_id` bigint unsigned NOT NULL,
  `item_goods_id` bigint unsigned NOT NULL,
  `item_sku_id` bigint unsigned NOT NULL,
  `quantity` int unsigned NOT NULL DEFAULT 1,
  `sort` int NOT NULL DEFAULT 0,
  `item_snapshot_json` longtext,
  `version_no` int unsigned NOT NULL DEFAULT 1,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bundle_item` (`bundle_sku_id`,`version_no`,`item_sku_id`),
  KEY `idx_bundle_version` (`bundle_goods_id`,`version_no`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='固定食材包组成';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_recipe_bundle_map` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `recipe_ref` varchar(100) NOT NULL,
  `recipe_version_ref` varchar(100) NOT NULL DEFAULT '',
  `bundle_sku_id` bigint unsigned NOT NULL,
  `people_count` int unsigned NOT NULL DEFAULT 1,
  `meal_type` varchar(20) NOT NULL DEFAULT '',
  `priority` int NOT NULL DEFAULT 0,
  `valid_from` bigint unsigned NOT NULL DEFAULT 0,
  `valid_to` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_recipe_bundle` (`recipe_ref`,`recipe_version_ref`,`bundle_sku_id`,`people_count`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜品食材包映射';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_catalog_version` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `catalog_version` varchar(64) NOT NULL,
  `change_type` varchar(30) NOT NULL DEFAULT 'product',
  `resource_ref` varchar(100) NOT NULL DEFAULT '',
  `summary` varchar(500) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_catalog_version` (`catalog_version`),
  KEY `idx_catalog_created` (`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent目录版本';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_external_identity` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `client_id` varchar(64) NOT NULL,
  `external_user_ref` varchar(100) NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_external_identity` (`client_id`,`external_user_ref`),
  KEY `idx_external_identity_user` (`user_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外部用户与商城会员绑定';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_recommendation_package` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `package_sn` varchar(64) NOT NULL,
  `agent_client_id` varchar(64) NOT NULL,
  `agent_task_id` varchar(100) NOT NULL,
  `request_digest` char(64) NOT NULL DEFAULT '',
  `user_id` bigint unsigned NOT NULL DEFAULT 0,
  `user_ref` varchar(100) NOT NULL DEFAULT '',
  `family_ref` varchar(100) NOT NULL DEFAULT '',
  `current_version` int unsigned NOT NULL DEFAULT 1,
  `menu_version_ref` varchar(100) NOT NULL DEFAULT '',
  `catalog_version` varchar(64) NOT NULL DEFAULT '',
  `meal_date` date DEFAULT NULL,
  `nutrition_status` varchar(30) NOT NULL DEFAULT 'pending',
  `trade_status` varchar(30) NOT NULL DEFAULT 'pending',
  `confirm_status` varchar(30) NOT NULL DEFAULT 'unconfirmed',
  `confirmed_at` bigint unsigned NOT NULL DEFAULT 0,
  `expires_at` bigint unsigned NOT NULL DEFAULT 0,
  `total_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `currency` char(3) NOT NULL DEFAULT 'CNY',
  `last_issue_code` varchar(50) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'draft',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_package_sn` (`package_sn`),
  UNIQUE KEY `uk_agent_package_task` (`agent_client_id`,`agent_task_id`),
  KEY `idx_package_user` (`user_id`,`status`,`createtime`),
  KEY `idx_package_expire` (`status`,`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent动态推荐包';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_recommendation_package_version` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `package_id` bigint unsigned NOT NULL,
  `version_no` int unsigned NOT NULL,
  `base_version_no` int unsigned NOT NULL DEFAULT 0,
  `menu_version_ref` varchar(100) NOT NULL DEFAULT '',
  `catalog_version` varchar(64) NOT NULL DEFAULT '',
  `change_type` varchar(30) NOT NULL DEFAULT 'create',
  `nutrition_validation_id` varchar(100) NOT NULL DEFAULT '',
  `nutrition_rules_version` varchar(100) NOT NULL DEFAULT '',
  `nutrition_status` varchar(30) NOT NULL DEFAULT 'pending',
  `nutrition_summary` varchar(500) NOT NULL DEFAULT '',
  `validated_at` bigint unsigned NOT NULL DEFAULT 0,
  `trade_status` varchar(30) NOT NULL DEFAULT 'pending',
  `trade_checked_at` bigint unsigned NOT NULL DEFAULT 0,
  `recipes_snapshot_json` longtext,
  `requirements_snapshot_json` longtext,
  `issues_json` longtext,
  `total_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `created_by_type` varchar(30) NOT NULL DEFAULT 'agent',
  `created_by_ref` varchar(100) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_package_version` (`package_id`,`version_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='推荐包不可变版本';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_recommendation_package_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `package_version_id` bigint unsigned NOT NULL,
  `goods_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `ingredient_id` bigint unsigned NOT NULL DEFAULT 0,
  `quantity` int unsigned NOT NULL DEFAULT 1,
  `planned_value` decimal(14,3) NOT NULL DEFAULT 0,
  `planned_unit` varchar(20) NOT NULL DEFAULT '',
  `unit_price_cent` bigint unsigned NOT NULL DEFAULT 0,
  `line_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `product_snapshot_json` longtext,
  `sort` int NOT NULL DEFAULT 0,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_package_item_version` (`package_version_id`,`sort`),
  KEY `idx_package_item_sku` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='推荐包商品明细';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_recommendation_swap` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `swap_request_id` varchar(100) NOT NULL,
  `agent_task_id` varchar(100) NOT NULL,
  `package_id` bigint unsigned NOT NULL,
  `base_version_no` int unsigned NOT NULL,
  `result_version_no` int unsigned NOT NULL DEFAULT 0,
  `base_menu_version_ref` varchar(100) NOT NULL DEFAULT '',
  `result_menu_version_ref` varchar(100) NOT NULL DEFAULT '',
  `swap_type` varchar(30) NOT NULL DEFAULT 'recipe',
  `change_reason` varchar(500) NOT NULL DEFAULT '',
  `old_recipe_ref` varchar(100) NOT NULL DEFAULT '',
  `new_recipe_ref` varchar(100) NOT NULL DEFAULT '',
  `ingredient_changes_json` longtext,
  `nutrition_validation_id` varchar(100) NOT NULL DEFAULT '',
  `nutrition_status` varchar(30) NOT NULL DEFAULT 'pending',
  `trade_status` varchar(30) NOT NULL DEFAULT 'pending',
  `user_id` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'pending',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_swap_request` (`swap_request_id`),
  UNIQUE KEY `uk_swap_agent_task` (`agent_task_id`),
  KEY `idx_swap_package` (`package_id`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜品换一换记录';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_purchase_list` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `purchase_list_sn` varchar(64) NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `source_type` varchar(30) NOT NULL,
  `source_ref` varchar(64) NOT NULL,
  `source_version` int unsigned NOT NULL DEFAULT 1,
  `current_version` int unsigned NOT NULL DEFAULT 1,
  `address_id` bigint unsigned NOT NULL DEFAULT 0,
  `match_status` varchar(30) NOT NULL DEFAULT 'pending',
  `confirm_status` varchar(30) NOT NULL DEFAULT 'unconfirmed',
  `estimated_total_cent` bigint unsigned NOT NULL DEFAULT 0,
  `currency` char(3) NOT NULL DEFAULT 'CNY',
  `expires_at` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'draft',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_list_sn` (`purchase_list_sn`),
  UNIQUE KEY `uk_purchase_source` (`user_id`,`source_type`,`source_ref`,`source_version`),
  KEY `idx_purchase_user` (`user_id`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜单采购清单';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_purchase_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `purchase_list_id` bigint unsigned NOT NULL,
  `list_version_no` int unsigned NOT NULL DEFAULT 1,
  `recipe_ref` varchar(100) NOT NULL DEFAULT '',
  `ingredient_id` bigint unsigned NOT NULL,
  `required_value` decimal(14,3) NOT NULL DEFAULT 0,
  `required_unit` varchar(20) NOT NULL DEFAULT '',
  `pantry_value` decimal(14,3) NOT NULL DEFAULT 0,
  `pantry_unit` varchar(20) NOT NULL DEFAULT '',
  `net_required_value` decimal(14,3) NOT NULL DEFAULT 0,
  `net_required_unit` varchar(20) NOT NULL DEFAULT '',
  `is_optional` tinyint unsigned NOT NULL DEFAULT 0,
  `match_status` varchar(30) NOT NULL DEFAULT 'pending',
  `selected_match_id` bigint unsigned NOT NULL DEFAULT 0,
  `sort` int NOT NULL DEFAULT 0,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_purchase_item_list` (`purchase_list_id`,`list_version_no`,`sort`),
  KEY `idx_purchase_item_ingredient` (`ingredient_id`,`match_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购清单食材项';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_purchase_match` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `purchase_item_id` bigint unsigned NOT NULL,
  `list_version_no` int unsigned NOT NULL DEFAULT 1,
  `sku_id` bigint unsigned NOT NULL,
  `rank_no` int unsigned NOT NULL DEFAULT 1,
  `required_pack_count` int unsigned NOT NULL DEFAULT 1,
  `covered_value` decimal(14,3) NOT NULL DEFAULT 0,
  `covered_unit` varchar(20) NOT NULL DEFAULT '',
  `surplus_value` decimal(14,3) NOT NULL DEFAULT 0,
  `surplus_unit` varchar(20) NOT NULL DEFAULT '',
  `unit_price_cent` bigint unsigned NOT NULL DEFAULT 0,
  `total_price_cent` bigint unsigned NOT NULL DEFAULT 0,
  `match_score` decimal(8,4) NOT NULL DEFAULT 0,
  `match_reason_json` longtext,
  `trade_status` varchar(30) NOT NULL DEFAULT 'pending',
  `requires_agent_revalidation` tinyint unsigned NOT NULL DEFAULT 0,
  `is_selected` tinyint unsigned NOT NULL DEFAULT 0,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_purchase_match` (`purchase_item_id`,`list_version_no`,`sku_id`),
  KEY `idx_match_selected` (`purchase_item_id`,`list_version_no`,`is_selected`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购商品匹配';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_inventory_reservation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `reservation_sn` varchar(64) NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `source_type` varchar(30) NOT NULL,
  `source_ref` varchar(64) NOT NULL,
  `source_item_ref` varchar(64) NOT NULL DEFAULT '',
  `quantity` int unsigned NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `expires_at` bigint unsigned NOT NULL DEFAULT 0,
  `confirmed_at` bigint unsigned NOT NULL DEFAULT 0,
  `released_at` bigint unsigned NOT NULL DEFAULT 0,
  `release_reason` varchar(255) NOT NULL DEFAULT '',
  `request_id` varchar(64) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reservation_sn` (`reservation_sn`),
  UNIQUE KEY `uk_reservation_source` (`source_type`,`source_ref`,`source_item_ref`,`sku_id`),
  KEY `idx_reservation_expire` (`status`,`expires_at`),
  KEY `idx_reservation_sku` (`sku_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存占用';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_inventory_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sku_id` bigint unsigned NOT NULL,
  `change_type` varchar(30) NOT NULL,
  `quantity_delta` int NOT NULL DEFAULT 0,
  `stock_before` int NOT NULL DEFAULT 0,
  `stock_after` int NOT NULL DEFAULT 0,
  `reserved_before` int NOT NULL DEFAULT 0,
  `reserved_after` int NOT NULL DEFAULT 0,
  `source_type` varchar(30) NOT NULL DEFAULT '',
  `source_ref` varchar(64) NOT NULL DEFAULT '',
  `operator_type` varchar(30) NOT NULL DEFAULT 'system',
  `operator_id` bigint unsigned NOT NULL DEFAULT 0,
  `reason` varchar(500) NOT NULL DEFAULT '',
  `request_id` varchar(64) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_inventory_log_sku` (`sku_id`,`createtime`),
  KEY `idx_inventory_log_source` (`source_type`,`source_ref`),
  KEY `idx_inventory_log_request` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存不可变流水';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_checkout_session` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `checkout_token_hash` char(64) NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `source_type` varchar(30) NOT NULL,
  `source_ref` varchar(64) NOT NULL,
  `source_version` int unsigned NOT NULL DEFAULT 1,
  `address_id` bigint unsigned NOT NULL DEFAULT 0,
  `pricing_snapshot_json` longtext,
  `trade_issues_json` longtext,
  `total_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'active',
  `expires_at` bigint unsigned NOT NULL DEFAULT 0,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_checkout_token` (`checkout_token_hash`),
  KEY `idx_checkout_user` (`user_id`,`status`,`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一结算会话';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_order_ext` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL,
  `order_sn` varchar(64) NOT NULL,
  `source_type` varchar(30) NOT NULL DEFAULT 'legacy',
  `source_ref` varchar(64) NOT NULL DEFAULT '',
  `source_version` int unsigned NOT NULL DEFAULT 1,
  `checkout_token_hash` char(64) DEFAULT NULL,
  `business_status` varchar(30) NOT NULL DEFAULT 'created',
  `payment_status` varchar(30) NOT NULL DEFAULT 'created',
  `fulfillment_status` varchar(30) NOT NULL DEFAULT 'pending',
  `exception_status` varchar(30) NOT NULL DEFAULT 'normal',
  `address_snapshot_json` longtext,
  `pricing_snapshot_json` longtext,
  `request_id` varchar(64) NOT NULL DEFAULT '',
  `row_version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_ext_order` (`order_id`),
  UNIQUE KEY `uk_order_ext_sn` (`order_sn`),
  UNIQUE KEY `uk_order_ext_checkout` (`checkout_token_hash`),
  KEY `idx_order_ext_source` (`source_type`,`source_ref`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单V5扩展';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_order_goods_ext` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_goods_id` bigint unsigned NOT NULL,
  `order_id` bigint unsigned NOT NULL,
  `order_sn` varchar(64) NOT NULL,
  `package_version_id` bigint unsigned NOT NULL DEFAULT 0,
  `purchase_item_id` bigint unsigned NOT NULL DEFAULT 0,
  `plan_batch_id` bigint unsigned NOT NULL DEFAULT 0,
  `sku_snapshot_json` longtext,
  `ingredient_snapshot_json` longtext,
  `unit_price_cent` bigint unsigned NOT NULL DEFAULT 0,
  `line_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `discount_allocated_cent` bigint unsigned NOT NULL DEFAULT 0,
  `refunded_quantity` int unsigned NOT NULL DEFAULT 0,
  `refunded_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_goods_ext` (`order_goods_id`),
  KEY `idx_order_goods_ext_order` (`order_id`),
  KEY `idx_order_goods_ext_batch` (`plan_batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单商品V5扩展';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_payment_record` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `payment_sn` varchar(64) NOT NULL,
  `order_sn` varchar(64) NOT NULL,
  `channel` varchar(30) NOT NULL DEFAULT 'wechat',
  `channel_transaction_id` varchar(100) DEFAULT NULL,
  `appid` varchar(64) NOT NULL DEFAULT '',
  `mchid` varchar(64) NOT NULL DEFAULT '',
  `amount_cent` bigint unsigned NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'CNY',
  `status` varchar(30) NOT NULL DEFAULT 'created',
  `prepay_id` varchar(255) NOT NULL DEFAULT '',
  `paid_at` bigint unsigned NOT NULL DEFAULT 0,
  `closed_at` bigint unsigned NOT NULL DEFAULT 0,
  `notify_id` varchar(100) NOT NULL DEFAULT '',
  `notify_received_at` bigint unsigned NOT NULL DEFAULT 0,
  `last_query_at` bigint unsigned NOT NULL DEFAULT 0,
  `request_id` varchar(64) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_sn` (`payment_sn`),
  UNIQUE KEY `uk_payment_channel_tx` (`channel`,`channel_transaction_id`),
  KEY `idx_payment_order_status` (`order_sn`,`status`),
  KEY `idx_payment_status` (`status`,`updatetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付记录';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_refund_record` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `refund_sn` varchar(64) NOT NULL,
  `order_sn` varchar(64) NOT NULL,
  `payment_id` bigint unsigned NOT NULL DEFAULT 0,
  `aftersale_id` bigint unsigned NOT NULL DEFAULT 0,
  `plan_change_request_id` bigint unsigned NOT NULL DEFAULT 0,
  `channel_refund_id` varchar(100) DEFAULT NULL,
  `refund_amount_cent` bigint unsigned NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'CNY',
  `reason` varchar(500) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'created',
  `requested_at` bigint unsigned NOT NULL DEFAULT 0,
  `success_at` bigint unsigned NOT NULL DEFAULT 0,
  `notify_id` varchar(100) NOT NULL DEFAULT '',
  `last_query_at` bigint unsigned NOT NULL DEFAULT 0,
  `failure_code` varchar(50) NOT NULL DEFAULT '',
  `failure_message` varchar(500) NOT NULL DEFAULT '',
  `request_id` varchar(64) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_sn` (`refund_sn`),
  UNIQUE KEY `uk_channel_refund` (`channel_refund_id`),
  KEY `idx_refund_order` (`order_sn`,`status`),
  KEY `idx_refund_pending` (`status`,`updatetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退款记录';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_refund_allocation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `refund_id` bigint unsigned NOT NULL,
  `allocation_type` varchar(30) NOT NULL,
  `batch_id` bigint unsigned NOT NULL DEFAULT 0,
  `order_goods_id` bigint unsigned NOT NULL DEFAULT 0,
  `original_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `fulfilled_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `refundable_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `refund_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `formula_version` varchar(50) NOT NULL DEFAULT '',
  `calculation_json` longtext,
  `exception_reason_code` varchar(50) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_allocation` (`refund_id`,`allocation_type`,`batch_id`,`order_goods_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='例外退款分摊';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_policy_version` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `policy_type` varchar(30) NOT NULL,
  `policy_version` varchar(50) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` longtext NOT NULL,
  `content_hash` char(64) NOT NULL,
  `effective_at` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'draft',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_policy_version` (`policy_type`,`policy_version`),
  KEY `idx_policy_effective` (`policy_type`,`status`,`effective_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='不可变交易政策版本';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_order_consent` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `consent_sn` varchar(64) NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `order_id` bigint unsigned NOT NULL DEFAULT 0,
  `checkout_token_hash` char(64) NOT NULL,
  `consent_type` varchar(30) NOT NULL DEFAULT 'plan_non_refund',
  `policy_version` varchar(50) NOT NULL,
  `policy_title` varchar(255) NOT NULL,
  `policy_content_hash` char(64) NOT NULL,
  `displayed_at` bigint unsigned NOT NULL,
  `confirmed_at` bigint unsigned NOT NULL,
  `confirm_action` varchar(30) NOT NULL DEFAULT 'explicit_click',
  `ip_hash` char(64) NOT NULL DEFAULT '',
  `device_hash` char(64) NOT NULL DEFAULT '',
  `request_id` varchar(64) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_consent_sn` (`consent_sn`),
  UNIQUE KEY `uk_consent_checkout` (`checkout_token_hash`,`consent_type`,`policy_version`),
  KEY `idx_consent_order` (`order_id`,`consent_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='重要政策确认凭证';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_service_plan` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `plan_sn` varchar(64) NOT NULL,
  `agent_client_id` varchar(64) NOT NULL,
  `agent_task_id` varchar(100) NOT NULL,
  `request_digest` char(64) NOT NULL DEFAULT '',
  `user_id` bigint unsigned NOT NULL DEFAULT 0,
  `user_ref` varchar(100) NOT NULL DEFAULT '',
  `family_ref` varchar(100) NOT NULL DEFAULT '',
  `plan_name` varchar(255) NOT NULL DEFAULT '',
  `plan_days` int unsigned NOT NULL DEFAULT 21,
  `delivery_frequency` varchar(20) NOT NULL DEFAULT 'daily',
  `delivery_lead_days` int unsigned NOT NULL DEFAULT 1,
  `current_version` int unsigned NOT NULL DEFAULT 1,
  `requires_professional_review` tinyint unsigned NOT NULL DEFAULT 0,
  `review_gate_status` varchar(30) NOT NULL DEFAULT 'not_required',
  `nutrition_status` varchar(30) NOT NULL DEFAULT 'pending',
  `trade_status` varchar(30) NOT NULL DEFAULT 'pending',
  `estimated_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `currency` char(3) NOT NULL DEFAULT 'CNY',
  `status` varchar(30) NOT NULL DEFAULT 'draft',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_sn` (`plan_sn`),
  UNIQUE KEY `uk_plan_agent_task` (`agent_client_id`,`agent_task_id`),
  KEY `idx_plan_user` (`user_id`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI专属计划';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_service_plan_version` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `plan_id` bigint unsigned NOT NULL,
  `version_no` int unsigned NOT NULL,
  `base_version_no` int unsigned NOT NULL DEFAULT 0,
  `profile_version_refs_json` longtext,
  `catalog_version` varchar(64) NOT NULL DEFAULT '',
  `change_reason` varchar(500) NOT NULL DEFAULT '',
  `nutrition_validation_id` varchar(100) NOT NULL DEFAULT '',
  `nutrition_rules_version` varchar(100) NOT NULL DEFAULT '',
  `nutrition_status` varchar(30) NOT NULL DEFAULT 'pending',
  `nutrition_summary` varchar(500) NOT NULL DEFAULT '',
  `review_ref` varchar(100) NOT NULL DEFAULT '',
  `review_gate_status` varchar(30) NOT NULL DEFAULT 'not_required',
  `trade_status` varchar(30) NOT NULL DEFAULT 'pending',
  `pricing_draft_json` longtext,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_version` (`plan_id`,`version_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='专属计划不可变版本';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_service_plan_day` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `plan_version_id` bigint unsigned NOT NULL,
  `day_no` int unsigned NOT NULL,
  `relative_date_offset` int NOT NULL DEFAULT 0,
  `display_title` varchar(255) NOT NULL DEFAULT '',
  `daily_summary` varchar(500) NOT NULL DEFAULT '',
  `ingredient_requirements_json` longtext,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_day` (`plan_version_id`,`day_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='专属计划日历';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_service_plan_meal` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `plan_day_id` bigint unsigned NOT NULL,
  `meal_type` varchar(20) NOT NULL,
  `sort` int NOT NULL DEFAULT 0,
  `recipe_ref` varchar(100) NOT NULL,
  `recipe_version_ref` varchar(100) NOT NULL DEFAULT '',
  `recipe_name` varchar(255) NOT NULL DEFAULT '',
  `recipe_summary` varchar(500) NOT NULL DEFAULT '',
  `recipe_snapshot_json` longtext,
  `ingredient_requirements_json` longtext,
  `mapped_bundle_sku_id` bigint unsigned NOT NULL DEFAULT 0,
  `mapping_status` varchar(30) NOT NULL DEFAULT 'pending',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_plan_meal_day` (`plan_day_id`,`meal_type`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='专属计划餐次';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_service_plan_member` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `plan_id` bigint unsigned NOT NULL,
  `member_ref` varchar(100) NOT NULL,
  `profile_version_ref` varchar(100) NOT NULL DEFAULT '',
  `role` varchar(30) NOT NULL DEFAULT 'member',
  `display_alias` varchar(100) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_member` (`plan_id`,`member_ref`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='计划成员引用';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_professional_review_ref` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `review_ref` varchar(100) NOT NULL,
  `resource_type` varchar(30) NOT NULL,
  `resource_ref` varchar(100) NOT NULL,
  `resource_version` int unsigned NOT NULL,
  `member_refs_json` longtext,
  `review_system` varchar(50) NOT NULL DEFAULT '',
  `review_status` varchar(30) NOT NULL DEFAULT 'pending',
  `purchase_gate` varchar(30) NOT NULL DEFAULT 'blocked',
  `summary` varchar(500) NOT NULL DEFAULT '',
  `result_signature` varchar(255) NOT NULL DEFAULT '',
  `reviewed_at` bigint unsigned NOT NULL DEFAULT 0,
  `expired_at` bigint unsigned NOT NULL DEFAULT 0,
  `last_event_id` varchar(100) NOT NULL DEFAULT '',
  `payload_digest` char(64) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_ref` (`review_ref`),
  UNIQUE KEY `uk_review_resource` (`resource_type`,`resource_ref`,`resource_version`),
  KEY `idx_review_gate` (`review_status`,`purchase_gate`,`updatetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外部专业审核引用';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_service_plan_order` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `plan_order_sn` varchar(64) NOT NULL,
  `order_id` bigint unsigned NOT NULL DEFAULT 0,
  `order_sn` varchar(64) NOT NULL DEFAULT '',
  `plan_id` bigint unsigned NOT NULL,
  `plan_version_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `schedule_version` int unsigned NOT NULL DEFAULT 1,
  `first_delivery_date` date NOT NULL,
  `delivery_frequency` varchar(20) NOT NULL DEFAULT 'daily',
  `total_batches` int unsigned NOT NULL DEFAULT 21,
  `completed_batches` int unsigned NOT NULL DEFAULT 0,
  `total_amount_cent` bigint unsigned NOT NULL,
  `goods_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `shipping_fee_cent` bigint unsigned NOT NULL DEFAULT 0,
  `service_fee_cent` bigint unsigned NOT NULL DEFAULT 0,
  `discount_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `fulfilled_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `exception_refunded_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `user_cancellable` tinyint unsigned NOT NULL DEFAULT 0,
  `non_refund_consent_id` bigint unsigned NOT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'pending_payment',
  `pause_started_at` bigint unsigned NOT NULL DEFAULT 0,
  `resume_agent_validation_ref` varchar(100) NOT NULL DEFAULT '',
  `row_version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_order_sn` (`plan_order_sn`),
  UNIQUE KEY `uk_plan_order_order` (`order_id`),
  KEY `idx_plan_order_user` (`user_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='专属计划交易';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_plan_delivery_batch` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `batch_sn` varchar(64) NOT NULL,
  `plan_order_id` bigint unsigned NOT NULL,
  `batch_no` int unsigned NOT NULL,
  `schedule_version` int unsigned NOT NULL DEFAULT 1,
  `meal_date` date NOT NULL,
  `delivery_date` date NOT NULL,
  `inventory_lock_at` bigint unsigned NOT NULL,
  `delivery_slot_id` bigint unsigned NOT NULL DEFAULT 0,
  `cutoff_at` bigint unsigned NOT NULL DEFAULT 0,
  `address_snapshot_json` longtext,
  `goods_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `shipping_fee_cent` bigint unsigned NOT NULL DEFAULT 0,
  `service_fee_cent` bigint unsigned NOT NULL DEFAULT 0,
  `discount_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `allocated_pay_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `exception_refunded_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `inventory_status` varchar(30) NOT NULL DEFAULT 'pending',
  `supplier_status` varchar(30) NOT NULL DEFAULT 'pending',
  `fulfillment_status` varchar(30) NOT NULL DEFAULT 'pending',
  `aftersale_status` varchar(30) NOT NULL DEFAULT 'none',
  `status` varchar(30) NOT NULL DEFAULT 'scheduled',
  `row_version` int unsigned NOT NULL DEFAULT 1,
  `prepared_at` bigint unsigned NOT NULL DEFAULT 0,
  `shipped_at` bigint unsigned NOT NULL DEFAULT 0,
  `delivered_at` bigint unsigned NOT NULL DEFAULT 0,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_batch` (`plan_order_id`,`batch_no`),
  UNIQUE KEY `uk_batch_sn` (`batch_sn`),
  KEY `idx_batch_prepare` (`status`,`inventory_lock_at`),
  KEY `idx_batch_delivery` (`delivery_date`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='计划每日配送批次';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_plan_delivery_batch_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `batch_id` bigint unsigned NOT NULL,
  `goods_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `quantity` int unsigned NOT NULL,
  `unit_price_cent` bigint unsigned NOT NULL DEFAULT 0,
  `line_amount_cent` bigint unsigned NOT NULL DEFAULT 0,
  `discount_allocated_cent` bigint unsigned NOT NULL DEFAULT 0,
  `ingredient_codes_json` longtext,
  `sku_snapshot_json` longtext,
  `inventory_reservation_id` bigint unsigned NOT NULL DEFAULT 0,
  `supplier_order_item_id` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'scheduled',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_batch_item` (`batch_id`,`status`),
  KEY `idx_batch_item_sku` (`sku_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='配送批次商品';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_plan_change_request` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `change_request_sn` varchar(64) NOT NULL,
  `plan_order_id` bigint unsigned NOT NULL,
  `request_type` varchar(30) NOT NULL,
  `target_batch_ids_json` longtext,
  `base_version` int unsigned NOT NULL,
  `request_payload_json` longtext,
  `agent_revalidation_ref` varchar(100) NOT NULL DEFAULT '',
  `request_user_id` bigint unsigned NOT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'pending',
  `approved_admin_id` bigint unsigned NOT NULL DEFAULT 0,
  `processed_at` bigint unsigned NOT NULL DEFAULT 0,
  `failure_code` varchar(50) NOT NULL DEFAULT '',
  `failure_message` varchar(500) NOT NULL DEFAULT '',
  `request_id` varchar(64) NOT NULL,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_change_sn` (`change_request_sn`),
  UNIQUE KEY `uk_plan_change_request_id` (`request_id`),
  KEY `idx_plan_change_order` (`plan_order_id`,`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='计划暂停恢复及地址变更';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_supplier` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `supplier_code` varchar(64) NOT NULL,
  `name` varchar(100) NOT NULL,
  `company_name` varchar(255) NOT NULL DEFAULT '',
  `credit_code` varchar(64) DEFAULT NULL,
  `contact_name` varchar(100) NOT NULL DEFAULT '',
  `contact_mobile_encrypted` varchar(255) NOT NULL DEFAULT '',
  `interface_type` varchar(30) NOT NULL DEFAULT 'manual',
  `endpoint_url` varchar(500) NOT NULL DEFAULT '',
  `secret_ciphertext` varchar(500) NOT NULL DEFAULT '',
  `credential_ref` varchar(255) NOT NULL DEFAULT '',
  `service_area_json` longtext,
  `settlement_ref` varchar(100) NOT NULL DEFAULT '',
  `priority` int NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  `deletetime` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_supplier_code` (`supplier_code`),
  UNIQUE KEY `uk_supplier_credit_code` (`credit_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商档案';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_supplier_sku` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `supplier_id` bigint unsigned NOT NULL,
  `sku_id` bigint unsigned NOT NULL,
  `supplier_sku_code` varchar(100) NOT NULL,
  `supplier_sku_name` varchar(255) NOT NULL DEFAULT '',
  `purchase_price_cent` bigint unsigned NOT NULL DEFAULT 0,
  `minimum_order_quantity` int unsigned NOT NULL DEFAULT 1,
  `stock_status` varchar(30) NOT NULL DEFAULT 'unknown',
  `stock_quantity` int unsigned NOT NULL DEFAULT 0,
  `stock_updated_at` bigint unsigned NOT NULL DEFAULT 0,
  `service_area_json` longtext,
  `priority` int NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_supplier_sku` (`supplier_id`,`supplier_sku_code`),
  UNIQUE KEY `uk_supplier_platform_sku` (`supplier_id`,`sku_id`),
  KEY `idx_supplier_sku_candidate` (`sku_id`,`status`,`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商商品映射';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_supplier_order` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `supplier_order_sn` varchar(64) NOT NULL,
  `supplier_id` bigint unsigned NOT NULL,
  `platform_order_sn` varchar(64) NOT NULL DEFAULT '',
  `plan_batch_id` bigint unsigned NOT NULL DEFAULT 0,
  `external_order_no` varchar(100) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'created',
  `push_status` varchar(30) NOT NULL DEFAULT 'pending',
  `push_attempts` int unsigned NOT NULL DEFAULT 0,
  `next_retry_at` bigint unsigned NOT NULL DEFAULT 0,
  `accepted_at` bigint unsigned NOT NULL DEFAULT 0,
  `shipped_at` bigint unsigned NOT NULL DEFAULT 0,
  `completed_at` bigint unsigned NOT NULL DEFAULT 0,
  `reject_code` varchar(50) NOT NULL DEFAULT '',
  `address_snapshot_json` longtext,
  `request_snapshot_json` longtext,
  `response_snapshot_json` longtext,
  `row_version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_supplier_order_sn` (`supplier_order_sn`),
  UNIQUE KEY `uk_supplier_external_order` (`supplier_id`,`external_order_no`),
  KEY `idx_supplier_push` (`push_status`,`next_retry_at`),
  KEY `idx_supplier_platform_order` (`platform_order_sn`),
  KEY `idx_supplier_batch` (`plan_batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商订单';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_supplier_order_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `supplier_order_id` bigint unsigned NOT NULL,
  `order_goods_id` bigint unsigned NOT NULL DEFAULT 0,
  `plan_batch_item_id` bigint unsigned NOT NULL DEFAULT 0,
  `supplier_sku_id` bigint unsigned NOT NULL,
  `quantity` int unsigned NOT NULL,
  `purchase_price_cent` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'created',
  `unavailable_quantity` int unsigned NOT NULL DEFAULT 0,
  `reason_code` varchar(50) NOT NULL DEFAULT '',
  `item_snapshot_json` longtext,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_supplier_order_item` (`supplier_order_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商订单明细';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_fulfillment_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `event_id` varchar(100) NOT NULL,
  `source_type` varchar(30) NOT NULL,
  `source_ref` varchar(100) NOT NULL DEFAULT '',
  `platform_order_sn` varchar(64) NOT NULL DEFAULT '',
  `plan_batch_id` bigint unsigned NOT NULL DEFAULT 0,
  `supplier_order_id` bigint unsigned NOT NULL DEFAULT 0,
  `carrier_code` varchar(50) NOT NULL DEFAULT '',
  `tracking_no` varchar(100) NOT NULL DEFAULT '',
  `source_status` varchar(50) NOT NULL DEFAULT '',
  `normalized_status` varchar(30) NOT NULL,
  `occurred_at` bigint unsigned NOT NULL,
  `location` varchar(255) NOT NULL DEFAULT '',
  `description` varchar(500) NOT NULL DEFAULT '',
  `payload_json` longtext,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fulfillment_event` (`source_type`,`event_id`),
  KEY `idx_fulfillment_order` (`platform_order_sn`,`occurred_at`),
  KEY `idx_fulfillment_batch` (`plan_batch_id`,`occurred_at`),
  KEY `idx_tracking` (`carrier_code`,`tracking_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='履约物流事件';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_delivery_area` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `area_code` varchar(64) NOT NULL,
  `name` varchar(100) NOT NULL,
  `province_code` varchar(30) NOT NULL DEFAULT '',
  `city_code` varchar(30) NOT NULL DEFAULT '',
  `district_code` varchar(30) NOT NULL DEFAULT '',
  `polygon_json` longtext,
  `postal_codes_json` longtext,
  `supplier_id` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_delivery_area` (`area_code`,`supplier_id`),
  KEY `idx_delivery_admin` (`province_code`,`city_code`,`district_code`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='配送区域';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_delivery_slot` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `area_id` bigint unsigned NOT NULL,
  `slot_code` varchar(64) NOT NULL,
  `name` varchar(100) NOT NULL,
  `start_time` char(5) NOT NULL,
  `end_time` char(5) NOT NULL,
  `cutoff_minutes` int unsigned NOT NULL DEFAULT 0,
  `capacity` int unsigned NOT NULL DEFAULT 0,
  `used_capacity` int unsigned NOT NULL DEFAULT 0,
  `weekday_mask` varchar(20) NOT NULL DEFAULT '1,2,3,4,5,6,7',
  `blackout_dates_json` longtext,
  `extra_fee_cent` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_delivery_slot` (`area_id`,`slot_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='配送时段';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_supplier_application` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `application_sn` varchar(64) NOT NULL,
  `user_id` bigint unsigned NOT NULL DEFAULT 0,
  `company_name` varchar(255) NOT NULL,
  `credit_code` varchar(64) NOT NULL DEFAULT '',
  `contact_name` varchar(100) NOT NULL,
  `contact_mobile_encrypted` varchar(255) NOT NULL,
  `business_categories_json` longtext,
  `service_areas_json` longtext,
  `capacity_summary` varchar(1000) NOT NULL DEFAULT '',
  `qualification_files_json` longtext,
  `privacy_consent_version` varchar(50) NOT NULL,
  `review_status` varchar(30) NOT NULL DEFAULT 'pending',
  `review_admin_id` bigint unsigned NOT NULL DEFAULT 0,
  `review_comment` varchar(1000) NOT NULL DEFAULT '',
  `supplier_id` bigint unsigned NOT NULL DEFAULT 0,
  `submitted_at` bigint unsigned NOT NULL DEFAULT 0,
  `reviewed_at` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_supplier_application_sn` (`application_sn`),
  KEY `idx_supplier_application_user` (`user_id`,`createtime`),
  KEY `idx_supplier_application_review` (`review_status`,`submitted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商合作申请';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_exception_order` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `exception_sn` varchar(64) NOT NULL,
  `dedupe_key` varchar(128) NOT NULL,
  `severity` varchar(20) NOT NULL DEFAULT 'medium',
  `module` varchar(30) NOT NULL,
  `exception_type` varchar(50) NOT NULL,
  `resource_type` varchar(30) NOT NULL DEFAULT '',
  `resource_ref` varchar(100) NOT NULL DEFAULT '',
  `order_sn` varchar(64) NOT NULL DEFAULT '',
  `batch_id` bigint unsigned NOT NULL DEFAULT 0,
  `supplier_order_id` bigint unsigned NOT NULL DEFAULT 0,
  `summary` varchar(500) NOT NULL,
  `detail_json` longtext,
  `assignee_admin_id` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'open',
  `retry_count` int unsigned NOT NULL DEFAULT 0,
  `next_retry_at` bigint unsigned NOT NULL DEFAULT 0,
  `resolved_at` bigint unsigned NOT NULL DEFAULT 0,
  `resolution` varchar(1000) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exception_sn` (`exception_sn`),
  UNIQUE KEY `uk_exception_dedupe` (`dedupe_key`),
  KEY `idx_exception_todo` (`status`,`severity`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一异常任务';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_integration_client` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `client_id` varchar(64) NOT NULL,
  `client_type` varchar(30) NOT NULL,
  `name` varchar(100) NOT NULL,
  `secret_ciphertext` varchar(500) NOT NULL,
  `allowed_ip_json` longtext,
  `callback_whitelist_json` longtext,
  `clock_skew_seconds` int unsigned NOT NULL DEFAULT 300,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `version` int unsigned NOT NULL DEFAULT 1,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_integration_client` (`client_id`),
  KEY `idx_integration_client_type` (`client_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务间调用方';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_integration_nonce` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `client_id` varchar(64) NOT NULL,
  `nonce_hash` char(64) NOT NULL,
  `expires_at` bigint unsigned NOT NULL,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_nonce` (`client_id`,`nonce_hash`),
  KEY `idx_nonce_expire` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务签名防重放';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_integration_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `request_id` varchar(64) NOT NULL,
  `partner_type` varchar(30) NOT NULL,
  `partner_code` varchar(64) NOT NULL DEFAULT '',
  `direction` varchar(20) NOT NULL,
  `interface_name` varchar(100) NOT NULL,
  `method` varchar(10) NOT NULL DEFAULT '',
  `url_path` varchar(255) NOT NULL DEFAULT '',
  `business_type` varchar(30) NOT NULL DEFAULT '',
  `business_ref` varchar(100) NOT NULL DEFAULT '',
  `request_headers_masked` longtext,
  `request_body_masked` longtext,
  `response_code` varchar(50) NOT NULL DEFAULT '',
  `response_body_masked` longtext,
  `http_status` int unsigned NOT NULL DEFAULT 0,
  `duration_ms` int unsigned NOT NULL DEFAULT 0,
  `success` tinyint unsigned NOT NULL DEFAULT 0,
  `retry_count` int unsigned NOT NULL DEFAULT 0,
  `error_code` varchar(50) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_integration_request` (`request_id`),
  KEY `idx_integration_business` (`business_type`,`business_ref`),
  KEY `idx_integration_partner` (`partner_code`,`createtime`),
  KEY `idx_integration_failure` (`success`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外部接口脱敏日志';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_idempotency_record` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `scope` varchar(100) NOT NULL,
  `client_id` varchar(64) NOT NULL,
  `idempotency_key` varchar(64) NOT NULL,
  `request_hash` char(64) NOT NULL,
  `resource_type` varchar(30) NOT NULL DEFAULT '',
  `resource_ref` varchar(100) NOT NULL DEFAULT '',
  `response_code` int NOT NULL DEFAULT 0,
  `response_body` longtext,
  `status` varchar(20) NOT NULL DEFAULT 'processing',
  `locked_until` bigint unsigned NOT NULL DEFAULT 0,
  `expires_at` bigint unsigned NOT NULL DEFAULT 0,
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_idempotency` (`scope`,`client_id`,`idempotency_key`),
  KEY `idx_idempotency_expire` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='写接口幂等记录';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_outbox_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `event_id` varchar(100) NOT NULL,
  `event_type` varchar(100) NOT NULL,
  `aggregate_type` varchar(30) NOT NULL,
  `aggregate_ref` varchar(100) NOT NULL,
  `aggregate_version` int unsigned NOT NULL,
  `destination` varchar(100) NOT NULL,
  `payload_json` longtext,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `attempts` int unsigned NOT NULL DEFAULT 0,
  `next_retry_at` bigint unsigned NOT NULL DEFAULT 0,
  `locked_by` varchar(100) NOT NULL DEFAULT '',
  `locked_until` bigint unsigned NOT NULL DEFAULT 0,
  `sent_at` bigint unsigned NOT NULL DEFAULT 0,
  `last_error` varchar(1000) NOT NULL DEFAULT '',
  `createtime` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_outbox_event_id` (`event_id`),
  UNIQUE KEY `uk_outbox_aggregate_event` (`aggregate_type`,`aggregate_ref`,`aggregate_version`,`event_type`,`destination`),
  KEY `idx_outbox_dispatch` (`status`,`next_retry_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='可靠事件Outbox';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_job_lock` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `job_name` varchar(100) NOT NULL,
  `owner` varchar(100) NOT NULL DEFAULT '',
  `locked_until` bigint unsigned NOT NULL DEFAULT 0,
  `cursor_value` varchar(255) NOT NULL DEFAULT '',
  `version` int unsigned NOT NULL DEFAULT 1,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_job_name` (`job_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自动任务互斥锁';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_job_run` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `run_id` varchar(64) NOT NULL,
  `job_name` varchar(100) NOT NULL,
  `owner` varchar(100) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'running',
  `processed_count` int unsigned NOT NULL DEFAULT 0,
  `success_count` int unsigned NOT NULL DEFAULT 0,
  `failure_count` int unsigned NOT NULL DEFAULT 0,
  `cursor_before` varchar(255) NOT NULL DEFAULT '',
  `cursor_after` varchar(255) NOT NULL DEFAULT '',
  `last_error` varchar(1000) NOT NULL DEFAULT '',
  `started_at` bigint unsigned NOT NULL DEFAULT 0,
  `finished_at` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_job_run` (`run_id`),
  KEY `idx_job_run_name` (`job_name`,`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自动任务运行记录';

CREATE TABLE IF NOT EXISTS `__PREFIX__shop_metric_daily` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `metric_date` date NOT NULL,
  `metric_group` varchar(50) NOT NULL,
  `metric_key` varchar(100) NOT NULL,
  `dimension_key` varchar(100) NOT NULL DEFAULT '',
  `metric_value` decimal(20,4) NOT NULL DEFAULT 0,
  `metric_json` longtext,
  `calculated_at` bigint unsigned NOT NULL DEFAULT 0,
  `updatetime` bigint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_metric_daily` (`metric_date`,`metric_group`,`metric_key`,`dimension_key`),
  KEY `idx_metric_group` (`metric_group`,`metric_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='经营数据日聚合';
