<script setup>
import AppNavBar from '../../components/AppNavBar.vue'
import { computed,ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { getRecords,backHome } from '../../utils/profile.js'
import { mockService } from '../../services/mock.js'
import { intakeSummary } from '../../utils/scan-portions.js'
const id=ref(''),record=ref(null),editing=ref(false),busy=ref(false),draft=ref([]),error=ref('')
onLoad(o=>{id.value=String(o.id);record.value=getRecords().find(r=>String(r.id)===id.value)||null})
const people=computed(()=>record.value?.memberIntake?.length?record.value.memberIntake:[{memberId:record.value?.memberId,memberName:record.value?.memberName||'我',dishes:record.value?.dishes||[],portion:record.value?.portion||'不确定'}])
function edit(){draft.value=people.value.map(p=>({...p,dishText:(p.dishes||[]).join('、')}));editing.value=true}
async function save(){if(busy.value)return;busy.value=true;error.value='';try{const intake=draft.value.map(({dishText,...p})=>({...p,dishes:dishText.split(/[、，,]/).map(s=>s.trim()).filter(Boolean)}));if(intake.some(p=>!p.dishes.length&&!p.noneConfirmed))throw new Error('请填写每位成员实际吃过的菜品');record.value=await mockService.correctRecord(record.value.id,{memberIntake:intake,dishes:[...new Set(intake.flatMap(p=>p.dishes))],portion:intake.length===1?intake[0].portion:'逐人确认',kcal:null,low:null,high:null,protein:null,fat:null,carbs:null,sugars:null});editing.value=false;uni.showToast({title:'已保存更正版本',icon:'success'})}catch(e){error.value=e.message}finally{busy.value=false}}
</script>
<template><view class="screen"><AppNavBar><view class="nav-row"><button class="icon-button" @click="backHome">‹</button><text class="nav-title">饮食记录详情</text><text></text></view></AppNavBar><template v-if="record"><view class="page-heading"><text class="display-title">{{record.meal}} · 实际记录</text><text class="subtitle">{{record.source||'拍照分析'}} · v{{record.version||1}} · {{record.createdAt?.slice(0,10)||record.date||'今天'}}</text></view><image v-if="record.photoPath" class="record-photo" :src="record.photoPath" mode="aspectFill"/><text v-else-if="record.photo" class="demo-label">照片为本机临时文件，重新打开时可能不可用。</text><view v-if="!editing"><view v-for="person in people" :key="person.memberId" class="list-card card"><text class="section-title">{{person.memberName}}</text><text>{{person.dishes.join('、')}}</text><text>实际份量：{{intakeSummary(person)}}</text></view><view class="list-card card"><text class="section-title">摄入估算</text><text>{{record.kcal?'约 '+record.kcal+' kcal · 测试估算':'暂无法估算'}}</text><text>共享桌菜不平均分配整桌热量。更正事实后，旧估算不继续作为最新数据。</text></view><button class="primary-button" @click="edit">更正这条记录</button><button class="secondary-button feedback" @click="uni.navigateTo({url:'/pages/feedback/index'})">查看反馈</button></view><template v-else><view v-for="person in draft" :key="person.memberId" class="list-card card"><text class="section-title">{{person.memberName}}实际吃了什么</text><textarea v-model="person.dishText" class="text-area" placeholder="菜名用顿号分隔"/><text class="form-label">粗略份量</text><picker :range="['少量','一般','较多','不确定']" @change="person.portion=['少量','一般','较多','不确定'][$event.detail.value]"><view class="field-input portion">{{person.portion}} ›</view></picker></view><text v-if="error" class="inline-error">{{error}}</text><button class="primary-button" :disabled="busy" @click="save">{{busy?'正在保存…':'确认更正并保存'}}</button><button class="secondary-button feedback" @click="editing=false">取消</button></template></template><text v-else class="inline-error">记录不存在，请返回记录列表。</text></view></template>
<style scoped>.feedback{margin-top:20rpx}.portion{display:flex;align-items:center}.record-photo{width:100%;height:360rpx;border-radius:28rpx}</style>
