<script setup>
import AppNavBar from '../../components/AppNavBar.vue'
import { computed,ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { localDate } from '../../utils/meal-state.js'
import { backHome,getProfile,getRecords } from '../../utils/profile.js'
import { intakeSummary } from '../../utils/scan-portions.js'
const profile=ref(getProfile()),records=ref(getRecords()),scope=ref('all'),date=ref(localDate())
onShow(()=>{profile.value=getProfile();records.value=getRecords()})
const visible=computed(()=>records.value.filter(r=>(r.createdAt?localDate(new Date(r.createdAt)):String(r.date||'').slice(0,10))===date.value).filter(r=>scope.value==='all'||String(r.memberId)===String(scope.value)||r.memberIds?.map(String).includes(String(scope.value))))
function scopedIntake(record){return scope.value==='all'?null:record.memberIntake?.find(item=>String(item.memberId)===String(scope.value))}
function summary(record){const intake=scopedIntake(record);return {dishes:intake?intake.dishes||[]:record.dishes||[],portion:intake?intakeSummary(intake):intakeSummary({dishes:record.dishes||[],portion:record.portion||'粗略份量',grams:record.grams})}}
function detail(record){uni.navigateTo({url:'/pages/records/detail?id='+encodeURIComponent(record.id)})}
</script>
<template><view class="screen"><AppNavBar><view class="nav-row"><button class="icon-button" @click="backHome">‹</button><text class="nav-title">饮食记录</text><text class="pill">事实记录</text></view></AppNavBar><view class="hero"><text class="eyebrow">ORIGINAL RECORDS</text><text class="display-title">今天真正吃了什么</text><text>这里保留原始记录与更正版本，不代替 AI 反馈页。</text></view><scroll-view class="scope-tabs" scroll-x><view class="scope-row"><button :class="{active:scope==='all'}" @click="scope='all'">全家</button><button v-for="m in profile.members" :key="m.id" :class="{active:scope===m.id}" @click="scope=m.id">{{m.name}}</button></view></scroll-view><view class="date-card card"><picker mode="date" :value="date" @change="date=$event.detail.value"><text>{{date}} ›</text></picker><text>按北京时间归档</text></view><view class="meal-list"><view v-for="meal in ['早餐','午餐','晚餐']" :key="meal" class="meal-card card"><view class="meal-head"><text>{{meal}}</text><text>{{visible.filter(r=>r.meal===meal).length?'已记录':'未记录'}}</text></view><button v-for="r in visible.filter(item=>item.meal===meal)" :key="r.id" @click="detail(r)"><view class="photo-mark">{{r.photo?'图':'记'}}</view><view><text>{{summary(r).dishes.join('、')||'暂未确认菜品'}}</text><text>{{scopedIntake(r)?.memberName||(r.memberNames?.join('、')||r.memberName)}} · {{summary(r).portion}}</text></view><text>›</text></button><text v-if="!visible.some(r=>r.meal===meal)" class="missing">未记录不代表没有进食，不会被当作 0 摄入。</text></view></view></view></template>
<style scoped>.hero{display:flex;flex-direction:column;gap:12rpx;margin:43rpx 0 24rpx}.hero .display-title{font-size:44rpx}.hero>text:last-child{color:#6c7d75;font-size:21rpx;line-height:1.6}.scope-tabs{white-space:nowrap}.scope-tabs .scope-row{display:inline-flex;gap:10rpx}.scope-tabs button{padding:13rpx 23rpx;border-radius:17rpx;background:#eef0e8;color:#65776f;font-size:20rpx}.scope-tabs button.active{background:#246b50;color:#fff}.date-card{display:flex;justify-content:space-between;margin-top:18rpx;padding:20rpx}.date-card text:first-child{font-size:23rpx;font-weight:800}.date-card text:last-child{color:#7b8983;font-size:18rpx}.meal-list{display:flex;flex-direction:column;gap:14rpx;margin-top:18rpx}.meal-card{padding:22rpx}.meal-head{display:flex;justify-content:space-between;margin-bottom:12rpx}.meal-head text:first-child{font-size:26rpx;font-weight:900}.meal-head text:last-child{color:#246b50;font-size:18rpx;font-weight:800}.meal-card button{width:100%;display:flex;align-items:center;gap:14rpx;padding:14rpx 0;text-align:left}.photo-mark{width:58rpx;height:58rpx;display:flex;align-items:center;justify-content:center;border-radius:18rpx;background:#f0f3f1;color:#246b50;font-weight:900}.meal-card button>view:nth-child(2){flex:1;display:flex;flex-direction:column;gap:6rpx}.meal-card button>view:nth-child(2) text:first-child{font-size:21rpx;font-weight:800}.meal-card button>view:nth-child(2) text:last-child,.missing{color:#7a8982;font-size:18rpx;line-height:1.5}.missing{display:block;padding:12rpx 0}</style>
