<script setup>
import AppNavBar from '../../components/AppNavBar.vue'
import { computed,ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { backHome,getProfile } from '../../utils/profile.js'
import { todayPlan } from '../../utils/meal-state.js'
import { createMealBundles } from '../../utils/meal-bundles.js'
import { mealFromRoute,mealToRoute } from '../../utils/meal-flow.js'
const profile=ref(getProfile()),meal=ref('晚餐'),bundleId=ref('')
const plan=computed(()=>todayPlan(profile.value,meal.value)),bundle=computed(()=>createMealBundles(plan.value).find(b=>b.id===bundleId.value)||createMealBundles(plan.value)[0]),products=computed(()=>plan.value.products.filter(p=>bundle.value?.productIds.includes(p.id)))
onLoad(o=>{meal.value=mealFromRoute(o.meal);bundleId.value=o.bundle||''})
function next(){uni.navigateTo({url:`/pages/shop/index?meal=${mealToRoute(meal.value)}&bundle=${encodeURIComponent(bundle.value.id)}&checkout=1`})}
function menu(){uni.navigateTo({url:`/pages/shop/index?meal=${mealToRoute(meal.value)}&bundle=${encodeURIComponent(bundle.value.id)}`})}
</script>
<template><view v-if="bundle" class="screen detail"><AppNavBar><view class="nav-row"><button class="icon-button" @click="backHome">‹</button><text class="nav-title">食材包详情</text><text class="pill">测试数据</text></view></AppNavBar><image class="hero-image" :src="bundle.image" mode="aspectFill"/><view class="product-head"><text class="eyebrow">{{bundle.category}} · 对应{{meal}}</text><text class="display-title">{{bundle.name}}</text><text>{{bundle.spec}}</text><text class="price">¥{{(bundle.priceCents/100).toFixed(2)}}</text></view><view class="card contents"><text class="section-title">这个包里有什么</text><view v-for="p in products" :key="p.id"><text>{{p.icon}} {{p.name}}</text><text>{{p.pack}}{{p.unit}}/包 × {{p.quantity}}包</text></view><text class="data-note">商品、规格和价格为测试数据，不是实时库存或履约承诺。</text></view><button class="recipe card" @click="menu"><view><text>对应菜品与做法</text><text>查看{{meal}}菜单和烹饪入口</text></view><text>›</text></button><button class="other" @click="uni.navigateTo({url:'/pages/shop/index?meal='+mealToRoute(meal)})">查看本餐其他食材包 →</button><view class="bottom"><button class="primary-button" @click="next">下一步 · 核对订单</button><text>{{plan.safetyText}}</text></view></view></template>
<style scoped>.detail{padding-bottom:180rpx}.hero-image{width:100%;height:360rpx;margin-top:25rpx;border-radius:34rpx;background:#e8eddd}.product-head{display:flex;flex-direction:column;gap:10rpx;margin-top:24rpx}.product-head .display-title{font-size:43rpx}.product-head>text:nth-child(3){color:#71827a;font-size:20rpx}.price{color:#a34c37;font-size:39rpx;font-weight:900}.contents{margin-top:23rpx;padding:26rpx}.contents .section-title{display:block;margin-bottom:13rpx}.contents>view{display:flex;justify-content:space-between;padding:15rpx 0;border-bottom:1rpx solid rgba(24,54,46,.08);font-size:20rpx}.contents>view text:last-child{color:#708078}.data-note{display:block;margin-top:16rpx;color:#8a5d4e;font-size:18rpx;line-height:1.5}.recipe{width:100%;display:flex;align-items:center;justify-content:space-between;margin-top:17rpx;padding:22rpx;text-align:left}.recipe>view{display:flex;flex-direction:column;gap:7rpx}.recipe>view text:first-child{font-size:22rpx;font-weight:900}.recipe>view text:last-child{color:#74847d;font-size:18rpx}.recipe>text:last-child{font-size:32rpx;color:#7e8c85}.other{width:100%;margin-top:17rpx;color:#246b50;font-size:21rpx;font-weight:800}.bottom{position:fixed;z-index:10;left:0;right:0;bottom:0;padding:18rpx 30rpx calc(env(safe-area-inset-bottom) + 18rpx);border-top:1rpx solid rgba(24,54,46,.08);background:#ffffff}.bottom text{display:block;margin-top:9rpx;color:#7a5a4e;font-size:16rpx;text-align:center}</style>
